//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane-contrib/provider-infoblox-nios/apis/common/driftdetection"
	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DTCPool) DeepCopyInto(out *DTCPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DTCPool.
func (in *DTCPool) DeepCopy() *DTCPool {
	if in == nil {
		return nil
	}
	out := new(DTCPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DTCPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DTCPoolConsolidatedMonitorHealth) DeepCopyInto(out *DTCPoolConsolidatedMonitorHealth) {
	*out = *in
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Monitor != nil {
		in, out := &in.Monitor, &out.Monitor
		*out = new(string)
		**out = **in
	}
	if in.Availability != nil {
		in, out := &in.Availability, &out.Availability
		*out = new(string)
		**out = **in
	}
	if in.FullHealthCommunication != nil {
		in, out := &in.FullHealthCommunication, &out.FullHealthCommunication
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DTCPoolConsolidatedMonitorHealth.
func (in *DTCPoolConsolidatedMonitorHealth) DeepCopy() *DTCPoolConsolidatedMonitorHealth {
	if in == nil {
		return nil
	}
	out := new(DTCPoolConsolidatedMonitorHealth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DTCPoolDynamicRatio) DeepCopyInto(out *DTCPoolDynamicRatio) {
	*out = *in
	if in.Method != nil {
		in, out := &in.Method, &out.Method
		*out = new(string)
		**out = **in
	}
	if in.Monitor != nil {
		in, out := &in.Monitor, &out.Monitor
		*out = new(string)
		**out = **in
	}
	if in.MonitorMetric != nil {
		in, out := &in.MonitorMetric, &out.MonitorMetric
		*out = new(string)
		**out = **in
	}
	if in.MonitorWeighing != nil {
		in, out := &in.MonitorWeighing, &out.MonitorWeighing
		*out = new(string)
		**out = **in
	}
	if in.InvertMonitorMetric != nil {
		in, out := &in.InvertMonitorMetric, &out.InvertMonitorMetric
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DTCPoolDynamicRatio.
func (in *DTCPoolDynamicRatio) DeepCopy() *DTCPoolDynamicRatio {
	if in == nil {
		return nil
	}
	out := new(DTCPoolDynamicRatio)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DTCPoolHealth) DeepCopyInto(out *DTCPoolHealth) {
	*out = *in
	if in.Availability != nil {
		in, out := &in.Availability, &out.Availability
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.EnabledState != nil {
		in, out := &in.EnabledState, &out.EnabledState
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DTCPoolHealth.
func (in *DTCPoolHealth) DeepCopy() *DTCPoolHealth {
	if in == nil {
		return nil
	}
	out := new(DTCPoolHealth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DTCPoolList) DeepCopyInto(out *DTCPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DTCPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DTCPoolList.
func (in *DTCPoolList) DeepCopy() *DTCPoolList {
	if in == nil {
		return nil
	}
	out := new(DTCPoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DTCPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DTCPoolMonitor) DeepCopyInto(out *DTCPoolMonitor) {
	*out = *in
	if in.Monitor != nil {
		in, out := &in.Monitor, &out.Monitor
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DTCPoolMonitor.
func (in *DTCPoolMonitor) DeepCopy() *DTCPoolMonitor {
	if in == nil {
		return nil
	}
	out := new(DTCPoolMonitor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DTCPoolObservation) DeepCopyInto(out *DTCPoolObservation) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.LBPreferredMethod != nil {
		in, out := &in.LBPreferredMethod, &out.LBPreferredMethod
		*out = new(string)
		**out = **in
	}
	if in.LBAlternateMethod != nil {
		in, out := &in.LBAlternateMethod, &out.LBAlternateMethod
		*out = new(string)
		**out = **in
	}
	if in.Servers != nil {
		in, out := &in.Servers, &out.Servers
		*out = make([]DTCPoolServerLink, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Availability != nil {
		in, out := &in.Availability, &out.Availability
		*out = new(string)
		**out = **in
	}
	if in.Quorum != nil {
		in, out := &in.Quorum, &out.Quorum
		*out = new(uint32)
		**out = **in
	}
	if in.LBPreferredTopology != nil {
		in, out := &in.LBPreferredTopology, &out.LBPreferredTopology
		*out = new(string)
		**out = **in
	}
	if in.LBDynamicRatioPreferred != nil {
		in, out := &in.LBDynamicRatioPreferred, &out.LBDynamicRatioPreferred
		*out = new(DTCPoolDynamicRatio)
		(*in).DeepCopyInto(*out)
	}
	if in.LBAlternateTopology != nil {
		in, out := &in.LBAlternateTopology, &out.LBAlternateTopology
		*out = new(string)
		**out = **in
	}
	if in.LBDynamicRatioAlternate != nil {
		in, out := &in.LBDynamicRatioAlternate, &out.LBDynamicRatioAlternate
		*out = new(DTCPoolDynamicRatio)
		(*in).DeepCopyInto(*out)
	}
	if in.Monitors != nil {
		in, out := &in.Monitors, &out.Monitors
		*out = make([]DTCPoolMonitor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Comment != nil {
		in, out := &in.Comment, &out.Comment
		*out = new(string)
		**out = **in
	}
	if in.Disable != nil {
		in, out := &in.Disable, &out.Disable
		*out = new(bool)
		**out = **in
	}
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(uint32)
		**out = **in
	}
	if in.UseTTL != nil {
		in, out := &in.UseTTL, &out.UseTTL
		*out = new(bool)
		**out = **in
	}
	if in.ExtAttrs != nil {
		in, out := &in.ExtAttrs, &out.ExtAttrs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Ref != nil {
		in, out := &in.Ref, &out.Ref
		*out = new(string)
		**out = **in
	}
	if in.ConsolidatedMonitors != nil {
		in, out := &in.ConsolidatedMonitors, &out.ConsolidatedMonitors
		*out = make([]DTCPoolConsolidatedMonitorHealth, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Health != nil {
		in, out := &in.Health, &out.Health
		*out = new(DTCPoolHealth)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DTCPoolObservation.
func (in *DTCPoolObservation) DeepCopy() *DTCPoolObservation {
	if in == nil {
		return nil
	}
	out := new(DTCPoolObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DTCPoolParameters) DeepCopyInto(out *DTCPoolParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.LBPreferredMethod != nil {
		in, out := &in.LBPreferredMethod, &out.LBPreferredMethod
		*out = new(string)
		**out = **in
	}
	if in.LBAlternateMethod != nil {
		in, out := &in.LBAlternateMethod, &out.LBAlternateMethod
		*out = new(string)
		**out = **in
	}
	if in.Servers != nil {
		in, out := &in.Servers, &out.Servers
		*out = make([]DTCPoolServerLink, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Availability != nil {
		in, out := &in.Availability, &out.Availability
		*out = new(string)
		**out = **in
	}
	if in.Quorum != nil {
		in, out := &in.Quorum, &out.Quorum
		*out = new(uint32)
		**out = **in
	}
	if in.LBPreferredTopology != nil {
		in, out := &in.LBPreferredTopology, &out.LBPreferredTopology
		*out = new(string)
		**out = **in
	}
	if in.LBDynamicRatioPreferred != nil {
		in, out := &in.LBDynamicRatioPreferred, &out.LBDynamicRatioPreferred
		*out = new(DTCPoolDynamicRatio)
		(*in).DeepCopyInto(*out)
	}
	if in.LBAlternateTopology != nil {
		in, out := &in.LBAlternateTopology, &out.LBAlternateTopology
		*out = new(string)
		**out = **in
	}
	if in.LBDynamicRatioAlternate != nil {
		in, out := &in.LBDynamicRatioAlternate, &out.LBDynamicRatioAlternate
		*out = new(DTCPoolDynamicRatio)
		(*in).DeepCopyInto(*out)
	}
	if in.Monitors != nil {
		in, out := &in.Monitors, &out.Monitors
		*out = make([]DTCPoolMonitor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Comment != nil {
		in, out := &in.Comment, &out.Comment
		*out = new(string)
		**out = **in
	}
	if in.Disable != nil {
		in, out := &in.Disable, &out.Disable
		*out = new(bool)
		**out = **in
	}
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(uint32)
		**out = **in
	}
	if in.UseTTL != nil {
		in, out := &in.UseTTL, &out.UseTTL
		*out = new(bool)
		**out = **in
	}
	if in.ExtAttrs != nil {
		in, out := &in.ExtAttrs, &out.ExtAttrs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DTCPoolParameters.
func (in *DTCPoolParameters) DeepCopy() *DTCPoolParameters {
	if in == nil {
		return nil
	}
	out := new(DTCPoolParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DTCPoolServerLink) DeepCopyInto(out *DTCPoolServerLink) {
	*out = *in
	if in.Server != nil {
		in, out := &in.Server, &out.Server
		*out = new(string)
		**out = **in
	}
	if in.ServerRef != nil {
		in, out := &in.ServerRef, &out.ServerRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.ServerSelector != nil {
		in, out := &in.ServerSelector, &out.ServerSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Ratio != nil {
		in, out := &in.Ratio, &out.Ratio
		*out = new(uint32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DTCPoolServerLink.
func (in *DTCPoolServerLink) DeepCopy() *DTCPoolServerLink {
	if in == nil {
		return nil
	}
	out := new(DTCPoolServerLink)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DTCPoolSpec) DeepCopyInto(out *DTCPoolSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	if in.DriftDetection != nil {
		in, out := &in.DriftDetection, &out.DriftDetection
		*out = new(driftdetection.DriftDetection)
		(*in).DeepCopyInto(*out)
	}
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DTCPoolSpec.
func (in *DTCPoolSpec) DeepCopy() *DTCPoolSpec {
	if in == nil {
		return nil
	}
	out := new(DTCPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DTCPoolStatus) DeepCopyInto(out *DTCPoolStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DTCPoolStatus.
func (in *DTCPoolStatus) DeepCopy() *DTCPoolStatus {
	if in == nil {
		return nil
	}
	out := new(DTCPoolStatus)
	in.DeepCopyInto(out)
	return out
}
