// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1alpha1 "github.com/crossplane-contrib/provider-infoblox-nios/apis/cluster/dtcserver/v1alpha1"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this DTCPool.
func (mg *DTCPool) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.Servers); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Servers[i3].Server),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.Servers[i3].ServerRef,
			Selector:     mg.Spec.ForProvider.Servers[i3].ServerSelector,
			To: reference.To{
				List:    &v1alpha1.DTCServerList{},
				Managed: &v1alpha1.DTCServer{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Servers[i3].Server")
		}
		mg.Spec.ForProvider.Servers[i3].Server = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Servers[i3].ServerRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Status.AtProvider.Servers); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Status.AtProvider.Servers[i3].Server),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Status.AtProvider.Servers[i3].ServerRef,
			Selector:     mg.Status.AtProvider.Servers[i3].ServerSelector,
			To: reference.To{
				List:    &v1alpha1.DTCServerList{},
				Managed: &v1alpha1.DTCServer{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Status.AtProvider.Servers[i3].Server")
		}
		mg.Status.AtProvider.Servers[i3].Server = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Status.AtProvider.Servers[i3].ServerRef = rsp.ResolvedReference

	}

	return nil
}
