// Code generated by openapi2crd. DO NOT EDIT.

// Package v1alpha1 contains the Namespaced-scoped DNSView managed resource.
// API group: dnsview.infobloxnios.m.crossplane.io
package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	xpv2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DNSViewNameServer describes one customized root name server entry (mirrors the SDK's NameServer struct).
type DNSViewNameServer struct {
	// The IPv4 address or IPv6 address of the server.
	Address *string `json:"address,omitempty"`
	// A resolvable domain name for the external DNS server.
	Name *string `json:"name,omitempty"`
	// Whether the name server is shared with the parent Microsoft primary zone's delegation server.
	SharedWithMsParentDelegation *bool `json:"sharedWithMsParentDelegation,omitempty"`
	// Hide the NS record for the primary name server from DNS queries.
	Stealth *bool `json:"stealth,omitempty"`
	// A generated TSIG key.
	TsigKey *string `json:"tsigKey,omitempty"`
	// The TSIG key algorithm.
	TsigKeyAlg *string `json:"tsigKeyAlg,omitempty"`
	// The TSIG key name.
	TsigKeyName *string `json:"tsigKeyName,omitempty"`
	// Use flag for: tsig_key_name.
	UseTsigKeyName *bool `json:"useTsigKeyName,omitempty"`
}

// DNSViewDnssecTrustedKey describes one DNSSEC trusted key entry (mirrors the SDK's Dnssectrustedkey struct).
type DNSViewDnssecTrustedKey struct {
	// The FQDN of the domain for which the member validates responses to recursive queries.
	Fqdn *string `json:"fqdn,omitempty"`
	// The DNSSEC algorithm used to generate the key.
	Algorithm *string `json:"algorithm,omitempty"`
	// The DNSSEC key.
	Key *string `json:"key,omitempty"`
	// The secure entry point flag; if set, this is a KSK configuration.
	SecureEntryPoint *bool `json:"secureEntryPoint,omitempty"`
	// Responses must be DNSSEC secure for this hierarchy/domain.
	DnssecMustBeSecure *bool `json:"dnssecMustBeSecure,omitempty"`
}

// DNSViewAddressAc describes one address/ACL access-control entry (mirrors the SDK's Addressac struct). Reused across filterAaaaList, matchClients, and matchDestinations.
type DNSViewAddressAc struct {
	// The address this rule applies to, or "Any".
	Address *string `json:"address,omitempty"`
	// The permission to use for this address.
	Permission *string `json:"permission,omitempty"`
	// A generated TSIG key.
	TsigKey *string `json:"tsigKey,omitempty"`
	// The TSIG key algorithm.
	TsigKeyAlg *string `json:"tsigKeyAlg,omitempty"`
	// The name of the TSIG key.
	TsigKeyName *string `json:"tsigKeyName,omitempty"`
	// Use flag for: tsig_key_name.
	UseTsigKeyName *bool `json:"useTsigKeyName,omitempty"`
}

// DNSViewFixedRrsetOrderFqdn describes one fixed RRset order FQDN entry (mirrors the SDK's GridDnsFixedrrsetorderfqdn struct).
type DNSViewFixedRrsetOrderFqdn struct {
	// The FQDN of the fixed RRset configuration item.
	Fqdn *string `json:"fqdn,omitempty"`
	// The record type for the specified FQDN in the fixed RRset configuration.
	RecordType *string `json:"recordType,omitempty"`
}

// DNSViewResponseRateLimiting carries response rate limiting settings for the DNS view (mirrors the SDK's GridResponseratelimiting struct).
type DNSViewResponseRateLimiting struct {
	// Determines if response rate limiting is enabled or not.
	EnableRrl *bool `json:"enableRrl,omitempty"`
	// Determines if logging for response rate limiting without dropping any requests is enabled or not.
	LogOnly *bool `json:"logOnly,omitempty"`
	// The number of responses per client per second.
	ResponsesPerSecond *uint32 `json:"responsesPerSecond,omitempty"`
	// The time interval in seconds over which responses are tracked.
	Window *uint32 `json:"window,omitempty"`
	// The response rate limiting slip. If slip is not 0, every n-th rate-limited UDP request is sent a truncated response instead of being dropped.
	Slip *uint32 `json:"slip,omitempty"`
}

// DNSViewScavengingSettings carries resource-record scavenging settings for the DNS view (mirrors the SDK's SettingScavenging struct).
type DNSViewScavengingSettings struct {
	// Indicates if resource record scavenging is enabled or not.
	EnableScavenging *bool `json:"enableScavenging,omitempty"`
	// Indicates if recurrent resource record scavenging is enabled or not.
	EnableRecurrentScavenging *bool `json:"enableRecurrentScavenging,omitempty"`
	// Indicates if automatic resource record scavenging is enabled or not.
	EnableAutoReclamation *bool `json:"enableAutoReclamation,omitempty"`
	// Indicates if resource record last-queried monitoring in affected zones is enabled or not.
	EnableRrLastQueried *bool `json:"enableRrLastQueried,omitempty"`
	// Indicates if last-queried monitoring for affected zones is enabled or not.
	EnableZoneLastQueried *bool `json:"enableZoneLastQueried,omitempty"`
	// Indicates if associated resource record scavenging is enabled or not.
	ReclaimAssociatedRecords *bool `json:"reclaimAssociatedRecords,omitempty"`
	// Schedule setting for the scavenging task.
	ScavengingSchedule *DNSViewScavengingSchedule `json:"scavengingSchedule,omitempty"`
	// The expression list. A record is treated as reclaimable if the expression evaluates to 'true' for it, unless scavenging has been manually disabled on that record.
	// +optional
	ExpressionList []*DNSViewExpressionOp `json:"expressionList"`
	// The extensible attributes expression list. A record is treated as reclaimable if the extensible-attributes expression evaluates to 'true' for it, unless scavenging has been manually disabled on that record.
	// +optional
	EaExpressionList []*DNSViewEaExpressionOp `json:"eaExpressionList"`
}

// DNSViewScavengingSchedule carries schedule settings for a scavenging task (mirrors the SDK's SettingSchedule struct).
type DNSViewScavengingSchedule struct {
	// Days of the week when scheduling is triggered.
	// +optional
	Weekdays []string `json:"weekdays"`
	// The time zone for the schedule.
	TimeZone *string `json:"timeZone,omitempty"`
	// The recurring time for the schedule, in Epoch seconds. Obsolete — preserved for backward compatibility; prefer year/month/day_of_month/hour_of_day/minutes_past_hour.
	RecurringTime *int64 `json:"recurringTime,omitempty"`
	// The frequency for the scheduled task.
	Frequency *string `json:"frequency,omitempty"`
	// The number of frequency units to wait before repeating the scheduled task.
	Every *uint32 `json:"every,omitempty"`
	// The minutes past the hour for the scheduled task.
	MinutesPastHour *uint32 `json:"minutesPastHour,omitempty"`
	// The hour of day for the scheduled task.
	HourOfDay *uint32 `json:"hourOfDay,omitempty"`
	// The year for the scheduled task.
	Year *uint32 `json:"year,omitempty"`
	// The month for the scheduled task.
	Month *uint32 `json:"month,omitempty"`
	// The day of the month for the scheduled task.
	DayOfMonth *uint32 `json:"dayOfMonth,omitempty"`
	// Indicates if the scheduled task repeats or runs only once.
	Repeat *string `json:"repeat,omitempty"`
	// If set to true, the scheduled task is disabled.
	Disable *bool `json:"disable,omitempty"`
}

// DNSViewExpressionOp describes one scavenging expression operand pair (mirrors the SDK's Expressionop struct).
type DNSViewExpressionOp struct {
	// The operation name.
	Op *string `json:"op,omitempty"`
	// The first operand value.
	Op1 *string `json:"op1,omitempty"`
	// The first operand type.
	Op1Type *string `json:"op1Type,omitempty"`
	// The second operand value.
	Op2 *string `json:"op2,omitempty"`
	// The second operand type.
	Op2Type *string `json:"op2Type,omitempty"`
}

// DNSViewEaExpressionOp describes one scavenging extensible-attributes expression operand pair (mirrors the SDK's Eaexpressionop struct).
type DNSViewEaExpressionOp struct {
	// The operation name.
	Op *string `json:"op,omitempty"`
	// The name of the Extensible Attribute Definition object used as the first operand value.
	Op1 *string `json:"op1,omitempty"`
	// The first operand type.
	Op1Type *string `json:"op1Type,omitempty"`
	// The second operand value.
	Op2 *string `json:"op2,omitempty"`
	// The second operand type.
	Op2Type *string `json:"op2Type,omitempty"`
}

// DNSViewSortlistEntry describes one sortlist entry (mirrors the SDK's Sortlist struct; renamed to avoid a name clash with the Sortlist field).
type DNSViewSortlistEntry struct {
	// The source address of a sortlist entry.
	Address *string `json:"address,omitempty"`
	// The match list of a sortlist entry.
	// +optional
	MatchList []string `json:"matchList"`
}

// DNSViewCloudInfo carries Cloud API delegation/ownership information for a cloud-managed DNSView (mirrors the SDK's GridCloudapiInfo struct).
type DNSViewCloudInfo struct {
	// The Cloud Platform Appliance to which authority of the object is delegated.
	DelegatedMember *DNSViewCloudInfoDelegatedMember `json:"delegatedMember,omitempty"`
	// Indicates the scope of delegation for the object: NONE (outside any delegation), ROOT (the delegation point), SUBTREE (within the scope of a delegation), or RECLAIMING (within the scope of a delegation being reclaimed).
	DelegatedScope *string `json:"delegatedScope,omitempty"`
	// Indicates the root of the delegation if delegated_scope is SUBTREE or RECLAIMING. Not set otherwise.
	DelegatedRoot *string `json:"delegatedRoot,omitempty"`
	// Determines whether the object was created by the cloud adapter or not.
	OwnedByAdaptor *bool `json:"ownedByAdaptor,omitempty"`
	// Indicates the cloud origin of the object.
	Usage *string `json:"usage,omitempty"`
	// Reference to the tenant object associated with the object, if any.
	Tenant *string `json:"tenant,omitempty"`
	// Indicates the specified cloud management platform.
	MgmtPlatform *string `json:"mgmtPlatform,omitempty"`
	// Type of authority over the object.
	AuthorityType *string `json:"authorityType,omitempty"`
}

// DNSViewCloudInfoDelegatedMember identifies the Grid member a cloud-managed DNSView's authority is delegated to (mirrors the SDK's Dhcpmember struct).
type DNSViewCloudInfoDelegatedMember struct {
	// The IPv4 Address of the Grid Member.
	Ipv4Addr *string `json:"ipv4Addr,omitempty"`
	// The IPv6 Address of the Grid Member.
	Ipv6Addr *string `json:"ipv6Addr,omitempty"`
	// The Grid member name.
	Name *string `json:"name,omitempty"`
}

// DNSViewParameters are the configurable fields of a DNSView.
type DNSViewParameters struct {
	// Name of the DNS view. Renaming an existing view changes its _ref (DNSView is in the _ref-unstable resource group — the controller re-reads _ref from the PUT response and updates the external-name annotation).
	// +kubebuilder:validation:Required
	Name *string `json:"name"`
	// Comment for the DNS view; maximum 64 characters.
	Comment *string `json:"comment,omitempty"`
	// The name of the network view object associated with this DNS view.
	NetworkView *string `json:"networkView,omitempty"`
	// Determines if the DNS view is disabled or not. When this is set to false, the DNS view is enabled.
	Disable *bool `json:"disable,omitempty"`
	// The action to perform when a domain name matches the pattern defined in a rule specified by the blacklist ruleset. The default value is "REFUSE".
	// +kubebuilder:validation:Enum=REDIRECT;REFUSE
	BlacklistAction *string `json:"blacklistAction,omitempty"`
	// The flag that indicates whether blacklist redirection queries are logged. The default value is false.
	BlacklistLogQuery *bool `json:"blacklistLogQuery,omitempty"`
	// The array of IP addresses the appliance includes in the response it sends in place of a blacklisted IP address.
	// +optional
	BlacklistRedirectAddresses []string `json:"blacklistRedirectAddresses"`
	// The Time To Live (TTL), in seconds, of the synthetic DNS responses resulting from blacklist redirection. Must be non-negative (0-2147483647); NIOS has no zone/grid-default sentinel for this field, so out-of-range values are rejected outright.
	// +kubebuilder:validation:Minimum=0
	// +kubebuilder:validation:Maximum=2147483647
	BlacklistRedirectTTL *uint32 `json:"blacklistRedirectTtl,omitempty"`
	// The name of the Ruleset object assigned at the Grid level for blacklist redirection.
	// +optional
	BlacklistRulesets []string `json:"blacklistRulesets"`
	// Use flag for: blacklist_action, blacklist_log_query, blacklist_redirect_addresses, blacklist_redirect_ttl, blacklist_rulesets, enable_blacklist.
	UseBlacklist *bool `json:"useBlacklist,omitempty"`
	// Determines if the blacklist in a DNS view is enabled or not.
	EnableBlacklist *bool `json:"enableBlacklist,omitempty"`
	// The list of customized root name servers. Select and use Internet root name servers, or specify custom root name servers by providing a host name and IP address to which the appliance can send queries.
	// +optional
	CustomRootNameServers []DNSViewNameServer `json:"customRootNameServers"`
	// Determines the type of root name servers.
	RootNameServerType *string `json:"rootNameServerType,omitempty"`
	// Use flag for: custom_root_name_servers, root_name_server_type.
	UseRootNameServer *bool `json:"useRootNameServer,omitempty"`
	// Defines whether the creation timestamp of a resource record is updated when a DDNS update happens, even if there is no change to the resource record.
	DdnsForceCreationTimestampUpdate *bool `json:"ddnsForceCreationTimestampUpdate,omitempty"`
	// Use flag for: ddns_force_creation_timestamp_update.
	UseDdnsForceCreationTimestampUpdate *bool `json:"useDdnsForceCreationTimestampUpdate,omitempty"`
	// The DDNS Principal cluster group name.
	DdnsPrincipalGroup *string `json:"ddnsPrincipalGroup,omitempty"`
	// The flag that indicates whether the DDNS principal track is enabled or disabled.
	DdnsPrincipalTracking *bool `json:"ddnsPrincipalTracking,omitempty"`
	// Use flag for: ddns_restrict_secure, ddns_principal_tracking, ddns_principal_group.
	UseDdnsPrincipalSecurity *bool `json:"useDdnsPrincipalSecurity,omitempty"`
	// The flag that indicates whether an option to restrict DDNS update requests based on FQDN patterns is enabled or disabled.
	DdnsRestrictPatterns *bool `json:"ddnsRestrictPatterns,omitempty"`
	// The unordered list of restriction patterns for the option to restrict DDNS updates based on FQDN patterns.
	// +optional
	DdnsRestrictPatternsList []string `json:"ddnsRestrictPatternsList"`
	// Use flag for: ddns_restrict_patterns_list, ddns_restrict_patterns.
	UseDdnsPatternsRestriction *bool `json:"useDdnsPatternsRestriction,omitempty"`
	// The flag that indicates whether an option to restrict DDNS update requests to protected resource records is enabled or disabled.
	DdnsRestrictProtected *bool `json:"ddnsRestrictProtected,omitempty"`
	// Use flag for: ddns_restrict_protected.
	UseDdnsRestrictProtected *bool `json:"useDdnsRestrictProtected,omitempty"`
	// The flag that indicates whether DDNS update requests for a principal other than the target resource record's principal are restricted.
	DdnsRestrictSecure *bool `json:"ddnsRestrictSecure,omitempty"`
	// The flag that indicates whether an option to restrict DDNS update requests to resource records marked as 'STATIC' is enabled or disabled.
	DdnsRestrictStatic *bool `json:"ddnsRestrictStatic,omitempty"`
	// Use flag for: ddns_restrict_static.
	UseDdnsRestrictStatic *bool `json:"useDdnsRestrictStatic,omitempty"`
	// Determines if DNS64 is enabled or not.
	Dns64Enabled *bool `json:"dns64Enabled,omitempty"`
	// The list of DNS64 synthesis groups associated with this DNS view.
	// +optional
	Dns64Groups []string `json:"dns64Groups"`
	// Use flag for: dns64_enabled, dns64_groups.
	UseDns64 *bool `json:"useDns64,omitempty"`
	// Determines if the DNS security extension is enabled or not.
	DnssecEnabled *bool `json:"dnssecEnabled,omitempty"`
	// Determines if the DNS security extension accepts expired signatures or not.
	DnssecExpiredSignaturesEnabled *bool `json:"dnssecExpiredSignaturesEnabled,omitempty"`
	// A list of zones for which the server does not perform DNSSEC validation.
	// +optional
	DnssecNegativeTrustAnchors []string `json:"dnssecNegativeTrustAnchors"`
	// The list of trusted keys for the DNS security extension.
	// +optional
	DnssecTrustedKeys []*DNSViewDnssecTrustedKey `json:"dnssecTrustedKeys"`
	// Determines if the DNS security validation is enabled or not.
	DnssecValidationEnabled *bool `json:"dnssecValidationEnabled,omitempty"`
	// Use flag for: dnssec_enabled, dnssec_expired_signatures_enabled, dnssec_validation_enabled, dnssec_trusted_keys.
	UseDnssec *bool `json:"useDnssec,omitempty"`
	// Determines if the fixed RRset order FQDN is enabled or not.
	EnableFixedRrsetOrderFqdns *bool `json:"enableFixedRrsetOrderFqdns,omitempty"`
	// The fixed RRset order FQDN list. If this field is non-empty, the appliance automatically sets enable_fixed_rrset_order_fqdns to true, unless the same request also sets it to false.
	// +optional
	FixedRrsetOrderFqdns []*DNSViewFixedRrsetOrderFqdn `json:"fixedRrsetOrderFqdns"`
	// Use flag for: fixed_rrset_order_fqdns, enable_fixed_rrset_order_fqdns.
	UseFixedRrsetOrderFqdns *bool `json:"useFixedRrsetOrderFqdns,omitempty"`
	// Determines if the 'match-recursive-only' option in a DNS view is enabled or not.
	EnableMatchRecursiveOnly *bool `json:"enableMatchRecursiveOnly,omitempty"`
	// Extensible attributes (arbitrary key/value metadata defined in Grid Manager). The WAPI wire format wraps each value as {"value": ...}; this map is the simplified string-valued CRD representation (the controller translates to/from the SDK's EA map[string]interface{} type).
	// +optional
	ExtAttrs map[string]string `json:"extAttrs"`
	// The type of AAAA filtering for this DNS view object.
	FilterAaaa *string `json:"filterAaaa,omitempty"`
	// Applies AAAA filtering to a named ACL, or to a list of IPv4/IPv6 addresses and networks from which queries are received. This field does not allow TSIG keys.
	// +optional
	FilterAaaaList []*DNSViewAddressAc `json:"filterAaaaList"`
	// Use flag for: filter_aaaa, filter_aaaa_list.
	UseFilterAaaa *bool `json:"useFilterAaaa,omitempty"`
	// Determines if this DNS view sends queries to forwarders only or not. When true, queries are sent to forwarders only, not to other internal or Internet root servers.
	ForwardOnly *bool `json:"forwardOnly,omitempty"`
	// The list of forwarders for the DNS view. A forwarder is a name server to which other name servers first send their off-site queries.
	// +optional
	Forwarders []string `json:"forwarders"`
	// Use flag for: forwarders, forward_only.
	UseForwarders *bool `json:"useForwarders,omitempty"`
	// The number of seconds to cache lame delegations or lame servers. Must be non-negative (0-2147483647); to inherit the grid default, set useLameTtl to false rather than passing a negative sentinel value.
	// +kubebuilder:validation:Minimum=0
	// +kubebuilder:validation:Maximum=2147483647
	LameTTL *uint32 `json:"lameTtl,omitempty"`
	// Use flag for: lame_ttl.
	UseLameTTL *bool `json:"useLameTtl,omitempty"`
	// A named ACL, or a list of IPv4/IPv6 addresses, networks, or TSIG keys of clients that are allowed or denied access to the DNS view.
	// +optional
	MatchClients []*DNSViewAddressAc `json:"matchClients"`
	// A named ACL, or a list of IPv4/IPv6 addresses, networks, or TSIG keys of destinations that are allowed or denied access to the DNS view.
	// +optional
	MatchDestinations []*DNSViewAddressAc `json:"matchDestinations"`
	// The maximum number of seconds to cache ordinary (positive) answers. Must be non-negative (0-2147483647); to inherit the grid default, set useMaxCacheTtl to false rather than passing a negative sentinel value.
	// +kubebuilder:validation:Minimum=0
	// +kubebuilder:validation:Maximum=2147483647
	MaxCacheTTL *uint32 `json:"maxCacheTtl,omitempty"`
	// Use flag for: max_cache_ttl.
	UseMaxCacheTTL *bool `json:"useMaxCacheTtl,omitempty"`
	// The maximum number of seconds to cache negative (NXDOMAIN) answers. Must be non-negative (0-2147483647); to inherit the grid default, set useMaxNcacheTtl to false rather than passing a negative sentinel value.
	// +kubebuilder:validation:Minimum=0
	// +kubebuilder:validation:Maximum=2147483647
	MaxNcacheTTL *uint32 `json:"maxNcacheTtl,omitempty"`
	// Use flag for: max_ncache_ttl.
	UseMaxNcacheTTL *bool `json:"useMaxNcacheTtl,omitempty"`
	// The number of seconds of delay before notify messages are sent to secondaries.
	NotifyDelay *uint32 `json:"notifyDelay,omitempty"`
	// The flag that indicates whether NXDOMAIN redirection queries are logged. The default value is false.
	NxdomainLogQuery *bool `json:"nxdomainLogQuery,omitempty"`
	// Determines if NXDOMAIN redirection in a DNS view is enabled or not.
	NxdomainRedirect *bool `json:"nxdomainRedirect,omitempty"`
	// The array with IPv4 addresses the appliance includes in the response it sends in place of an NXDOMAIN response.
	// +optional
	NxdomainRedirectAddresses []string `json:"nxdomainRedirectAddresses"`
	// The array with IPv6 addresses the appliance includes in the response it sends in place of an NXDOMAIN response.
	// +optional
	NxdomainRedirectAddressesV6 []string `json:"nxdomainRedirectAddressesV6"`
	// The Time To Live (TTL), in seconds, of the synthetic DNS responses resulting from NXDOMAIN redirection. Must be non-negative (0-2147483647); NIOS has no zone/grid-default sentinel for this field, so out-of-range values are rejected outright.
	// +kubebuilder:validation:Minimum=0
	// +kubebuilder:validation:Maximum=2147483647
	NxdomainRedirectTTL *uint32 `json:"nxdomainRedirectTtl,omitempty"`
	// The names of the Ruleset objects assigned at the grid level for NXDOMAIN redirection.
	// +optional
	NxdomainRulesets []string `json:"nxdomainRulesets"`
	// Use flag for: nxdomain_redirect, nxdomain_redirect_addresses, nxdomain_redirect_addresses_v6, nxdomain_redirect_ttl, nxdomain_log_query, nxdomain_rulesets.
	UseNxdomainRedirect *bool `json:"useNxdomainRedirect,omitempty"`
	// Determines if recursion is enabled or not.
	Recursion *bool `json:"recursion,omitempty"`
	// Use flag for: recursion.
	UseRecursion *bool `json:"useRecursion,omitempty"`
	// The response rate limiting settings for the DNS view.
	ResponseRateLimiting *DNSViewResponseRateLimiting `json:"responseRateLimiting,omitempty"`
	// Use flag for: response_rate_limiting.
	UseResponseRateLimiting *bool `json:"useResponseRateLimiting,omitempty"`
	// Enables the appliance to ignore RPZ-IP triggers with prefix lengths less than the specified minimum prefix length.
	RpzDropIPRuleEnabled *bool `json:"rpzDropIpRuleEnabled,omitempty"`
	// The minimum prefix length for IPv4 RPZ-IP triggers. The appliance ignores RPZ-IP triggers with prefix lengths less than this value.
	RpzDropIPRuleMinPrefixLengthIPv4 *uint32 `json:"rpzDropIpRuleMinPrefixLengthIpv4,omitempty"`
	// The minimum prefix length for IPv6 RPZ-IP triggers. The appliance ignores RPZ-IP triggers with prefix lengths less than this value.
	RpzDropIPRuleMinPrefixLengthIPv6 *uint32 `json:"rpzDropIpRuleMinPrefixLengthIpv6,omitempty"`
	// Use flag for: rpz_drop_ip_rule_enabled, rpz_drop_ip_rule_min_prefix_length_ipv4, rpz_drop_ip_rule_min_prefix_length_ipv6.
	UseRpzDropIPRule *bool `json:"useRpzDropIpRule,omitempty"`
	// The flag that indicates whether recursive RPZ lookups are enabled.
	RpzQnameWaitRecurse *bool `json:"rpzQnameWaitRecurse,omitempty"`
	// Use flag for: rpz_qname_wait_recurse.
	UseRpzQnameWaitRecurse *bool `json:"useRpzQnameWaitRecurse,omitempty"`
	// The scavenging settings for the DNS view.
	ScavengingSettings *DNSViewScavengingSettings `json:"scavengingSettings,omitempty"`
	// Use flag for: scavenging_settings.
	UseScavengingSettings *bool `json:"useScavengingSettings,omitempty"`
	// A sort list that determines the order of IP addresses in responses sent to DNS queries.
	// +optional
	Sortlist []*DNSViewSortlistEntry `json:"sortlist"`
	// Use flag for: sortlist.
	UseSortlist *bool `json:"useSortlist,omitempty"`
}

// DNSViewObservation holds the observed state of a DNSView.
// It mirrors every DNSViewParameters field plus response-only fields
// (full-mirror AtProvider) so users can compare forProvider to
// atProvider before switching to full management
// (managementPolicies: ["Observe"]).
type DNSViewObservation struct {
	// Server-assigned external identifier for this resource, set by Observe()
	// from the resource's external name. Used by import testing to confirm
	// the controller re-discovers the resource after a restart.
	// +optional
	ID string `json:"id,omitempty"` // atProvider
	// Name of the DNS view. Renaming an existing view changes its _ref (DNSView is in the _ref-unstable resource group — the controller re-reads _ref from the PUT response and updates the external-name annotation).
	Name *string `json:"name,omitempty"` // atProvider
	// Comment for the DNS view; maximum 64 characters.
	Comment *string `json:"comment,omitempty"` // atProvider
	// The name of the network view object associated with this DNS view.
	NetworkView *string `json:"networkView,omitempty"` // atProvider
	// Determines if the DNS view is disabled or not. When this is set to false, the DNS view is enabled.
	Disable *bool `json:"disable,omitempty"` // atProvider
	// The action to perform when a domain name matches the pattern defined in a rule specified by the blacklist ruleset. The default value is "REFUSE".
	BlacklistAction *string `json:"blacklistAction,omitempty"` // atProvider
	// The flag that indicates whether blacklist redirection queries are logged. The default value is false.
	BlacklistLogQuery *bool `json:"blacklistLogQuery,omitempty"` // atProvider
	// The array of IP addresses the appliance includes in the response it sends in place of a blacklisted IP address.
	// +optional
	BlacklistRedirectAddresses []string `json:"blacklistRedirectAddresses"` // atProvider
	// The Time To Live (TTL), in seconds, of the synthetic DNS responses resulting from blacklist redirection. Must be non-negative (0-2147483647); NIOS has no zone/grid-default sentinel for this field, so out-of-range values are rejected outright.
	BlacklistRedirectTTL *uint32 `json:"blacklistRedirectTtl,omitempty"` // atProvider
	// The name of the Ruleset object assigned at the Grid level for blacklist redirection.
	// +optional
	BlacklistRulesets []string `json:"blacklistRulesets"` // atProvider
	// Use flag for: blacklist_action, blacklist_log_query, blacklist_redirect_addresses, blacklist_redirect_ttl, blacklist_rulesets, enable_blacklist.
	UseBlacklist *bool `json:"useBlacklist,omitempty"` // atProvider
	// Determines if the blacklist in a DNS view is enabled or not.
	EnableBlacklist *bool `json:"enableBlacklist,omitempty"` // atProvider
	// The list of customized root name servers. Select and use Internet root name servers, or specify custom root name servers by providing a host name and IP address to which the appliance can send queries.
	// +optional
	CustomRootNameServers []DNSViewNameServer `json:"customRootNameServers"` // atProvider
	// Determines the type of root name servers.
	RootNameServerType *string `json:"rootNameServerType,omitempty"` // atProvider
	// Use flag for: custom_root_name_servers, root_name_server_type.
	UseRootNameServer *bool `json:"useRootNameServer,omitempty"` // atProvider
	// Defines whether the creation timestamp of a resource record is updated when a DDNS update happens, even if there is no change to the resource record.
	DdnsForceCreationTimestampUpdate *bool `json:"ddnsForceCreationTimestampUpdate,omitempty"` // atProvider
	// Use flag for: ddns_force_creation_timestamp_update.
	UseDdnsForceCreationTimestampUpdate *bool `json:"useDdnsForceCreationTimestampUpdate,omitempty"` // atProvider
	// The DDNS Principal cluster group name.
	DdnsPrincipalGroup *string `json:"ddnsPrincipalGroup,omitempty"` // atProvider
	// The flag that indicates whether the DDNS principal track is enabled or disabled.
	DdnsPrincipalTracking *bool `json:"ddnsPrincipalTracking,omitempty"` // atProvider
	// Use flag for: ddns_restrict_secure, ddns_principal_tracking, ddns_principal_group.
	UseDdnsPrincipalSecurity *bool `json:"useDdnsPrincipalSecurity,omitempty"` // atProvider
	// The flag that indicates whether an option to restrict DDNS update requests based on FQDN patterns is enabled or disabled.
	DdnsRestrictPatterns *bool `json:"ddnsRestrictPatterns,omitempty"` // atProvider
	// The unordered list of restriction patterns for the option to restrict DDNS updates based on FQDN patterns.
	// +optional
	DdnsRestrictPatternsList []string `json:"ddnsRestrictPatternsList"` // atProvider
	// Use flag for: ddns_restrict_patterns_list, ddns_restrict_patterns.
	UseDdnsPatternsRestriction *bool `json:"useDdnsPatternsRestriction,omitempty"` // atProvider
	// The flag that indicates whether an option to restrict DDNS update requests to protected resource records is enabled or disabled.
	DdnsRestrictProtected *bool `json:"ddnsRestrictProtected,omitempty"` // atProvider
	// Use flag for: ddns_restrict_protected.
	UseDdnsRestrictProtected *bool `json:"useDdnsRestrictProtected,omitempty"` // atProvider
	// The flag that indicates whether DDNS update requests for a principal other than the target resource record's principal are restricted.
	DdnsRestrictSecure *bool `json:"ddnsRestrictSecure,omitempty"` // atProvider
	// The flag that indicates whether an option to restrict DDNS update requests to resource records marked as 'STATIC' is enabled or disabled.
	DdnsRestrictStatic *bool `json:"ddnsRestrictStatic,omitempty"` // atProvider
	// Use flag for: ddns_restrict_static.
	UseDdnsRestrictStatic *bool `json:"useDdnsRestrictStatic,omitempty"` // atProvider
	// Determines if DNS64 is enabled or not.
	Dns64Enabled *bool `json:"dns64Enabled,omitempty"` // atProvider
	// The list of DNS64 synthesis groups associated with this DNS view.
	// +optional
	Dns64Groups []string `json:"dns64Groups"` // atProvider
	// Use flag for: dns64_enabled, dns64_groups.
	UseDns64 *bool `json:"useDns64,omitempty"` // atProvider
	// Determines if the DNS security extension is enabled or not.
	DnssecEnabled *bool `json:"dnssecEnabled,omitempty"` // atProvider
	// Determines if the DNS security extension accepts expired signatures or not.
	DnssecExpiredSignaturesEnabled *bool `json:"dnssecExpiredSignaturesEnabled,omitempty"` // atProvider
	// A list of zones for which the server does not perform DNSSEC validation.
	// +optional
	DnssecNegativeTrustAnchors []string `json:"dnssecNegativeTrustAnchors"` // atProvider
	// The list of trusted keys for the DNS security extension.
	// +optional
	DnssecTrustedKeys []*DNSViewDnssecTrustedKey `json:"dnssecTrustedKeys"` // atProvider
	// Determines if the DNS security validation is enabled or not.
	DnssecValidationEnabled *bool `json:"dnssecValidationEnabled,omitempty"` // atProvider
	// Use flag for: dnssec_enabled, dnssec_expired_signatures_enabled, dnssec_validation_enabled, dnssec_trusted_keys.
	UseDnssec *bool `json:"useDnssec,omitempty"` // atProvider
	// Determines if the fixed RRset order FQDN is enabled or not.
	EnableFixedRrsetOrderFqdns *bool `json:"enableFixedRrsetOrderFqdns,omitempty"` // atProvider
	// The fixed RRset order FQDN list. If this field is non-empty, the appliance automatically sets enable_fixed_rrset_order_fqdns to true, unless the same request also sets it to false.
	// +optional
	FixedRrsetOrderFqdns []*DNSViewFixedRrsetOrderFqdn `json:"fixedRrsetOrderFqdns"` // atProvider
	// Use flag for: fixed_rrset_order_fqdns, enable_fixed_rrset_order_fqdns.
	UseFixedRrsetOrderFqdns *bool `json:"useFixedRrsetOrderFqdns,omitempty"` // atProvider
	// Determines if the 'match-recursive-only' option in a DNS view is enabled or not.
	EnableMatchRecursiveOnly *bool `json:"enableMatchRecursiveOnly,omitempty"` // atProvider
	// Extensible attributes (arbitrary key/value metadata defined in Grid Manager). The WAPI wire format wraps each value as {"value": ...}; this map is the simplified string-valued CRD representation (the controller translates to/from the SDK's EA map[string]interface{} type).
	// +optional
	ExtAttrs map[string]string `json:"extAttrs"` // atProvider
	// The type of AAAA filtering for this DNS view object.
	FilterAaaa *string `json:"filterAaaa,omitempty"` // atProvider
	// Applies AAAA filtering to a named ACL, or to a list of IPv4/IPv6 addresses and networks from which queries are received. This field does not allow TSIG keys.
	// +optional
	FilterAaaaList []*DNSViewAddressAc `json:"filterAaaaList"` // atProvider
	// Use flag for: filter_aaaa, filter_aaaa_list.
	UseFilterAaaa *bool `json:"useFilterAaaa,omitempty"` // atProvider
	// Determines if this DNS view sends queries to forwarders only or not. When true, queries are sent to forwarders only, not to other internal or Internet root servers.
	ForwardOnly *bool `json:"forwardOnly,omitempty"` // atProvider
	// The list of forwarders for the DNS view. A forwarder is a name server to which other name servers first send their off-site queries.
	// +optional
	Forwarders []string `json:"forwarders"` // atProvider
	// Use flag for: forwarders, forward_only.
	UseForwarders *bool `json:"useForwarders,omitempty"` // atProvider
	// The number of seconds to cache lame delegations or lame servers. Must be non-negative (0-2147483647); to inherit the grid default, set useLameTtl to false rather than passing a negative sentinel value.
	LameTTL *uint32 `json:"lameTtl,omitempty"` // atProvider
	// Use flag for: lame_ttl.
	UseLameTTL *bool `json:"useLameTtl,omitempty"` // atProvider
	// A named ACL, or a list of IPv4/IPv6 addresses, networks, or TSIG keys of clients that are allowed or denied access to the DNS view.
	// +optional
	MatchClients []*DNSViewAddressAc `json:"matchClients"` // atProvider
	// A named ACL, or a list of IPv4/IPv6 addresses, networks, or TSIG keys of destinations that are allowed or denied access to the DNS view.
	// +optional
	MatchDestinations []*DNSViewAddressAc `json:"matchDestinations"` // atProvider
	// The maximum number of seconds to cache ordinary (positive) answers. Must be non-negative (0-2147483647); to inherit the grid default, set useMaxCacheTtl to false rather than passing a negative sentinel value.
	MaxCacheTTL *uint32 `json:"maxCacheTtl,omitempty"` // atProvider
	// Use flag for: max_cache_ttl.
	UseMaxCacheTTL *bool `json:"useMaxCacheTtl,omitempty"` // atProvider
	// The maximum number of seconds to cache negative (NXDOMAIN) answers. Must be non-negative (0-2147483647); to inherit the grid default, set useMaxNcacheTtl to false rather than passing a negative sentinel value.
	MaxNcacheTTL *uint32 `json:"maxNcacheTtl,omitempty"` // atProvider
	// Use flag for: max_ncache_ttl.
	UseMaxNcacheTTL *bool `json:"useMaxNcacheTtl,omitempty"` // atProvider
	// The number of seconds of delay before notify messages are sent to secondaries.
	NotifyDelay *uint32 `json:"notifyDelay,omitempty"` // atProvider
	// The flag that indicates whether NXDOMAIN redirection queries are logged. The default value is false.
	NxdomainLogQuery *bool `json:"nxdomainLogQuery,omitempty"` // atProvider
	// Determines if NXDOMAIN redirection in a DNS view is enabled or not.
	NxdomainRedirect *bool `json:"nxdomainRedirect,omitempty"` // atProvider
	// The array with IPv4 addresses the appliance includes in the response it sends in place of an NXDOMAIN response.
	// +optional
	NxdomainRedirectAddresses []string `json:"nxdomainRedirectAddresses"` // atProvider
	// The array with IPv6 addresses the appliance includes in the response it sends in place of an NXDOMAIN response.
	// +optional
	NxdomainRedirectAddressesV6 []string `json:"nxdomainRedirectAddressesV6"` // atProvider
	// The Time To Live (TTL), in seconds, of the synthetic DNS responses resulting from NXDOMAIN redirection. Must be non-negative (0-2147483647); NIOS has no zone/grid-default sentinel for this field, so out-of-range values are rejected outright.
	NxdomainRedirectTTL *uint32 `json:"nxdomainRedirectTtl,omitempty"` // atProvider
	// The names of the Ruleset objects assigned at the grid level for NXDOMAIN redirection.
	// +optional
	NxdomainRulesets []string `json:"nxdomainRulesets"` // atProvider
	// Use flag for: nxdomain_redirect, nxdomain_redirect_addresses, nxdomain_redirect_addresses_v6, nxdomain_redirect_ttl, nxdomain_log_query, nxdomain_rulesets.
	UseNxdomainRedirect *bool `json:"useNxdomainRedirect,omitempty"` // atProvider
	// Determines if recursion is enabled or not.
	Recursion *bool `json:"recursion,omitempty"` // atProvider
	// Use flag for: recursion.
	UseRecursion *bool `json:"useRecursion,omitempty"` // atProvider
	// The response rate limiting settings for the DNS view.
	ResponseRateLimiting *DNSViewResponseRateLimiting `json:"responseRateLimiting,omitempty"` // atProvider
	// Use flag for: response_rate_limiting.
	UseResponseRateLimiting *bool `json:"useResponseRateLimiting,omitempty"` // atProvider
	// Enables the appliance to ignore RPZ-IP triggers with prefix lengths less than the specified minimum prefix length.
	RpzDropIPRuleEnabled *bool `json:"rpzDropIpRuleEnabled,omitempty"` // atProvider
	// The minimum prefix length for IPv4 RPZ-IP triggers. The appliance ignores RPZ-IP triggers with prefix lengths less than this value.
	RpzDropIPRuleMinPrefixLengthIPv4 *uint32 `json:"rpzDropIpRuleMinPrefixLengthIpv4,omitempty"` // atProvider
	// The minimum prefix length for IPv6 RPZ-IP triggers. The appliance ignores RPZ-IP triggers with prefix lengths less than this value.
	RpzDropIPRuleMinPrefixLengthIPv6 *uint32 `json:"rpzDropIpRuleMinPrefixLengthIpv6,omitempty"` // atProvider
	// Use flag for: rpz_drop_ip_rule_enabled, rpz_drop_ip_rule_min_prefix_length_ipv4, rpz_drop_ip_rule_min_prefix_length_ipv6.
	UseRpzDropIPRule *bool `json:"useRpzDropIpRule,omitempty"` // atProvider
	// The flag that indicates whether recursive RPZ lookups are enabled.
	RpzQnameWaitRecurse *bool `json:"rpzQnameWaitRecurse,omitempty"` // atProvider
	// Use flag for: rpz_qname_wait_recurse.
	UseRpzQnameWaitRecurse *bool `json:"useRpzQnameWaitRecurse,omitempty"` // atProvider
	// The scavenging settings for the DNS view.
	ScavengingSettings *DNSViewScavengingSettings `json:"scavengingSettings,omitempty"` // atProvider
	// Use flag for: scavenging_settings.
	UseScavengingSettings *bool `json:"useScavengingSettings,omitempty"` // atProvider
	// A sort list that determines the order of IP addresses in responses sent to DNS queries.
	// +optional
	Sortlist []*DNSViewSortlistEntry `json:"sortlist"` // atProvider
	// Use flag for: sortlist.
	UseSortlist *bool `json:"useSortlist,omitempty"` // atProvider
	// Server-assigned opaque object reference (WAPI `_ref`). Mirrors the crossplane.io/external-name annotation for observability and uptest import verification. UNSTABLE — renaming the view changes this value; the controller re-reads _ref from the PUT response and updates the external-name annotation.
	Ref *string `json:"ref,omitempty"` // atProvider
	// The NIOS appliance always provides one default DNS view (name "default") plus two other well-known views ("External", "Internal"). You can rename the default view and change its settings, but its is_default flag never changes after creation. WAPI marks this field `supports=sr` (search + read only) — it is never a POST/PUT parameter, so it has no ForProvider representation; the CEL `self == oldSelf` rule is instead emitted on this AtProvider (status) mirror field (see FieldDef.Immutable doc, same pattern as ARecord's `zone` field).
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="isDefault is immutable after creation"
	IsDefault *bool `json:"isDefault,omitempty"` // atProvider
	// Cloud API related information for this object (cloud-managed views only).
	CloudInfo *DNSViewCloudInfo `json:"cloudInfo,omitempty"` // atProvider
}

// DNSViewSpec defines the desired state of DNSView.
type DNSViewSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`

	// ForProvider holds the user-supplied parameters for this DNSView.
	// +kubebuilder:validation:Required
	ForProvider DNSViewParameters `json:"forProvider"`
}

// DNSViewStatus defines the observed state of DNSView.
type DNSViewStatus struct {
	xpv1.ResourceStatus `json:",inline"`

	// AtProvider holds the observed values from the Infoblox NIOS WAPI.
	// +optional
	AtProvider DNSViewObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:storageversion
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,infobloxnios}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"

// DNSView is the Namespaced-scoped managed resource representing an Infoblox NIOS DNSView.
type DNSView struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   DNSViewSpec   `json:"spec"`
	Status DNSViewStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DNSViewList contains a list of DNSView.
type DNSViewList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DNSView `json:"items"`
}
