// Code generated by openapi2crd. DO NOT EDIT.

// Package rangepkg contains a standalone reference copy of the Parameters
// and Observation types for the Range managed resource. The
// cluster-scoped and namespaced variants (apis/cluster/range/,
// apis/namespaced/range/) generate self-contained copies of these same
// types rather than importing this package — see the openapi2crd/pkg/
// generator package doc comment for the rationale.
package rangepkg

import (
	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// RangeParameters are the configurable fields of a Range.
type RangeParameters struct {
	// First address in the DHCP range.
	// +kubebuilder:validation:Required
	StartAddr *string `json:"startAddr"`
	// Last address in the DHCP range.
	// +kubebuilder:validation:Required
	EndAddr *string `json:"endAddr"`
	// Name of the network view the range belongs to. Referenced by name (not _ref), since NetworkView's name is stable across most operations while its _ref changes on rename.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-infoblox-nios/apis/cluster/networkview/v1alpha1.NetworkView
	// +crossplane:generate:reference:extractor=github.com/crossplane-contrib/provider-infoblox-nios/apis/common/referencehelpers.ExtractField("spec.forProvider.name")
	NetworkView *string `json:"networkView,omitempty"`
	// +optional
	NetworkViewRef *xpv2.Reference `json:"networkViewRef,omitempty"`
	// +optional
	NetworkViewSelector *xpv2.Selector `json:"networkViewSelector,omitempty"`
	// CIDR of the parent network the range belongs to.
	Network *string `json:"network,omitempty"`
	// Name of the Range Template used to pre-populate this range's settings at creation. CreateNetworkRange accepts it; UpdateNetworkRange does not — the template link is create-only (applies its settings once, then the range is independent). Not part of the GetNetworkRange response, so the AtProvider mirror is populated from ForProvider (informational only) rather than from the observed object.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="template is immutable after creation"
	Template *string `json:"template,omitempty"`
	// Comment for the range; maximum 256 characters.
	Comment *string `json:"comment,omitempty"`
	// Extensible attributes (arbitrary key/value metadata defined in Grid Manager). The WAPI wire format wraps each value as {"value": ...}; this map is the simplified string-valued CRD representation (the controller translates to/from the SDK's EA map[string]interface{} type).
	// +optional
	// +kubebuilder:validation:XValidation:rule="self.all(k, k != 'Crossplane Internal ID')",message="the 'Crossplane Internal ID' extensible attribute is reserved for the provider's identity stamp and cannot be set in spec.forProvider.extAttrs"
	ExtAttrs map[string]string `json:"extAttrs"`
}

// RangeObservation holds the observed state of a Range.
// It mirrors every RangeParameters field plus response-only fields
// (full-mirror AtProvider) so users can compare forProvider to
// atProvider before switching to full management
// (managementPolicies: ["Observe"]).
type RangeObservation struct {
	// Server-assigned external identifier for this resource, set by Observe()
	// from the resource's external name. Used by import testing to confirm
	// the controller re-discovers the resource after a restart.
	// +optional
	ID string `json:"id,omitempty"` // atProvider
	// First address in the DHCP range.
	StartAddr *string `json:"startAddr,omitempty"` // atProvider
	// Last address in the DHCP range.
	EndAddr *string `json:"endAddr,omitempty"` // atProvider
	// Name of the network view the range belongs to. Referenced by name (not _ref), since NetworkView's name is stable across most operations while its _ref changes on rename.
	NetworkView *string `json:"networkView,omitempty"` // atProvider
	// CIDR of the parent network the range belongs to.
	Network *string `json:"network,omitempty"` // atProvider
	// Name of the Range Template used to pre-populate this range's settings at creation. CreateNetworkRange accepts it; UpdateNetworkRange does not — the template link is create-only (applies its settings once, then the range is independent). Not part of the GetNetworkRange response, so the AtProvider mirror is populated from ForProvider (informational only) rather than from the observed object.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="template is immutable after creation"
	Template *string `json:"template,omitempty"` // atProvider
	// Comment for the range; maximum 256 characters.
	Comment *string `json:"comment,omitempty"` // atProvider
	// Extensible attributes (arbitrary key/value metadata defined in Grid Manager). The WAPI wire format wraps each value as {"value": ...}; this map is the simplified string-valued CRD representation (the controller translates to/from the SDK's EA map[string]interface{} type).
	// +optional
	ExtAttrs map[string]string `json:"extAttrs"` // atProvider
	// Server-assigned opaque object reference (WAPI `_ref`). Mirrors the crossplane.io/external-name annotation for observability and uptest import verification.
	Ref *string `json:"ref,omitempty"` // atProvider
}
