// Package generator implements the openapi2crd generate subcommand. It
// renders catalog.ResourceDescriptor entries into Go source for:
//
//   - apis/common/<slug>/<slug>_types.go      — standalone reference copy of
//     the shared Parameters/Observation/nested types (documentation only —
//     see below for why the scope packages don't import it).
//   - apis/cluster/<slug>/v1alpha1/            — cluster-scoped MR type
//   - apis/namespaced/<slug>/v1alpha1/         — namespaced MR type
//
// Both scope packages generate SELF-CONTAINED types (Parameters, Observation,
// nested types are duplicated into each scope package rather than imported
// from apis/common/<slug>). This is intentional: controller-gen's deepcopy
// generator needs every managed-resource field type to live in the SAME
// package as the Spec/Status types it's embedded in, and mechanical
// convention checks scan each scope's <slug>_types.go file independently for
// the full-mirror AtProvider invariant. An import-based split would place
// those fields in a different file, causing false-positive check failures.
// apis/common/<slug>/<slug>_types.go is kept as a standalone, non-imported
// reference copy so there is a single documented source of truth for the
// field list even though the compiled scope packages don't reference it
// directly.
//
// Dual-scope spec embedding: cluster variants embed xpv1.ResourceSpec,
// namespaced variants embed xpv2.ManagedResourceSpec; both embed
// xpv1.ResourceStatus for status. CRD categories are
// {crossplane,managed,infobloxnios}. Immutable fields get a CEL
// `self == oldSelf` XValidation rule. JSON struct tags never carry
// omitempty on slice/map fields.
//
// Filenames: per this provider's Phase 3 plan, generated type files use the
// plain "<slug>_types.go" name (no "zz_" prefix) — e.g. "recorda_types.go" —
// so the resource is easy to spot in a directory listing; the mandatory
// "Code generated by openapi2crd. DO NOT EDIT." header is still the first
// line of every generated file, and register.go/doc.go carry the same
// header.
package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/crossplane-contrib/provider-infoblox-nios/tools/openapi2crd/pkg/catalog"
)

// Provider-specific constants.
const (
	providerName = "infobloxnios"
	apiVersion   = "v1alpha1"
	// modulePath is the Go module path declared in the provider root's
	// go.mod. Used to build fully-qualified
	// +crossplane:generate:reference:type marker values for future
	// cross-resource reference fields (none exist on ARecord today).
	modulePath = "github.com/crossplane-contrib/provider-infoblox-nios"
)

// FieldData is the template data for a single struct field.
type FieldData struct {
	// Name is the Go field name (PascalCase).
	Name string
	// GoType is the full Go type string (e.g. "*bool", "[]string").
	GoType string
	// JSONName is the JSON serialisation key.
	JSONName string
	// Description is a human-readable description (used as a Go doc comment).
	Description string
	// OmitEmpty controls whether the JSON tag includes omitempty.
	OmitEmpty bool
	// Required controls whether a +kubebuilder:validation:Required marker is
	// emitted (ForProvider fields only).
	Required bool
	// Immutable is true for ForProvider fields that require a CEL
	// XValidation rule.
	Immutable bool
	// Enum lists valid string values for this field.
	Enum []string
	// Reference holds cross-resource reference template data. Nil for
	// every ARecord field today.
	Reference *ReferenceData
}

// ReferenceData is the template data for one field's cross-resource
// reference. Not populated by any current resource — retained so the
// template already supports it when a referencing resource (e.g.
// CNAMERecord) is added.
type ReferenceData struct {
	// MarkerType is the fully-qualified Go type reference for the
	// +crossplane:generate:reference:type marker.
	MarkerType string
	// MarkerExtractor is the value for the
	// +crossplane:generate:reference:extractor marker. Empty omits the
	// marker, so angryjet falls back to reference.ExternalName().
	MarkerExtractor string
	// RefFieldName is the Go field name of the reference field.
	RefFieldName string
	// RefFieldJSONName is the camelCase JSON name for RefFieldName.
	RefFieldJSONName string
	// RefGoType is the Go type of the reference field.
	RefGoType string
	// RefFieldOmitEmpty is false when RefGoType is a slice, true otherwise.
	RefFieldOmitEmpty bool
	// SelectorFieldName is the Go field name of the selector field.
	SelectorFieldName string
	// SelectorGoType is "*xpv1.Reference"-style selector type.
	SelectorGoType string
	// SelectorFieldJSONName is the camelCase JSON name for SelectorFieldName.
	SelectorFieldJSONName string
	// ImmutableOnceSet mirrors catalog.ReferenceDescriptor.ImmutableOnceSet.
	ImmutableOnceSet bool
}

// NestedTypeData is the template data for a custom nested struct type.
type NestedTypeData struct {
	// TypeName is the Go type name (e.g. "ARecordDiscoveredData").
	TypeName string
	// Description is the type's doc comment.
	Description string
	// Fields are the fields of this struct.
	Fields []FieldData
}

// FieldSetData is the template input shared by both the standalone reference
// copy (apis/common/<slug>) and each scope's self-contained types file
// (apis/{cluster,namespaced}/<slug>/v1alpha1).
type FieldSetData struct {
	// Kind is the Kubernetes Kind (e.g. "ARecord").
	Kind string
	// Slug is the package name / directory slug (e.g. "recorda").
	Slug string
	// ForProvider contains fields sent in API create/update requests.
	ForProvider []FieldData
	// AtProvider contains fields populated from API responses. This is a
	// full mirror of ForProvider plus response-only fields.
	AtProvider []FieldData
	// NestedTypes contains custom struct type definitions referenced by
	// fields (e.g. ARecordDiscoveredData).
	NestedTypes []NestedTypeData
	// HasReferences is true if any ForProvider or nested-type field
	// carries a cross-resource Reference.
	HasReferences bool
	// ParameterValidations are resource-level (cross-field) CEL
	// XValidation rules rendered on the {{.Kind}}Parameters struct.
	ParameterValidations []catalog.ValidationRule
	// NeedsXPV1Import is true if any field (top-level or nested,
	// ForProvider or AtProvider) has a Go type that references the xpv1
	// package directly (implied by any cross-resource Reference). The
	// standalone common reference copy only imports xpv1 when this is
	// true — every scope's self-contained types file already imports
	// xpv1 unconditionally for xpv1.ResourceSpec/ResourceStatus.
	NeedsXPV1Import bool
}

// ScopeData is the template input for a scope-specific (cluster/namespaced)
// MR types file. It embeds FieldSetData so the scope template can render
// self-contained Parameters/Observation/nested types alongside the MR
// wrapper (Spec/Status/Kind/KindList).
type ScopeData struct {
	FieldSetData
	// Scope is "Cluster" or "Namespaced".
	Scope string
	// IsCluster is true for the cluster-scoped variant.
	IsCluster bool
	// Group is the full API group for this scope
	// (e.g. "recorda.infobloxnios.crossplane.io").
	Group string
}

// isOmitEmpty reports whether a Go type should use omitempty in its JSON
// struct tag, given whether the field is required.
//
// Slice ([]T) and map (map[K]V) fields MUST NOT use omitempty, in ANY
// struct (ForProvider, AtProvider, or nested types) — empty collections
// must round-trip as [] / {} rather than null so CEL `self == oldSelf`
// immutability rules never see a spurious null diff. Scalar/pointer fields
// use omitempty when the field is not required.
func isOmitEmpty(goType string, required bool) bool {
	if strings.HasPrefix(goType, "[]") || strings.HasPrefix(goType, "map[") {
		return false
	}
	return !required
}

// usesXPV1 reports whether a Go type string references the xpv1 package
// directly (e.g. "xpv1.Reference"). Used to decide whether the standalone
// common reference copy needs to import xpv1.
func usesXPV1(goType string) bool {
	return strings.Contains(goType, "xpv1.")
}

// lowerFirst lowercases the first rune of s, leaving the rest untouched.
func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

// buildReferenceData converts a catalog.ReferenceDescriptor into template
// data for the value field named goFieldName with Go type goType. Not
// exercised by any current resource (ARecord has no reference fields) but
// wired up so a future referencing resource needs no generator changes.
func buildReferenceData(ref *catalog.ReferenceDescriptor, goFieldName, goType string, isCluster bool) *ReferenceData {
	if ref == nil {
		return nil
	}

	scope := ref.TargetScope
	if scope == "" {
		scope = "namespaced"
		if isCluster {
			scope = "cluster"
		}
	}

	refType, selectorType := "xpv1.Reference", "xpv1.Selector"
	if !isCluster {
		refType, selectorType = "xpv1.NamespacedReference", "xpv1.NamespacedSelector"
	}

	refFieldName := goFieldName + "Ref"
	refGoType := "*" + refType
	if strings.HasPrefix(goType, "[]") {
		refFieldName = goFieldName + "Refs"
		refGoType = "[]" + refType
	}
	selectorFieldName := goFieldName + "Selector"

	return &ReferenceData{
		MarkerType:            fmt.Sprintf("%s/apis/%s/%s/%s.%s", modulePath, scope, ref.TargetSlug, apiVersion, ref.TargetKind),
		MarkerExtractor:       ref.Extractor,
		RefFieldName:          refFieldName,
		RefFieldJSONName:      lowerFirst(refFieldName),
		RefGoType:             refGoType,
		RefFieldOmitEmpty:     isOmitEmpty(refGoType, false),
		SelectorFieldName:     selectorFieldName,
		SelectorGoType:        "*" + selectorType,
		SelectorFieldJSONName: lowerFirst(selectorFieldName),
		ImmutableOnceSet:      ref.ImmutableOnceSet,
	}
}

// buildFieldData converts one catalog.FieldDef into ForProvider FieldData.
func buildFieldData(f catalog.FieldDef, isCluster bool) FieldData {
	return FieldData{
		Name:        f.Name,
		GoType:      f.GoType,
		JSONName:    f.JSONName,
		Description: f.Description,
		OmitEmpty:   isOmitEmpty(f.GoType, f.Required),
		Required:    f.Required,
		Immutable:   f.Immutable,
		Enum:        f.Enum,
		Reference:   buildReferenceData(f.Reference, f.Name, f.GoType, isCluster),
	}
}

// atProviderGoType returns the Go type to use for a field mirrored into the
// Observation struct. AtProvider fields are always optional (the value may
// not be observed yet), so non-pointer, non-collection ForProvider types
// (e.g. "string") are mirrored as pointers (e.g. "*string"). Types that are
// already pointers, slices, or maps are copied as-is.
func atProviderGoType(goType string) string {
	if strings.HasPrefix(goType, "*") || strings.HasPrefix(goType, "[]") || strings.HasPrefix(goType, "map[") {
		return goType
	}
	return "*" + goType
}

// buildAtProviderFieldData converts one catalog.FieldDef into AtProvider
// FieldData. AtProvider fields always use omitempty, except slice/map fields
// (which never carry omitempty).
func buildAtProviderFieldData(f catalog.FieldDef) FieldData {
	goType := atProviderGoType(f.GoType)
	return FieldData{
		Name:        f.Name,
		GoType:      goType,
		JSONName:    f.JSONName,
		Description: f.Description,
		OmitEmpty:   isOmitEmpty(goType, false),
	}
}

// BuildFieldSetData converts a catalog.ResourceDescriptor into the shared
// field-set template data consumed by both the standalone reference copy and
// every scope's self-contained types file. isCluster selects which scope's
// import path is used for any cross-resource reference; the standalone
// common reference copy always renders with isCluster=true purely for a
// single deterministic doc-only rendering (see Generate).
//
// Field-scope mapping:
//
//	FieldScopeRequest  -> ForProvider only
//	FieldScopeResponse -> AtProvider only
//	FieldScopeBoth     -> BOTH ForProvider and AtProvider
//
// All ForProvider fields also appear in AtProvider (full-mirror) to enable
// Observe-mode import — EXCEPT fields marked catalog.FieldDef.
// OmitFromObservation, which the API genuinely never echoes back (ARecord's
// removeAssociatedPtr is the only such field today). Those fields still
// appear in ForProvider normally; only the AtProvider mirror is skipped.
func BuildFieldSetData(rd catalog.ResourceDescriptor, isCluster bool) FieldSetData {
	var forProvider, atProvider []FieldData
	hasReferences := false
	needsXPV1 := false

	for _, f := range rd.Fields {
		switch f.Scope {
		case catalog.FieldScopeRequest, catalog.FieldScopeBoth:
			forProvider = append(forProvider, buildFieldData(f, isCluster))
			if !f.OmitFromObservation {
				atProvider = append(atProvider, buildAtProviderFieldData(f))
			}
		case catalog.FieldScopeResponse:
			if !f.OmitFromObservation {
				atProvider = append(atProvider, buildAtProviderFieldData(f))
			}
		}
		if f.Reference != nil {
			hasReferences = true
		}
		if usesXPV1(f.GoType) {
			needsXPV1 = true
		}
	}

	nestedTypes := make([]NestedTypeData, 0, len(rd.NestedTypes))
	for _, nt := range rd.NestedTypes {
		fields := make([]FieldData, 0, len(nt.Fields))
		for _, f := range nt.Fields {
			fields = append(fields, FieldData{
				Name:        f.Name,
				GoType:      f.GoType,
				JSONName:    f.JSONName,
				Description: f.Description,
				// No omitempty on slice/map, even in nested types.
				OmitEmpty: isOmitEmpty(f.GoType, false),
				Reference: buildReferenceData(f.Reference, f.Name, f.GoType, isCluster),
			})
			if f.Reference != nil {
				hasReferences = true
			}
			if usesXPV1(f.GoType) {
				needsXPV1 = true
			}
		}
		nestedTypes = append(nestedTypes, NestedTypeData{
			TypeName:    nt.TypeName,
			Description: nt.Description,
			Fields:      fields,
		})
	}

	return FieldSetData{
		Kind:                 rd.Kind,
		Slug:                 rd.Slug,
		ForProvider:          forProvider,
		AtProvider:           atProvider,
		NestedTypes:          nestedTypes,
		HasReferences:        hasReferences,
		ParameterValidations: rd.ParameterValidations,
		NeedsXPV1Import:      needsXPV1 || hasReferences,
	}
}

// BuildScopeData converts a catalog.ResourceDescriptor into template data for
// one scope's self-contained types file.
func BuildScopeData(rd catalog.ResourceDescriptor, isCluster bool) ScopeData {
	scope := "Namespaced"
	group := rd.NamespacedGroup
	if isCluster {
		scope = "Cluster"
		group = rd.ClusterGroup
	}
	return ScopeData{
		FieldSetData: BuildFieldSetData(rd, isCluster),
		Scope:        scope,
		IsCluster:    isCluster,
		Group:        group,
	}
}

// templateFuncs are helper functions available in all generator templates.
var templateFuncs = template.FuncMap{
	// jsonTag produces a complete struct tag literal: `json:"name"` or
	// `json:"name,omitempty"`.
	"jsonTag": func(name string, omitEmpty bool) string {
		if omitEmpty {
			return "`" + `json:"` + name + `,omitempty"` + "`"
		}
		return "`" + `json:"` + name + `"` + "`"
	},
	"inlineTag": func() string {
		return "`" + `json:",inline"` + "`"
	},
	// enumValues renders a kubebuilder Enum marker's value list.
	"enumValues": func(vals []string) string {
		return strings.Join(vals, ";")
	},
	// isSliceType reports whether a Go type string is a slice ("[]T").
	"isSliceType": func(goType string) bool {
		return strings.HasPrefix(goType, "[]")
	},
}

// fieldSetTemplate renders the Parameters/Observation/nested-type block
// shared by the standalone reference file and every scope's types file.
//
// Every field carries EITHER a +kubebuilder:validation:Required marker
// (Required fields) OR a +optional marker (everything else). This is
// mandatory for slice/map fields: they never carry omitempty on their JSON
// tags, so controller-gen has no other signal that the field is optional
// and defaults to marking it CRD-required.
const fieldSetTemplate = `{{- define "referenceMarker" -}}
{{if .Reference}}
	// +crossplane:generate:reference:type={{.Reference.MarkerType}}
{{- if .Reference.MarkerExtractor}}
	// +crossplane:generate:reference:extractor={{.Reference.MarkerExtractor}}
{{- end}}
{{- end}}
{{- end -}}
{{- define "referenceFields" -}}
{{if .Reference}}
	// +optional
	{{.Reference.RefFieldName}} {{.Reference.RefGoType}} {{jsonTag .Reference.RefFieldJSONName .Reference.RefFieldOmitEmpty}}
	// +optional
	{{.Reference.SelectorFieldName}} {{.Reference.SelectorGoType}} {{jsonTag .Reference.SelectorFieldJSONName true}}
{{- end}}
{{- end -}}
{{range .NestedTypes}}
// {{.TypeName}} {{.Description}}
type {{.TypeName}} struct {
{{range .Fields}}	// {{.Description}}
{{- if not .OmitEmpty}}
	// +optional
{{- end}}
{{- template "referenceMarker" .}}
	{{.Name}} {{.GoType}} {{jsonTag .JSONName .OmitEmpty}}
{{- template "referenceFields" .}}
{{end}}}
{{end}}
// {{.Kind}}Parameters are the configurable fields of a {{.Kind}}.
{{range .ParameterValidations}}// +kubebuilder:validation:XValidation:rule="{{.Rule}}",message="{{.Message}}"
{{end -}}
type {{.Kind}}Parameters struct {
{{range .ForProvider}}	// {{.Description}}
{{- if and .Immutable .Reference .Reference.ImmutableOnceSet}}
	// +optional
{{- if isSliceType .GoType}}
	// +kubebuilder:validation:XValidation:rule="size(oldSelf) == 0 || self == oldSelf",message="field is immutable once set"
{{- else}}
	// +kubebuilder:validation:XValidation:rule="oldSelf == '' || self == oldSelf",message="field is immutable once set"
{{- end}}
{{- else}}
{{- if .Required}}
	// +kubebuilder:validation:Required
{{- else if not .OmitEmpty}}
	// +optional
{{- end}}
{{- if .Immutable}}
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="{{.JSONName}} is immutable after creation"
{{- end}}
{{- end}}
{{- if .Enum}}
{{- if isSliceType .GoType}}
	// +kubebuilder:validation:items:Enum={{enumValues .Enum}}
{{- else}}
	// +kubebuilder:validation:Enum={{enumValues .Enum}}
{{- end}}
{{- end}}
{{- template "referenceMarker" .}}
	{{.Name}} {{.GoType}} {{jsonTag .JSONName .OmitEmpty}}
{{- template "referenceFields" .}}
{{end}}}

// {{.Kind}}Observation holds the observed state of a {{.Kind}}.
// It mirrors every {{.Kind}}Parameters field plus response-only fields
// (full-mirror AtProvider) so users can compare forProvider to
// atProvider before switching to full management
// (managementPolicies: ["Observe"]).
type {{.Kind}}Observation struct {
{{range .AtProvider}}	// {{.Description}}
{{- if not .OmitEmpty}}
	// +optional
{{- end}}
	{{.Name}} {{.GoType}} {{jsonTag .JSONName .OmitEmpty}} // atProvider
{{end}}}
`

// commonReferenceTemplate renders apis/common/<slug>/<slug>_types.go. This
// package is a standalone reference copy — it documents the shared field
// list but is not imported by the scope packages (see the package doc
// comment above for why).
const commonReferenceTemplate = `// Code generated by openapi2crd. DO NOT EDIT.

// Package {{.Slug}} contains a standalone reference copy of the Parameters
// and Observation types for the {{.Kind}} managed resource. The
// cluster-scoped and namespaced variants (apis/cluster/{{.Slug}}/,
// apis/namespaced/{{.Slug}}/) generate self-contained copies of these same
// types rather than importing this package — see the openapi2crd/pkg/
// generator package doc comment for the rationale.
package {{.Slug}}
{{- if .NeedsXPV1Import}}

import (
	xpv1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)
{{- end}}
` + fieldSetTemplate

// scopeTypesTemplate renders apis/{cluster,namespaced}/<slug>/v1alpha1/<slug>_types.go.
const scopeTypesTemplate = `// Code generated by openapi2crd. DO NOT EDIT.

// Package v1alpha1 contains the {{.Scope}}-scoped {{.Kind}} managed resource.
// API group: {{.Group}}
package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
{{- if not .IsCluster}}
	xpv2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
{{- end}}
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)
` + fieldSetTemplate + `
// {{.Kind}}Spec defines the desired state of {{.Kind}}.
type {{.Kind}}Spec struct {
{{- if .IsCluster}}
	xpv1.ResourceSpec {{inlineTag}}
{{- else}}
	xpv2.ManagedResourceSpec {{inlineTag}}
{{- end}}

	// ForProvider holds the user-supplied parameters for this {{.Kind}}.
	// +kubebuilder:validation:Required
	ForProvider {{.Kind}}Parameters {{jsonTag "forProvider" false}}
}

// {{.Kind}}Status defines the observed state of {{.Kind}}.
type {{.Kind}}Status struct {
	xpv1.ResourceStatus {{inlineTag}}

	// AtProvider holds the observed values from the Infoblox NIOS WAPI.
	// +optional
	AtProvider {{.Kind}}Observation {{jsonTag "atProvider" true}}
}

// +kubebuilder:object:root=true
// +kubebuilder:storageversion
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope={{.Scope}},categories={crossplane,managed,infobloxnios}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"

// {{.Kind}} is the {{.Scope}}-scoped managed resource representing an Infoblox NIOS {{.Kind}}.
type {{.Kind}} struct {
	metav1.TypeMeta   {{inlineTag}}
	metav1.ObjectMeta {{jsonTag "metadata" true}}

	Spec   {{.Kind}}Spec   {{jsonTag "spec" false}}
	Status {{.Kind}}Status {{jsonTag "status" true}}
}

// +kubebuilder:object:root=true

// {{.Kind}}List contains a list of {{.Kind}}.
type {{.Kind}}List struct {
	metav1.TypeMeta {{inlineTag}}
	metav1.ListMeta {{jsonTag "metadata" true}}
	Items           []{{.Kind}} {{jsonTag "items" false}}
}
`

// docTemplate renders doc.go for a scope package.
const docTemplate = `// Code generated by openapi2crd. DO NOT EDIT.

// Package v1alpha1 contains the {{.Scope}}-scoped {{.Kind}} managed resource
// for the {{.ProviderName}} provider.
// +kubebuilder:object:generate=true
// +groupName={{.Group}}
// +versionName={{.Version}}
package v1alpha1
`

// registerTemplate renders register.go for a scope package (combined
// group/version constants + SchemeBuilder + init registration).
const registerTemplate = `// Code generated by openapi2crd. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime/schema"
	"sigs.k8s.io/controller-runtime/pkg/scheme"
)

// Package type metadata.
const (
	// Group is the API group for this package.
	Group = "{{.Group}}"
	// Version is the API version for this package.
	Version = "{{.Version}}"
)

var (
	// SchemeGroupVersion is the group version used to register these objects.
	SchemeGroupVersion = schema.GroupVersion{Group: Group, Version: Version}

	// SchemeBuilder is used to add Go types to the GroupVersionKind scheme.
	SchemeBuilder = &scheme.Builder{GroupVersion: SchemeGroupVersion}
)

func init() {
	SchemeBuilder.Register(&{{.Kind}}{}, &{{.Kind}}List{})
}
`

// docRegisterData is the data shared by the doc.go and register.go templates.
type docRegisterData struct {
	ProviderName string
	Kind         string
	Scope        string
	Group        string
	Version      string
}

// RenderCommonReference renders apis/common/<slug>/<slug>_types.go source.
// The returned bytes are gofmt-formatted.
func RenderCommonReference(data FieldSetData) ([]byte, error) {
	return renderTemplate("common-reference", commonReferenceTemplate, data, data.Kind)
}

// RenderScopeTypes renders the <slug>_types.go source for one scope.
func RenderScopeTypes(data ScopeData) ([]byte, error) {
	return renderTemplate("scope-types", scopeTypesTemplate, data, data.Kind)
}

// renderDoc renders doc.go for one scope.
func renderDoc(data ScopeData) ([]byte, error) {
	drd := docRegisterData{
		ProviderName: providerName,
		Kind:         data.Kind,
		Scope:        data.Scope,
		Group:        data.Group,
		Version:      apiVersion,
	}
	return renderTemplate("doc", docTemplate, drd, data.Kind)
}

// renderRegister renders register.go for one scope.
func renderRegister(data ScopeData) ([]byte, error) {
	drd := docRegisterData{
		Kind:    data.Kind,
		Group:   data.Group,
		Version: apiVersion,
	}
	return renderTemplate("register", registerTemplate, drd, data.Kind)
}

// renderTemplate executes a named template and gofmt-formats the result.
func renderTemplate(name, tmpl string, data any, kind string) ([]byte, error) {
	t, err := template.New(name).Funcs(templateFuncs).Parse(tmpl)
	if err != nil {
		return nil, fmt.Errorf("parsing %s template: %w", name, err)
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("executing %s template for %s: %w", name, kind, err)
	}
	src, err := format.Source(buf.Bytes())
	if err != nil {
		// Return the unformatted source for debugging alongside the error.
		return buf.Bytes(), fmt.Errorf("formatting %s for %s (raw source returned): %w", name, kind, err)
	}
	return src, nil
}

// Generate produces all Go source files for rd in both cluster-scoped and
// namespaced scopes, plus the standalone common reference copy. outputDir is
// the provider root (e.g. "." when running from provider-infobloxnios/).
//
// Files written:
//   - apis/common/<slug>/<slug>_types.go
//   - apis/cluster/<slug>/v1alpha1/{doc.go,register.go,<slug>_types.go}
//   - apis/namespaced/<slug>/v1alpha1/{doc.go,register.go,<slug>_types.go}
func Generate(rd catalog.ResourceDescriptor, outputDir string) error {
	// Standalone common reference copy (isCluster=true is an arbitrary,
	// deterministic choice — the common copy documents the field list,
	// it does not need scope-specific import paths since ARecord has no
	// cross-resource reference fields).
	commonData := BuildFieldSetData(rd, true)
	commonSrc, err := RenderCommonReference(commonData)
	if err != nil {
		return fmt.Errorf("rendering common reference for %s: %w", rd.Kind, err)
	}
	commonDir := filepath.Join(outputDir, "apis", "common", rd.Slug)
	commonFile := filepath.Join(commonDir, rd.Slug+"_types.go")
	if err := writeFile(commonFile, commonSrc); err != nil {
		return err
	}

	// Scope-specific packages (self-contained).
	for _, isCluster := range []bool{true, false} {
		scope := "namespaced"
		if isCluster {
			scope = "cluster"
		}

		pkgDir := filepath.Join(outputDir, "apis", scope, rd.Slug, apiVersion)
		if err := os.MkdirAll(pkgDir, 0o750); err != nil {
			return fmt.Errorf("creating %s: %w", pkgDir, err)
		}

		data := BuildScopeData(rd, isCluster)

		docSrc, err := renderDoc(data)
		if err != nil {
			return fmt.Errorf("rendering doc.go for %s/%s: %w", scope, rd.Kind, err)
		}
		if err := writeFile(filepath.Join(pkgDir, "doc.go"), docSrc); err != nil {
			return err
		}

		regSrc, err := renderRegister(data)
		if err != nil {
			return fmt.Errorf("rendering register.go for %s/%s: %w", scope, rd.Kind, err)
		}
		if err := writeFile(filepath.Join(pkgDir, "register.go"), regSrc); err != nil {
			return err
		}

		typesSrc, err := RenderScopeTypes(data)
		if err != nil {
			return fmt.Errorf("rendering types for %s/%s: %w", scope, rd.Kind, err)
		}
		filename := rd.Slug + "_types.go"
		if err := writeFile(filepath.Join(pkgDir, filename), typesSrc); err != nil {
			return err
		}
	}

	return nil
}

// writeFile writes data to path, creating parent directories as needed.
func writeFile(path string, data []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		return fmt.Errorf("creating dir for %s: %w", path, err)
	}
	if err := os.WriteFile(path, data, 0o600); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}
	return nil
}
