// Package generator implements the openapi2crd generate subcommand. It
// renders catalog.ResourceDescriptor entries into Go source for:
//
//   - apis/common/<slug>/<slug>_types.go      — standalone reference copy of
//     the shared Parameters/Observation/nested types (documentation only —
//     see below for why the scope packages don't import it).
//   - apis/cluster/<slug>/v1alpha1/            — cluster-scoped MR type
//   - apis/namespaced/<slug>/v1alpha1/         — namespaced MR type
//
// Both scope packages generate SELF-CONTAINED types (Parameters, Observation,
// nested types are duplicated into each scope package rather than imported
// from apis/common/<slug>). This is intentional: controller-gen's deepcopy
// generator needs every managed-resource field type to live in the SAME
// package as the Spec/Status types it's embedded in, and mechanical
// convention checks scan each scope's <slug>_types.go file independently for
// the full-mirror AtProvider invariant. An import-based split would place
// those fields in a different file, causing false-positive check failures.
// apis/common/<slug>/<slug>_types.go is kept as a standalone, non-imported
// reference copy so there is a single documented source of truth for the
// field list even though the compiled scope packages don't reference it
// directly.
//
// Dual-scope spec embedding: cluster variants embed
// xpv2.ClusterManagedResourceSpec, namespaced variants embed
// xpv2.ManagedResourceSpec; both embed xpv2.ManagedResourceStatus for
// status (xpv2 is github.com/crossplane/crossplane/apis/v2/core/v2). CRD
// categories are {crossplane,managed,infobloxnios}. Immutable fields get a
// CEL `self == oldSelf` XValidation rule — except a ForProvider field that
// is BOTH Immutable AND cross-resource-reference-fed, which gets the
// empty-tolerant form (`self == oldSelf || oldSelf == ”`, or the slice
// equivalent) so the reference resolver's post-admission empty-to-populated
// first write is not rejected. JSON struct tags never carry omitempty on
// slice/map fields.
//
// Filenames: per this provider's Phase 3 plan, generated type files use the
// plain "<slug>_types.go" name (no "zz_" prefix) — e.g. "recorda_types.go" —
// so the resource is easy to spot in a directory listing; the mandatory
// "Code generated by openapi2crd. DO NOT EDIT." header is still the first
// line of every generated file, and register.go/doc.go carry the same
// header.
//
// apis/common/driftdetection/driftdetection_types.go is the one deliberate
// exception to the self-contained rule above: it is genuinely shared,
// provider-wide, resource-agnostic policy (spec.driftDetection), not a
// duplicated per-resource type, so every scope package's Spec imports it by
// pointer rather than duplicating it. It is rendered once per generate run
// (GenerateDriftDetectionPackage), not once per resource, and carries its
// own `+kubebuilder:object:generate=true` package marker so controller-gen
// generates its deepcopy methods.
package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/crossplane-contrib/provider-infoblox-nios/tools/openapi2crd/pkg/catalog"
)

// Provider-specific constants.
const (
	providerName = "infobloxnios"
	apiVersion   = "v1alpha1"
	// modulePath is the Go module path declared in the provider root's
	// go.mod. Used to build fully-qualified
	// +crossplane:generate:reference:type marker values for future
	// cross-resource reference fields (none exist on ARecord today).
	modulePath = "github.com/crossplane-contrib/provider-infoblox-nios"
)

// FieldData is the template data for a single struct field.
type FieldData struct {
	// Name is the Go field name (PascalCase).
	Name string
	// GoType is the full Go type string (e.g. "*bool", "[]string").
	GoType string
	// JSONName is the JSON serialisation key.
	JSONName string
	// Description is a human-readable description (used as a Go doc comment).
	Description string
	// OmitEmpty controls whether the JSON tag includes omitempty.
	OmitEmpty bool
	// Required controls whether a +kubebuilder:validation:Required marker is
	// emitted (ForProvider fields only).
	Required bool
	// Immutable is true for ForProvider fields that require a CEL
	// XValidation rule.
	Immutable bool
	// Enum lists valid string values for this field.
	Enum []string
	// HasMinimum controls whether a +kubebuilder:validation:Minimum
	// marker is emitted (ForProvider fields only).
	HasMinimum bool
	// Minimum is the marker value rendered when HasMinimum is true.
	Minimum int64
	// HasMaximum controls whether a +kubebuilder:validation:Maximum
	// marker is emitted (ForProvider fields only).
	HasMaximum bool
	// Maximum is the marker value rendered when HasMaximum is true.
	Maximum int64
	// Reference holds cross-resource reference template data. Nil for
	// every ARecord field today.
	Reference *ReferenceData
	// ExtraValidations are field-level kubebuilder XValidation rules
	// (catalog.FieldDef.ForProviderValidations). Rendered ONLY on
	// ForProvider fields — buildAtProviderFieldData never populates
	// this, so the same underlying catalog rule (e.g. the reserved
	// extAttrs identity key) never reaches the AtProvider mirror.
	ExtraValidations []catalog.ValidationRule
}

// ReferenceData is the template data for one field's cross-resource
// reference. Not populated by any current resource — retained so the
// template already supports it when a referencing resource (e.g.
// CNAMERecord) is added.
type ReferenceData struct {
	// MarkerType is the fully-qualified Go type reference for the
	// +crossplane:generate:reference:type marker.
	MarkerType string
	// MarkerExtractor is the value for the
	// +crossplane:generate:reference:extractor marker. Empty omits the
	// marker, so angryjet falls back to reference.ExternalName().
	MarkerExtractor string
	// RefFieldName is the Go field name of the reference field.
	RefFieldName string
	// RefFieldJSONName is the camelCase JSON name for RefFieldName.
	RefFieldJSONName string
	// RefGoType is the Go type of the reference field.
	RefGoType string
	// RefFieldOmitEmpty is false when RefGoType is a slice, true otherwise.
	RefFieldOmitEmpty bool
	// SelectorFieldName is the Go field name of the selector field.
	SelectorFieldName string
	// SelectorGoType is "*xpv2.Reference"-style selector type.
	SelectorGoType string
	// SelectorFieldJSONName is the camelCase JSON name for SelectorFieldName.
	SelectorFieldJSONName string
}

// NestedTypeData is the template data for a custom nested struct type.
type NestedTypeData struct {
	// TypeName is the Go type name (e.g. "ARecordDiscoveredData").
	TypeName string
	// Description is the type's doc comment.
	Description string
	// Fields are the fields of this struct.
	Fields []FieldData
}

// FieldSetData is the template input shared by both the standalone reference
// copy (apis/common/<slug>) and each scope's self-contained types file
// (apis/{cluster,namespaced}/<slug>/v1alpha1).
type FieldSetData struct {
	// Kind is the Kubernetes Kind (e.g. "ARecord").
	Kind string
	// Slug is the directory slug (e.g. "recorda"), used for file paths
	// and the apis/common/<slug> directory name.
	Slug string
	// PackageName is the Go package identifier for the standalone
	// apis/common/<slug> reference copy. Equal to Slug for almost every
	// resource, EXCEPT when Slug collides with a Go reserved keyword
	// (e.g. "range" — CreateNetworkRange's resource slug), in which case
	// it is Slug with a "pkg" suffix so `package {{.PackageName}}`
	// compiles. See safeGoPackageName.
	PackageName string
	// ForProvider contains fields sent in API create/update requests.
	ForProvider []FieldData
	// AtProvider contains fields populated from API responses. This is a
	// full mirror of ForProvider plus response-only fields.
	AtProvider []FieldData
	// NestedTypes contains custom struct type definitions referenced by
	// fields (e.g. ARecordDiscoveredData).
	NestedTypes []NestedTypeData
	// HasReferences is true if any ForProvider or nested-type field
	// carries a cross-resource Reference.
	HasReferences bool
	// ParameterValidations are resource-level (cross-field) CEL
	// XValidation rules rendered on the {{.Kind}}Parameters struct.
	ParameterValidations []catalog.ValidationRule
	// NeedsXPV2Import is true if any field (top-level or nested,
	// ForProvider or AtProvider) has a Go type that references the xpv2
	// package directly (implied by any cross-resource Reference). The
	// standalone common reference copy only imports xpv2 when this is
	// true — every scope's self-contained types file already imports
	// xpv2 unconditionally for xpv2.ClusterManagedResourceSpec/
	// ManagedResourceSpec/ManagedResourceStatus.
	NeedsXPV2Import bool
}

// ScopeData is the template input for a scope-specific (cluster/namespaced)
// MR types file. It embeds FieldSetData so the scope template can render
// self-contained Parameters/Observation/nested types alongside the MR
// wrapper (Spec/Status/Kind/KindList).
type ScopeData struct {
	FieldSetData
	// Scope is "Cluster" or "Namespaced".
	Scope string
	// IsCluster is true for the cluster-scoped variant.
	IsCluster bool
	// Group is the full API group for this scope
	// (e.g. "recorda.infobloxnios.crossplane.io").
	Group string
	// DriftDetectionImportPath is the fully-qualified import path of the
	// shared apis/common/driftdetection package, imported (unlike the
	// per-resource types) by every scope package's Spec.
	DriftDetectionImportPath string
}

// isOmitEmpty reports whether a Go type should use omitempty in its JSON
// struct tag, given whether the field is required.
//
// Slice ([]T) and map (map[K]V) fields MUST NOT use omitempty, in ANY
// struct (ForProvider, AtProvider, or nested types) — empty collections
// must round-trip as [] / {} rather than null so CEL `self == oldSelf`
// immutability rules never see a spurious null diff. Scalar/pointer fields
// use omitempty when the field is not required.
func isOmitEmpty(goType string, required bool) bool {
	if strings.HasPrefix(goType, "[]") || strings.HasPrefix(goType, "map[") {
		return false
	}
	return !required
}

// usesXPV2 reports whether a Go type string references the xpv2 package
// directly (e.g. "xpv2.Reference"). Used to decide whether the standalone
// common reference copy needs to import xpv2.
func usesXPV2(goType string) bool {
	return strings.Contains(goType, "xpv2.")
}

// lowerFirst lowercases the first rune of s, leaving the rest untouched.
func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

// safeGoPackageName returns a resource slug that is guaranteed to be a
// valid Go package identifier. It is used only for the standalone
// apis/common/<slug> reference copy's `package` declaration — every other
// use of a resource slug (directory names, CRD/API group names, JSON field
// names) is a string literal or filesystem path, not a Go identifier, and
// is unaffected by keyword collisions. A resource slug that happens to be
// a Go reserved word (e.g. "range", from CreateNetworkRange) would
// otherwise render an uncompilable `package range` — appending "pkg"
// disambiguates it while keeping the directory/CRD-facing slug untouched.
func safeGoPackageName(slug string) string {
	if token.IsKeyword(slug) {
		return slug + "pkg"
	}
	return slug
}

// buildReferenceData converts a catalog.ReferenceDescriptor into template
// data for the value field named goFieldName with Go type goType.
func buildReferenceData(ref *catalog.ReferenceDescriptor, goFieldName, goType string, isCluster bool) *ReferenceData {
	if ref == nil {
		return nil
	}

	scope := ref.TargetScope
	if scope == "" {
		scope = "namespaced"
		if isCluster {
			scope = "cluster"
		}
	}

	refType, selectorType := "xpv2.Reference", "xpv2.Selector"
	if !isCluster {
		refType, selectorType = "xpv2.NamespacedReference", "xpv2.NamespacedSelector"
	}

	refFieldName := goFieldName + "Ref"
	refGoType := "*" + refType
	if strings.HasPrefix(goType, "[]") {
		refFieldName = goFieldName + "Refs"
		refGoType = "[]" + refType
	}
	selectorFieldName := goFieldName + "Selector"

	return &ReferenceData{
		MarkerType:            fmt.Sprintf("%s/apis/%s/%s/%s.%s", modulePath, scope, ref.TargetSlug, apiVersion, ref.TargetKind),
		MarkerExtractor:       ref.Extractor,
		RefFieldName:          refFieldName,
		RefFieldJSONName:      lowerFirst(refFieldName),
		RefGoType:             refGoType,
		RefFieldOmitEmpty:     isOmitEmpty(refGoType, false),
		SelectorFieldName:     selectorFieldName,
		SelectorGoType:        "*" + selectorType,
		SelectorFieldJSONName: lowerFirst(selectorFieldName),
	}
}

// buildFieldData converts one catalog.FieldDef into ForProvider FieldData.
func buildFieldData(f catalog.FieldDef, isCluster bool) FieldData {
	fd := FieldData{
		Name:             f.Name,
		GoType:           f.GoType,
		JSONName:         f.JSONName,
		Description:      f.Description,
		OmitEmpty:        isOmitEmpty(f.GoType, f.Required),
		Required:         f.Required,
		Immutable:        f.Immutable,
		Enum:             f.Enum,
		Reference:        buildReferenceData(f.Reference, f.Name, f.GoType, isCluster),
		ExtraValidations: f.ForProviderValidations,
	}
	if f.Minimum != nil {
		fd.HasMinimum = true
		fd.Minimum = *f.Minimum
	}
	if f.Maximum != nil {
		fd.HasMaximum = true
		fd.Maximum = *f.Maximum
	}
	return fd
}

// atProviderGoType returns the Go type to use for a field mirrored into the
// Observation struct. AtProvider fields are always optional (the value may
// not be observed yet), so non-pointer, non-collection ForProvider types
// (e.g. "string") are mirrored as pointers (e.g. "*string"). Types that are
// already pointers, slices, or maps are copied as-is.
func atProviderGoType(goType string) string {
	if strings.HasPrefix(goType, "*") || strings.HasPrefix(goType, "[]") || strings.HasPrefix(goType, "map[") {
		return goType
	}
	return "*" + goType
}

// buildAtProviderFieldData converts one catalog.FieldDef into AtProvider
// FieldData. AtProvider fields always use omitempty, except slice/map fields
// (which never carry omitempty). Immutable is carried over so the
// Observation template can emit a CEL `self == oldSelf` rule on the mirror
// field — this is the ONLY place a response-only (FieldScopeResponse)
// immutable field can carry the rule at all, since it has no ForProvider
// counterpart to attach it to.
func buildAtProviderFieldData(f catalog.FieldDef) FieldData {
	goType := atProviderGoType(f.GoType)
	return FieldData{
		Name:        f.Name,
		GoType:      goType,
		JSONName:    f.JSONName,
		Description: f.Description,
		OmitEmpty:   isOmitEmpty(goType, false),
		Immutable:   f.Immutable,
	}
}

// BuildFieldSetData converts a catalog.ResourceDescriptor into the shared
// field-set template data consumed by both the standalone reference copy and
// every scope's self-contained types file. isCluster selects which scope's
// import path is used for any cross-resource reference; the standalone
// common reference copy always renders with isCluster=true purely for a
// single deterministic doc-only rendering (see Generate).
//
// Field-scope mapping:
//
//	FieldScopeRequest  -> ForProvider only
//	FieldScopeResponse -> AtProvider only
//	FieldScopeBoth     -> BOTH ForProvider and AtProvider
//
// All ForProvider fields also appear in AtProvider (full-mirror) to enable
// Observe-mode import — EXCEPT fields marked catalog.FieldDef.
// OmitFromObservation, which the API genuinely never echoes back (e.g.
// ARecord's and AAAARecord's removeAssociatedPtr, ExtensibleAttributeDef's
// descendantsAction, RangeTemplate's msServer). Those fields still appear
// in ForProvider normally; only the AtProvider mirror is skipped.
func BuildFieldSetData(rd catalog.ResourceDescriptor, isCluster bool) FieldSetData {
	var forProvider, atProvider []FieldData
	hasReferences := false
	needsXPV2 := false

	for _, f := range rd.Fields {
		switch f.Scope {
		case catalog.FieldScopeRequest, catalog.FieldScopeBoth:
			forProvider = append(forProvider, buildFieldData(f, isCluster))
			if !f.OmitFromObservation {
				atProvider = append(atProvider, buildAtProviderFieldData(f))
			}
		case catalog.FieldScopeResponse:
			if !f.OmitFromObservation {
				atProvider = append(atProvider, buildAtProviderFieldData(f))
			}
		}
		if f.Reference != nil {
			hasReferences = true
		}
		if usesXPV2(f.GoType) {
			needsXPV2 = true
		}
	}

	nestedTypes := make([]NestedTypeData, 0, len(rd.NestedTypes))
	for _, nt := range rd.NestedTypes {
		fields := make([]FieldData, 0, len(nt.Fields))
		for _, f := range nt.Fields {
			fields = append(fields, FieldData{
				Name:        f.Name,
				GoType:      f.GoType,
				JSONName:    f.JSONName,
				Description: f.Description,
				// No omitempty on slice/map, even in nested types. Nested
				// types can carry genuinely required fields (e.g. a list
				// entry's identifying value) — honor Required the same way
				// top-level fields do.
				OmitEmpty: isOmitEmpty(f.GoType, f.Required),
				Required:  f.Required,
				Reference: buildReferenceData(f.Reference, f.Name, f.GoType, isCluster),
			})
			if f.Reference != nil {
				hasReferences = true
			}
			if usesXPV2(f.GoType) {
				needsXPV2 = true
			}
		}
		nestedTypes = append(nestedTypes, NestedTypeData{
			TypeName:    nt.TypeName,
			Description: nt.Description,
			Fields:      fields,
		})
	}

	return FieldSetData{
		Kind:                 rd.Kind,
		Slug:                 rd.Slug,
		PackageName:          safeGoPackageName(rd.Slug),
		ForProvider:          forProvider,
		AtProvider:           atProvider,
		NestedTypes:          nestedTypes,
		HasReferences:        hasReferences,
		ParameterValidations: rd.ParameterValidations,
		NeedsXPV2Import:      needsXPV2 || hasReferences,
	}
}

// BuildScopeData converts a catalog.ResourceDescriptor into template data for
// one scope's self-contained types file.
func BuildScopeData(rd catalog.ResourceDescriptor, isCluster bool) ScopeData {
	scope := "Namespaced"
	group := rd.NamespacedGroup
	if isCluster {
		scope = "Cluster"
		group = rd.ClusterGroup
	}
	return ScopeData{
		FieldSetData:             BuildFieldSetData(rd, isCluster),
		Scope:                    scope,
		IsCluster:                isCluster,
		Group:                    group,
		DriftDetectionImportPath: modulePath + "/apis/common/driftdetection",
	}
}

// templateFuncs are helper functions available in all generator templates.
var templateFuncs = template.FuncMap{
	// jsonTag produces a complete struct tag literal: `json:"name"` or
	// `json:"name,omitempty"`.
	"jsonTag": func(name string, omitEmpty bool) string {
		if omitEmpty {
			return "`" + `json:"` + name + `,omitempty"` + "`"
		}
		return "`" + `json:"` + name + `"` + "`"
	},
	"inlineTag": func() string {
		return "`" + `json:",inline"` + "`"
	},
	// enumValues renders a kubebuilder Enum marker's value list.
	"enumValues": func(vals []string) string {
		return strings.Join(vals, ";")
	},
	// isSliceType reports whether a Go type string is a slice ("[]T").
	"isSliceType": func(goType string) bool {
		return strings.HasPrefix(goType, "[]")
	},
}

// fieldSetTemplate renders the Parameters/Observation/nested-type block
// shared by the standalone reference file and every scope's types file.
//
// Every field carries EITHER a +kubebuilder:validation:Required marker
// (Required fields) OR a +optional marker (everything else). This is
// mandatory for slice/map fields: they never carry omitempty on their JSON
// tags, so controller-gen has no other signal that the field is optional
// and defaults to marking it CRD-required.
const fieldSetTemplate = `{{- define "referenceMarker" -}}
{{if .Reference}}
	// +crossplane:generate:reference:type={{.Reference.MarkerType}}
{{- if .Reference.MarkerExtractor}}
	// +crossplane:generate:reference:extractor={{.Reference.MarkerExtractor}}
{{- end}}
{{- end}}
{{- end -}}
{{- define "referenceFields" -}}
{{if .Reference}}
	// +optional
	{{.Reference.RefFieldName}} {{.Reference.RefGoType}} {{jsonTag .Reference.RefFieldJSONName .Reference.RefFieldOmitEmpty}}
	// +optional
	{{.Reference.SelectorFieldName}} {{.Reference.SelectorGoType}} {{jsonTag .Reference.SelectorFieldJSONName true}}
{{- end}}
{{- end -}}
{{range .NestedTypes}}
// {{.TypeName}} {{.Description}}
type {{.TypeName}} struct {
{{range .Fields}}	// {{.Description}}
{{- if .Required}}
	// +kubebuilder:validation:Required
{{- else if not .OmitEmpty}}
	// +optional
{{- end}}
{{- template "referenceMarker" .}}
	{{.Name}} {{.GoType}} {{jsonTag .JSONName .OmitEmpty}}
{{- template "referenceFields" .}}
{{end}}}
{{end}}
// {{.Kind}}Parameters are the configurable fields of a {{.Kind}}.
{{range .ParameterValidations}}// +kubebuilder:validation:XValidation:rule="{{.Rule}}",message="{{.Message}}"
{{end -}}
type {{.Kind}}Parameters struct {
{{range .ForProvider}}	// {{.Description}}
{{- if .Required}}
	// +kubebuilder:validation:Required
{{- else if not .OmitEmpty}}
	// +optional
{{- end}}
{{- if .Immutable}}
{{- if .Reference}}
{{- if isSliceType .GoType}}
	// +kubebuilder:validation:XValidation:rule="self == oldSelf || size(oldSelf) == 0",message="{{.JSONName}} is immutable after creation"
{{- else}}
	// +kubebuilder:validation:XValidation:rule="self == oldSelf || oldSelf == ''",message="{{.JSONName}} is immutable after creation"
{{- end}}
{{- else}}
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="{{.JSONName}} is immutable after creation"
{{- end}}
{{- end}}
{{- if .Enum}}
{{- if isSliceType .GoType}}
	// +kubebuilder:validation:items:Enum={{enumValues .Enum}}
{{- else}}
	// +kubebuilder:validation:Enum={{enumValues .Enum}}
{{- end}}
{{- end}}
{{- if .HasMinimum}}
	// +kubebuilder:validation:Minimum={{.Minimum}}
{{- end}}
{{- if .HasMaximum}}
	// +kubebuilder:validation:Maximum={{.Maximum}}
{{- end}}
{{- range .ExtraValidations}}
	// +kubebuilder:validation:XValidation:rule="{{.Rule}}",message="{{.Message}}"
{{- end}}
{{- template "referenceMarker" .}}
	{{.Name}} {{.GoType}} {{jsonTag .JSONName .OmitEmpty}}
{{- template "referenceFields" .}}
{{end}}}

// {{.Kind}}Observation holds the observed state of a {{.Kind}}.
// It mirrors every {{.Kind}}Parameters field plus response-only fields
// (full-mirror AtProvider) so users can compare forProvider to
// atProvider before switching to full management
// (managementPolicies: ["Observe"]).
type {{.Kind}}Observation struct {
	// Server-assigned external identifier for this resource, set by Observe()
	// from the resource's external name. Used by import testing to confirm
	// the controller re-discovers the resource after a restart.
	// +optional
	ID string {{jsonTag "id" true}} // atProvider
{{range .AtProvider}}	// {{.Description}}
{{- if not .OmitEmpty}}
	// +optional
{{- end}}
{{- if .Immutable}}
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="{{.JSONName}} is immutable after creation"
{{- end}}
	{{.Name}} {{.GoType}} {{jsonTag .JSONName .OmitEmpty}} // atProvider
{{end}}}
`

// commonReferenceTemplate renders apis/common/<slug>/<slug>_types.go. This
// package is a standalone reference copy — it documents the shared field
// list but is not imported by the scope packages (see the package doc
// comment above for why).
const commonReferenceTemplate = `// Code generated by openapi2crd. DO NOT EDIT.

// Package {{.PackageName}} contains a standalone reference copy of the Parameters
// and Observation types for the {{.Kind}} managed resource. The
// cluster-scoped and namespaced variants (apis/cluster/{{.Slug}}/,
// apis/namespaced/{{.Slug}}/) generate self-contained copies of these same
// types rather than importing this package — see the openapi2crd/pkg/
// generator package doc comment for the rationale.
package {{.PackageName}}
{{- if .NeedsXPV2Import}}

import (
	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)
{{- end}}
` + fieldSetTemplate

// scopeTypesTemplate renders apis/{cluster,namespaced}/<slug>/v1alpha1/<slug>_types.go.
const scopeTypesTemplate = `// Code generated by openapi2crd. DO NOT EDIT.

// Package v1alpha1 contains the {{.Scope}}-scoped {{.Kind}} managed resource.
// API group: {{.Group}}
package v1alpha1

import (
	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	"{{.DriftDetectionImportPath}}"
)
` + fieldSetTemplate + `
// {{.Kind}}Spec defines the desired state of {{.Kind}}.
type {{.Kind}}Spec struct {
{{- if .IsCluster}}
	xpv2.ClusterManagedResourceSpec {{inlineTag}}
{{- else}}
	xpv2.ManagedResourceSpec {{inlineTag}}
{{- end}}

	// DriftDetection configures which forProvider fields are owned
	// outside Crossplane and how drift in those fields is detected and
	// corrected. Absent configuration means drift detection is enabled
	// with no ignored paths -- today's behaviour.
	// +optional
	DriftDetection *driftdetection.DriftDetection {{jsonTag "driftDetection" true}}

	// ForProvider holds the user-supplied parameters for this {{.Kind}}.
	// +kubebuilder:validation:Required
	ForProvider {{.Kind}}Parameters {{jsonTag "forProvider" false}}
}

// {{.Kind}}Status defines the observed state of {{.Kind}}.
type {{.Kind}}Status struct {
	xpv2.ManagedResourceStatus {{inlineTag}}

	// AtProvider holds the observed values from the Infoblox NIOS WAPI.
	// +optional
	AtProvider {{.Kind}}Observation {{jsonTag "atProvider" true}}
}

// +kubebuilder:object:root=true
// +kubebuilder:storageversion
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope={{.Scope}},categories={crossplane,managed,infobloxnios}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"

// {{.Kind}} is the {{.Scope}}-scoped managed resource representing an Infoblox NIOS {{.Kind}}.
type {{.Kind}} struct {
	metav1.TypeMeta   {{inlineTag}}
	metav1.ObjectMeta {{jsonTag "metadata" true}}

	Spec   {{.Kind}}Spec   {{jsonTag "spec" false}}
	Status {{.Kind}}Status {{jsonTag "status" true}}
}

// +kubebuilder:object:root=true

// {{.Kind}}List contains a list of {{.Kind}}.
type {{.Kind}}List struct {
	metav1.TypeMeta {{inlineTag}}
	metav1.ListMeta {{jsonTag "metadata" true}}
	Items           []{{.Kind}} {{jsonTag "items" false}}
}
`

// docTemplate renders doc.go for a scope package.
const docTemplate = `// Code generated by openapi2crd. DO NOT EDIT.

// Package v1alpha1 contains the {{.Scope}}-scoped {{.Kind}} managed resource
// for the {{.ProviderName}} provider.
// +kubebuilder:object:generate=true
// +groupName={{.Group}}
// +versionName={{.Version}}
package v1alpha1
`

// registerTemplate renders register.go for a scope package (combined
// group/version constants + SchemeBuilder + init registration).
const registerTemplate = `// Code generated by openapi2crd. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime/schema"
	"sigs.k8s.io/controller-runtime/pkg/scheme"
)

// Package type metadata.
const (
	// Group is the API group for this package.
	Group = "{{.Group}}"
	// Version is the API version for this package.
	Version = "{{.Version}}"
)

var (
	// SchemeGroupVersion is the group version used to register these objects.
	SchemeGroupVersion = schema.GroupVersion{Group: Group, Version: Version}

	// SchemeBuilder is used to add Go types to the GroupVersionKind scheme.
	SchemeBuilder = &scheme.Builder{GroupVersion: SchemeGroupVersion}
)

func init() {
	SchemeBuilder.Register(&{{.Kind}}{}, &{{.Kind}}List{})
}
`

// referenceHelpersTemplate renders
// apis/common/referencehelpers/zz_referencehelpers.go — a single, static,
// non-resource-specific file providing a generic cross-resource reference
// extractor. It lives in its own leaf package (NOT the root apis package)
// because the root apis package's zz_generated_register.go imports every
// apis/{cluster,namespaced}/<slug>/v1alpha1 package for scheme
// registration; if a scope package's zz_generated.resolvers.go imported
// the root apis package back for this helper, that would be an import
// cycle. apis/common/referencehelpers has no dependents of its own, so any
// scope package can safely import it. It is (re)written unconditionally on
// every `generate` run (see cmd's runGenerate) since its content never
// varies by resource.
const referenceHelpersTemplate = `// Code generated by openapi2crd. DO NOT EDIT.

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Package referencehelpers provides generic cross-resource reference
// extractors shared across every resource's generated types. It is
// intentionally a leaf package (imports nothing under apis/) so any
// apis/{cluster,namespaced}/<slug>/v1alpha1 package can import it without
// risk of an import cycle with the root apis package (which imports every
// scope package for scheme registration).
package referencehelpers

import (
	"github.com/crossplane/crossplane-runtime/v2/pkg/fieldpath"
	"github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	"github.com/crossplane/crossplane-runtime/v2/pkg/resource"
)

// ExtractField returns a cross-resource reference extractor that reads an
// arbitrary field off a referenced managed resource by JSON field path
// (e.g. "spec.forProvider.network"), using fieldpath.PaveObject. It is the
// native-provider equivalent of upjet's ExtractParamPath: unlike the
// crossplane-runtime default reference.ExternalName() extractor, which
// always reads the crossplane.io/external-name annotation, ExtractField
// lets a +crossplane:generate:reference:extractor= marker resolve to any
// field on the target's spec or status. Because it works generically via
// reflection, it needs no import of any resource-specific package, so it
// cannot introduce an import cycle between resources that reference each
// other.
//
// An empty return means "not yet resolvable" (missing field, wrong type,
// or the target hasn't populated the field yet) — crossplane-runtime
// reference resolution treats this as "referenced field was empty" and
// requeues.
func ExtractField(path string) reference.ExtractValueFn {
	return func(mg resource.Managed) string {
		paved, err := fieldpath.PaveObject(mg)
		if err != nil {
			return ""
		}
		v, err := paved.GetString(path)
		if err != nil {
			return ""
		}
		return v
	}
}
`

// driftDetectionTemplate renders
// apis/common/driftdetection/driftdetection_types.go — the shared drift
// detection configuration type embedded (by pointer) in every generated MR
// Spec, both scopes. Unlike the per-resource apis/common/<slug> packages
// (standalone reference copies, not imported — see the package doc comment
// above), this package IS imported directly by every scope package: it is
// genuinely shared, provider-wide, resource-agnostic infrastructure rather
// than a duplicated per-resource type. Rendered once per generate run, not
// once per resource.
const driftDetectionTemplate = `// Code generated by openapi2crd. DO NOT EDIT.

// Package driftdetection contains the shared drift detection configuration
// type embedded in every managed resource spec (spec.driftDetection). It
// declares which forProvider fields are owned outside Crossplane and how
// drift in those fields is detected and corrected.
// +kubebuilder:object:generate=true
package driftdetection

// Mode selects the drift detection behaviour for a managed resource.
// +kubebuilder:validation:Enum=enabled;warn;disabled
type Mode string

const (
	// ModeEnabled detects and corrects drift. This is the default.
	ModeEnabled Mode = "enabled"
	// ModeWarn detects drift and reports it on the DriftDetected condition,
	// but does not correct it.
	ModeWarn Mode = "warn"
	// ModeDisabled neither detects nor corrects drift.
	ModeDisabled Mode = "disabled"
)

// IgnoreRule declares fields whose value is owned by something other than
// Crossplane. Listed fields are seeded from spec on create, then neither
// compared nor written from spec: the value observed on the external
// resource is carried forward instead.
type IgnoreRule struct {
	// Paths to ignore, in Crossplane field path notation rooted at the
	// managed resource spec, for example forProvider.comment. This is the
	// grammar Composition patches use; JSON Pointer form
	// (/forProvider/comment) is also accepted. List indices and wildcards
	// are not supported -- ignore the whole list instead.
	// +optional
	Paths []string {{jsonTag "paths" false}}
}

// DriftDetection configures how drift between spec and the external
// resource is detected and corrected.
type DriftDetection struct {
	// Mode selects the drift detection behaviour.
	// +optional
	// +kubebuilder:default=enabled
	Mode Mode {{jsonTag "mode" true}}

	// Ignore declares fields owned outside Crossplane.
	// +optional
	Ignore []IgnoreRule {{jsonTag "ignore" false}}
}
`

// RenderDriftDetectionPackage renders
// apis/common/driftdetection/driftdetection_types.go source. The template
// takes no per-resource data — it is the same output for every provider
// run.
func RenderDriftDetectionPackage() ([]byte, error) {
	return renderTemplate("driftdetection", driftDetectionTemplate, nil, "DriftDetection")
}

// GenerateDriftDetectionPackage writes
// apis/common/driftdetection/driftdetection_types.go under outputDir (the
// provider root). Unlike Generate, this is called once per run — it is
// provider-wide, not per-resource — so callers invoke it unconditionally,
// even when a single --resource is being (re)generated, since every scope
// package's Spec imports this package.
func GenerateDriftDetectionPackage(outputDir string) error {
	src, err := RenderDriftDetectionPackage()
	if err != nil {
		return fmt.Errorf("rendering driftdetection package: %w", err)
	}
	dir := filepath.Join(outputDir, "apis", "common", "driftdetection")
	if err := os.MkdirAll(dir, 0o750); err != nil {
		return fmt.Errorf("creating %s: %w", dir, err)
	}
	return writeFile(filepath.Join(dir, "driftdetection_types.go"), src)
}

// RenderReferenceHelpers renders
// apis/common/referencehelpers/zz_referencehelpers.go source. The returned
// bytes are gofmt-formatted.
func RenderReferenceHelpers() ([]byte, error) {
	src, err := format.Source([]byte(referenceHelpersTemplate))
	if err != nil {
		return []byte(referenceHelpersTemplate), fmt.Errorf("formatting reference helpers (raw source returned): %w", err)
	}
	return src, nil
}

// GenerateReferenceHelpers writes
// apis/common/referencehelpers/zz_referencehelpers.go under outputDir (the
// provider root). It is independent of any single resource — call it once
// per `generate` invocation, not per resource.
func GenerateReferenceHelpers(outputDir string) error {
	src, err := RenderReferenceHelpers()
	if err != nil {
		return fmt.Errorf("rendering reference helpers: %w", err)
	}
	return writeFile(filepath.Join(outputDir, "apis", "common", "referencehelpers", "zz_referencehelpers.go"), src)
}

// docRegisterData is the data shared by the doc.go and register.go templates.
type docRegisterData struct {
	ProviderName string
	Kind         string
	Scope        string
	Group        string
	Version      string
}

// RenderCommonReference renders apis/common/<slug>/<slug>_types.go source.
// The returned bytes are gofmt-formatted.
func RenderCommonReference(data FieldSetData) ([]byte, error) {
	return renderTemplate("common-reference", commonReferenceTemplate, data, data.Kind)
}

// RenderScopeTypes renders the <slug>_types.go source for one scope.
func RenderScopeTypes(data ScopeData) ([]byte, error) {
	return renderTemplate("scope-types", scopeTypesTemplate, data, data.Kind)
}

// renderDoc renders doc.go for one scope.
func renderDoc(data ScopeData) ([]byte, error) {
	drd := docRegisterData{
		ProviderName: providerName,
		Kind:         data.Kind,
		Scope:        data.Scope,
		Group:        data.Group,
		Version:      apiVersion,
	}
	return renderTemplate("doc", docTemplate, drd, data.Kind)
}

// renderRegister renders register.go for one scope.
func renderRegister(data ScopeData) ([]byte, error) {
	drd := docRegisterData{
		Kind:    data.Kind,
		Group:   data.Group,
		Version: apiVersion,
	}
	return renderTemplate("register", registerTemplate, drd, data.Kind)
}

// renderTemplate executes a named template and gofmt-formats the result.
func renderTemplate(name, tmpl string, data any, kind string) ([]byte, error) {
	t, err := template.New(name).Funcs(templateFuncs).Parse(tmpl)
	if err != nil {
		return nil, fmt.Errorf("parsing %s template: %w", name, err)
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("executing %s template for %s: %w", name, kind, err)
	}
	src, err := format.Source(buf.Bytes())
	if err != nil {
		// Return the unformatted source for debugging alongside the error.
		return buf.Bytes(), fmt.Errorf("formatting %s for %s (raw source returned): %w", name, kind, err)
	}
	return src, nil
}

// Generate produces all Go source files for rd in both cluster-scoped and
// namespaced scopes, plus the standalone common reference copy. outputDir is
// the provider root (e.g. "." when running from provider-infobloxnios/).
//
// Files written:
//   - apis/common/<package-name>/<package-name>_types.go — <package-name> is
//     rd.Slug UNLESS rd.Slug is a Go reserved keyword (e.g. "range"), in
//     which case it is safeGoPackageName(rd.Slug) (e.g. "rangepkg"). The
//     directory name always matches the package name so `go run
//     ./... generate-methodsets` (jennifer's NewFilePath, which derives the
//     package clause it writes from the LAST PATH SEGMENT of the import
//     path, not the file's actual `package` declaration) never emits an
//     uncompilable `package range`.
//   - apis/cluster/<slug>/v1alpha1/{doc.go,register.go,<slug>_types.go}
//   - apis/namespaced/<slug>/v1alpha1/{doc.go,register.go,<slug>_types.go}
func Generate(rd catalog.ResourceDescriptor, outputDir string) error {
	// Standalone common reference copy (isCluster=true is an arbitrary,
	// deterministic choice — the common copy documents the field list,
	// it does not need scope-specific import paths since ARecord has no
	// cross-resource reference fields).
	commonData := BuildFieldSetData(rd, true)
	commonSrc, err := RenderCommonReference(commonData)
	if err != nil {
		return fmt.Errorf("rendering common reference for %s: %w", rd.Kind, err)
	}
	commonDir := filepath.Join(outputDir, "apis", "common", commonData.PackageName)
	commonFile := filepath.Join(commonDir, commonData.PackageName+"_types.go")
	if err := writeFile(commonFile, commonSrc); err != nil {
		return err
	}

	// Scope-specific packages (self-contained).
	for _, isCluster := range []bool{true, false} {
		scope := "namespaced"
		if isCluster {
			scope = "cluster"
		}

		pkgDir := filepath.Join(outputDir, "apis", scope, rd.Slug, apiVersion)
		if err := os.MkdirAll(pkgDir, 0o750); err != nil {
			return fmt.Errorf("creating %s: %w", pkgDir, err)
		}

		data := BuildScopeData(rd, isCluster)

		docSrc, err := renderDoc(data)
		if err != nil {
			return fmt.Errorf("rendering doc.go for %s/%s: %w", scope, rd.Kind, err)
		}
		if err := writeFile(filepath.Join(pkgDir, "doc.go"), docSrc); err != nil {
			return err
		}

		regSrc, err := renderRegister(data)
		if err != nil {
			return fmt.Errorf("rendering register.go for %s/%s: %w", scope, rd.Kind, err)
		}
		if err := writeFile(filepath.Join(pkgDir, "register.go"), regSrc); err != nil {
			return err
		}

		typesSrc, err := RenderScopeTypes(data)
		if err != nil {
			return fmt.Errorf("rendering types for %s/%s: %w", scope, rd.Kind, err)
		}
		filename := rd.Slug + "_types.go"
		if err := writeFile(filepath.Join(pkgDir, filename), typesSrc); err != nil {
			return err
		}
	}

	return nil
}

// writeFile writes data to path, creating parent directories as needed.
func writeFile(path string, data []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		return fmt.Errorf("creating dir for %s: %w", path, err)
	}
	if err := os.WriteFile(path, data, 0o600); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}
	return nil
}
