// Code generated by openapi2crd. DO NOT EDIT.

// Package v1alpha1 contains the Cluster-scoped DTCLBDN managed resource
// for the infobloxnios provider.
// +kubebuilder:object:generate=true
// +groupName=dtclbdn.infobloxnios.crossplane.io
// +versionName=v1alpha1
package v1alpha1
