// Code generated by openapi2crd. DO NOT EDIT.

// Package v1alpha1 contains the Cluster-scoped DTCLBDN managed resource.
// API group: dtclbdn.infobloxnios.crossplane.io
package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DTCLBDNPoolLink identifies one DTCPool member of a DTCLBDN along with its match priority ratio (mirrors the SDK's DtcPoolLink struct).
type DTCLBDNPoolLink struct {
	// DTCPool member of the LBDN, identified by its Crossplane external-name (the DTCPool's WAPI `_ref`).
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-infoblox-nios/apis/cluster/dtcpool/v1alpha1.DTCPool
	Pool *string `json:"pool,omitempty"`
	// +optional
	PoolRef *xpv1.Reference `json:"poolRef,omitempty"`
	// +optional
	PoolSelector *xpv1.Selector `json:"poolSelector,omitempty"`
	// The match priority weight of the pool within the LBDN.
	Ratio *uint32 `json:"ratio,omitempty"`
}

// DTCLBDNHealth carries the aggregate health status of a DTCLBDN (mirrors the SDK's DtcHealth struct).
type DTCLBDNHealth struct {
	// The availability color status.
	Availability *string `json:"availability,omitempty"`
	// The textual description of the object's status.
	Description *string `json:"description,omitempty"`
	// The enabled state of the object.
	EnabledState *string `json:"enabledState,omitempty"`
}

// DTCLBDNParameters are the configurable fields of a DTCLBDN.
type DTCLBDNParameters struct {
	// DTC LBDN (Load Balanced Domain Name) display name (not DNS-related). Mutable — changes the WAPI `_ref`.
	// +kubebuilder:validation:Required
	Name *string `json:"name"`
	// Load balancing method used to select a pool from those listed in pools.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Enum=ROUND_ROBIN;RATIO;TOPOLOGY;GLOBAL_AVAILABILITY
	LBMethod *string `json:"lbMethod"`
	// FQDN wildcard patterns matched against incoming queries. At least one pattern is required for the LBDN to answer any query.
	// +kubebuilder:validation:Required
	Patterns []string `json:"patterns"`
	// Pools associated with this LBDN, each with a per-pool match priority ratio.
	// +optional
	Pools []DTCLBDNPoolLink `json:"pools"`
	// Authoritative zones the LBDN's patterns are matched against, identified by each ZoneAuth's WAPI `_ref`. Live-verified (ADR-IN-0004): WAPI requires bare _ref strings, not objects. Linked zones must have a Grid primary configured.
	// +optional
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-infoblox-nios/apis/cluster/zoneauth/v1alpha1.ZoneAuth
	AuthZones []string `json:"authZones"`
	// +optional
	AuthZonesRefs []xpv1.Reference `json:"authZonesRefs"`
	// +optional
	AuthZonesSelector *xpv1.Selector `json:"authZonesSelector,omitempty"`
	// Resource record types the LBDN answers with.
	// +optional
	// +kubebuilder:validation:items:Enum=A;AAAA;CNAME;NAPTR;SRV
	Types []string `json:"types"`
	// Match priority among overlapping LBDNs (lower ordinal wins).
	Priority *uint32 `json:"priority,omitempty"`
	// Seconds to cache a client-specific LBDN response. Zero disables caching.
	Persistence *uint32 `json:"persistence,omitempty"`
	// Topology ruleset name used when lbMethod=TOPOLOGY.
	Topology *string `json:"topology,omitempty"`
	// Time-To-Live for the DTC LBDN response, in seconds.
	TTL *uint32 `json:"ttl,omitempty"`
	// Use flag for ttl.
	UseTTL *bool `json:"useTtl,omitempty"`
	// Comment for the DTC LBDN; maximum 256 characters.
	Comment *string `json:"comment,omitempty"`
	// Whether the DTC LBDN is disabled.
	Disable *bool `json:"disable,omitempty"`
	// Extensible attributes (arbitrary key/value metadata defined in Grid Manager). The WAPI wire format wraps each value as {"value": ...}; this map is the simplified string-valued CRD representation (the controller translates to/from the SDK's EA map[string]interface{} type).
	// +optional
	ExtAttrs map[string]string `json:"extattrs"`
}

// DTCLBDNObservation holds the observed state of a DTCLBDN.
// It mirrors every DTCLBDNParameters field plus response-only fields
// (full-mirror AtProvider) so users can compare forProvider to
// atProvider before switching to full management
// (managementPolicies: ["Observe"]).
type DTCLBDNObservation struct {
	// Server-assigned external identifier for this resource, set by Observe()
	// from the resource's external name. Used by import testing to confirm
	// the controller re-discovers the resource after a restart.
	// +optional
	ID string `json:"id,omitempty"` // atProvider
	// DTC LBDN (Load Balanced Domain Name) display name (not DNS-related). Mutable — changes the WAPI `_ref`.
	Name *string `json:"name,omitempty"` // atProvider
	// Load balancing method used to select a pool from those listed in pools.
	LBMethod *string `json:"lbMethod,omitempty"` // atProvider
	// FQDN wildcard patterns matched against incoming queries. At least one pattern is required for the LBDN to answer any query.
	// +optional
	Patterns []string `json:"patterns"` // atProvider
	// Pools associated with this LBDN, each with a per-pool match priority ratio.
	// +optional
	Pools []DTCLBDNPoolLink `json:"pools"` // atProvider
	// Authoritative zones the LBDN's patterns are matched against, identified by each ZoneAuth's WAPI `_ref`. Live-verified (ADR-IN-0004): WAPI requires bare _ref strings, not objects. Linked zones must have a Grid primary configured.
	// +optional
	AuthZones []string `json:"authZones"` // atProvider
	// Resource record types the LBDN answers with.
	// +optional
	Types []string `json:"types"` // atProvider
	// Match priority among overlapping LBDNs (lower ordinal wins).
	Priority *uint32 `json:"priority,omitempty"` // atProvider
	// Seconds to cache a client-specific LBDN response. Zero disables caching.
	Persistence *uint32 `json:"persistence,omitempty"` // atProvider
	// Topology ruleset name used when lbMethod=TOPOLOGY.
	Topology *string `json:"topology,omitempty"` // atProvider
	// Time-To-Live for the DTC LBDN response, in seconds.
	TTL *uint32 `json:"ttl,omitempty"` // atProvider
	// Use flag for ttl.
	UseTTL *bool `json:"useTtl,omitempty"` // atProvider
	// Comment for the DTC LBDN; maximum 256 characters.
	Comment *string `json:"comment,omitempty"` // atProvider
	// Whether the DTC LBDN is disabled.
	Disable *bool `json:"disable,omitempty"` // atProvider
	// Extensible attributes (arbitrary key/value metadata defined in Grid Manager). The WAPI wire format wraps each value as {"value": ...}; this map is the simplified string-valued CRD representation (the controller translates to/from the SDK's EA map[string]interface{} type).
	// +optional
	ExtAttrs map[string]string `json:"extattrs"` // atProvider
	// Server-assigned opaque object reference (WAPI `_ref`). Mirrors the crossplane.io/external-name annotation for observability and uptest import verification.
	Ref *string `json:"ref,omitempty"` // atProvider
	// Aggregate health status of the LBDN.
	Health *DTCLBDNHealth `json:"health,omitempty"` // atProvider
}

// DTCLBDNSpec defines the desired state of DTCLBDN.
type DTCLBDNSpec struct {
	xpv1.ResourceSpec `json:",inline"`

	// ForProvider holds the user-supplied parameters for this DTCLBDN.
	// +kubebuilder:validation:Required
	ForProvider DTCLBDNParameters `json:"forProvider"`
}

// DTCLBDNStatus defines the observed state of DTCLBDN.
type DTCLBDNStatus struct {
	xpv1.ResourceStatus `json:",inline"`

	// AtProvider holds the observed values from the Infoblox NIOS WAPI.
	// +optional
	AtProvider DTCLBDNObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:storageversion
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,infobloxnios}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"

// DTCLBDN is the Cluster-scoped managed resource representing an Infoblox NIOS DTCLBDN.
type DTCLBDN struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   DTCLBDNSpec   `json:"spec"`
	Status DTCLBDNStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DTCLBDNList contains a list of DTCLBDN.
type DTCLBDNList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DTCLBDN `json:"items"`
}
