//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostRecord) DeepCopyInto(out *HostRecord) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostRecord.
func (in *HostRecord) DeepCopy() *HostRecord {
	if in == nil {
		return nil
	}
	out := new(HostRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HostRecord) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostRecordIpv4Addr) DeepCopyInto(out *HostRecordIpv4Addr) {
	*out = *in
	if in.MAC != nil {
		in, out := &in.MAC, &out.MAC
		*out = new(string)
		**out = **in
	}
	if in.ConfigureForDHCP != nil {
		in, out := &in.ConfigureForDHCP, &out.ConfigureForDHCP
		*out = new(bool)
		**out = **in
	}
	if in.NextServer != nil {
		in, out := &in.NextServer, &out.NextServer
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostRecordIpv4Addr.
func (in *HostRecordIpv4Addr) DeepCopy() *HostRecordIpv4Addr {
	if in == nil {
		return nil
	}
	out := new(HostRecordIpv4Addr)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostRecordIpv6Addr) DeepCopyInto(out *HostRecordIpv6Addr) {
	*out = *in
	if in.Duid != nil {
		in, out := &in.Duid, &out.Duid
		*out = new(string)
		**out = **in
	}
	if in.ConfigureForDHCP != nil {
		in, out := &in.ConfigureForDHCP, &out.ConfigureForDHCP
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostRecordIpv6Addr.
func (in *HostRecordIpv6Addr) DeepCopy() *HostRecordIpv6Addr {
	if in == nil {
		return nil
	}
	out := new(HostRecordIpv6Addr)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostRecordList) DeepCopyInto(out *HostRecordList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HostRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostRecordList.
func (in *HostRecordList) DeepCopy() *HostRecordList {
	if in == nil {
		return nil
	}
	out := new(HostRecordList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HostRecordList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostRecordObservation) DeepCopyInto(out *HostRecordObservation) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Ipv4Addrs != nil {
		in, out := &in.Ipv4Addrs, &out.Ipv4Addrs
		*out = make([]HostRecordIpv4Addr, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Ipv6Addrs != nil {
		in, out := &in.Ipv6Addrs, &out.Ipv6Addrs
		*out = make([]HostRecordIpv6Addr, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NetworkView != nil {
		in, out := &in.NetworkView, &out.NetworkView
		*out = new(string)
		**out = **in
	}
	if in.View != nil {
		in, out := &in.View, &out.View
		*out = new(string)
		**out = **in
	}
	if in.Aliases != nil {
		in, out := &in.Aliases, &out.Aliases
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ConfigureForDNS != nil {
		in, out := &in.ConfigureForDNS, &out.ConfigureForDNS
		*out = new(bool)
		**out = **in
	}
	if in.Comment != nil {
		in, out := &in.Comment, &out.Comment
		*out = new(string)
		**out = **in
	}
	if in.Disable != nil {
		in, out := &in.Disable, &out.Disable
		*out = new(bool)
		**out = **in
	}
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(uint32)
		**out = **in
	}
	if in.UseTTL != nil {
		in, out := &in.UseTTL, &out.UseTTL
		*out = new(bool)
		**out = **in
	}
	if in.ExtAttrs != nil {
		in, out := &in.ExtAttrs, &out.ExtAttrs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Ipv4Cidr != nil {
		in, out := &in.Ipv4Cidr, &out.Ipv4Cidr
		*out = new(string)
		**out = **in
	}
	if in.Ipv6Cidr != nil {
		in, out := &in.Ipv6Cidr, &out.Ipv6Cidr
		*out = new(string)
		**out = **in
	}
	if in.FilterParams != nil {
		in, out := &in.FilterParams, &out.FilterParams
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.IpAddressType != nil {
		in, out := &in.IpAddressType, &out.IpAddressType
		*out = new(string)
		**out = **in
	}
	if in.Ref != nil {
		in, out := &in.Ref, &out.Ref
		*out = new(string)
		**out = **in
	}
	if in.Zone != nil {
		in, out := &in.Zone, &out.Zone
		*out = new(string)
		**out = **in
	}
	if in.DNSName != nil {
		in, out := &in.DNSName, &out.DNSName
		*out = new(string)
		**out = **in
	}
	if in.DNSAliases != nil {
		in, out := &in.DNSAliases, &out.DNSAliases
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostRecordObservation.
func (in *HostRecordObservation) DeepCopy() *HostRecordObservation {
	if in == nil {
		return nil
	}
	out := new(HostRecordObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostRecordParameters) DeepCopyInto(out *HostRecordParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Ipv4Addrs != nil {
		in, out := &in.Ipv4Addrs, &out.Ipv4Addrs
		*out = make([]HostRecordIpv4Addr, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Ipv6Addrs != nil {
		in, out := &in.Ipv6Addrs, &out.Ipv6Addrs
		*out = make([]HostRecordIpv6Addr, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NetworkView != nil {
		in, out := &in.NetworkView, &out.NetworkView
		*out = new(string)
		**out = **in
	}
	if in.NetworkViewRef != nil {
		in, out := &in.NetworkViewRef, &out.NetworkViewRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.NetworkViewSelector != nil {
		in, out := &in.NetworkViewSelector, &out.NetworkViewSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.View != nil {
		in, out := &in.View, &out.View
		*out = new(string)
		**out = **in
	}
	if in.Aliases != nil {
		in, out := &in.Aliases, &out.Aliases
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ConfigureForDNS != nil {
		in, out := &in.ConfigureForDNS, &out.ConfigureForDNS
		*out = new(bool)
		**out = **in
	}
	if in.Comment != nil {
		in, out := &in.Comment, &out.Comment
		*out = new(string)
		**out = **in
	}
	if in.Disable != nil {
		in, out := &in.Disable, &out.Disable
		*out = new(bool)
		**out = **in
	}
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(uint32)
		**out = **in
	}
	if in.UseTTL != nil {
		in, out := &in.UseTTL, &out.UseTTL
		*out = new(bool)
		**out = **in
	}
	if in.ExtAttrs != nil {
		in, out := &in.ExtAttrs, &out.ExtAttrs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Ipv4Cidr != nil {
		in, out := &in.Ipv4Cidr, &out.Ipv4Cidr
		*out = new(string)
		**out = **in
	}
	if in.Ipv6Cidr != nil {
		in, out := &in.Ipv6Cidr, &out.Ipv6Cidr
		*out = new(string)
		**out = **in
	}
	if in.FilterParams != nil {
		in, out := &in.FilterParams, &out.FilterParams
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.IpAddressType != nil {
		in, out := &in.IpAddressType, &out.IpAddressType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostRecordParameters.
func (in *HostRecordParameters) DeepCopy() *HostRecordParameters {
	if in == nil {
		return nil
	}
	out := new(HostRecordParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostRecordSpec) DeepCopyInto(out *HostRecordSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostRecordSpec.
func (in *HostRecordSpec) DeepCopy() *HostRecordSpec {
	if in == nil {
		return nil
	}
	out := new(HostRecordSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostRecordStatus) DeepCopyInto(out *HostRecordStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostRecordStatus.
func (in *HostRecordStatus) DeepCopy() *HostRecordStatus {
	if in == nil {
		return nil
	}
	out := new(HostRecordStatus)
	in.DeepCopyInto(out)
	return out
}
