// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"

// GetCondition of this NetworkView.
func (mg *NetworkView) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this NetworkView.
func (mg *NetworkView) GetDeletionPolicy() xpv2.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this NetworkView.
func (mg *NetworkView) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this NetworkView.
func (mg *NetworkView) GetProviderConfigReference() *xpv2.Reference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this NetworkView.
func (mg *NetworkView) GetWriteConnectionSecretToReference() *xpv2.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this NetworkView.
func (mg *NetworkView) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this NetworkView.
func (mg *NetworkView) SetDeletionPolicy(r xpv2.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this NetworkView.
func (mg *NetworkView) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this NetworkView.
func (mg *NetworkView) SetProviderConfigReference(r *xpv2.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this NetworkView.
func (mg *NetworkView) SetWriteConnectionSecretToReference(r *xpv2.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}
