// Code generated by openapi2crd. DO NOT EDIT.

// Package v1alpha1 contains the Cluster-scoped NetworkContainer managed resource.
// API group: networkcontainer.infobloxnios.crossplane.io
package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// NetworkContainerParameters are the configurable fields of a NetworkContainer.
type NetworkContainerParameters struct {
	// Network view the container belongs to. Immutable — absent from UpdateNetworkContainer. Identifies a NetworkView by name.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="networkView is immutable after creation"
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-infoblox-nios/apis/cluster/networkview/v1alpha1.NetworkView
	NetworkView *string `json:"networkView"`
	// +optional
	NetworkViewRef *xpv1.Reference `json:"networkViewRef,omitempty"`
	// +optional
	NetworkViewSelector *xpv1.Selector `json:"networkViewSelector,omitempty"`
	// CIDR of the container network, e.g. "10.0.0.0/16". Immutable — absent from UpdateNetworkContainer.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="network is immutable after creation"
	Network *string `json:"network"`
	// Comment for the network container.
	Comment *string `json:"comment,omitempty"`
	// Extensible attributes (arbitrary key/value metadata defined in Grid Manager). The WAPI wire format wraps each value as {"value": ...}; this map is the simplified string-valued CRD representation (the controller translates to/from the SDK's EA map[string]interface{} type).
	// +optional
	ExtAttrs map[string]string `json:"extAttrs"`
}

// NetworkContainerObservation holds the observed state of a NetworkContainer.
// It mirrors every NetworkContainerParameters field plus response-only fields
// (full-mirror AtProvider) so users can compare forProvider to
// atProvider before switching to full management
// (managementPolicies: ["Observe"]).
type NetworkContainerObservation struct {
	// Server-assigned external identifier for this resource, set by Observe()
	// from the resource's external name. Used by import testing to confirm
	// the controller re-discovers the resource after a restart.
	// +optional
	ID string `json:"id,omitempty"` // atProvider
	// Network view the container belongs to. Immutable — absent from UpdateNetworkContainer. Identifies a NetworkView by name.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="networkView is immutable after creation"
	NetworkView *string `json:"networkView,omitempty"` // atProvider
	// CIDR of the container network, e.g. "10.0.0.0/16". Immutable — absent from UpdateNetworkContainer.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="network is immutable after creation"
	Network *string `json:"network,omitempty"` // atProvider
	// Comment for the network container.
	Comment *string `json:"comment,omitempty"` // atProvider
	// Extensible attributes (arbitrary key/value metadata defined in Grid Manager). The WAPI wire format wraps each value as {"value": ...}; this map is the simplified string-valued CRD representation (the controller translates to/from the SDK's EA map[string]interface{} type).
	// +optional
	ExtAttrs map[string]string `json:"extAttrs"` // atProvider
	// Server-assigned opaque object reference (WAPI `_ref`). Mirrors the crossplane.io/external-name annotation for observability and uptest import verification.
	Ref *string `json:"ref,omitempty"` // atProvider
}

// NetworkContainerSpec defines the desired state of NetworkContainer.
type NetworkContainerSpec struct {
	xpv1.ResourceSpec `json:",inline"`

	// ForProvider holds the user-supplied parameters for this NetworkContainer.
	// +kubebuilder:validation:Required
	ForProvider NetworkContainerParameters `json:"forProvider"`
}

// NetworkContainerStatus defines the observed state of NetworkContainer.
type NetworkContainerStatus struct {
	xpv1.ResourceStatus `json:",inline"`

	// AtProvider holds the observed values from the Infoblox NIOS WAPI.
	// +optional
	AtProvider NetworkContainerObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:storageversion
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,infobloxnios}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"

// NetworkContainer is the Cluster-scoped managed resource representing an Infoblox NIOS NetworkContainer.
type NetworkContainer struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   NetworkContainerSpec   `json:"spec"`
	Status NetworkContainerStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NetworkContainerList contains a list of NetworkContainer.
type NetworkContainerList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NetworkContainer `json:"items"`
}
