// Code generated by hack/generate-registration.go. DO NOT EDIT.
//
// SetupGated defers MR controller startup until CRDs are installed (SafeStart).
// Setup starts all controllers immediately (RBAC fallback path).
// ProviderConfig (config.Setup) is NEVER gated — it must always be available.
// See the gated controller registration convention (SafeStart pattern).

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

package controller

import (
	"github.com/crossplane-contrib/provider-infoblox-nios/internal/controller/config"
	"github.com/crossplane-contrib/provider-infoblox-nios/internal/controller/fixedaddress"
	"github.com/crossplane-contrib/provider-infoblox-nios/internal/controller/hostrecord"
	"github.com/crossplane-contrib/provider-infoblox-nios/internal/controller/ipv4sharednetwork"
	"github.com/crossplane-contrib/provider-infoblox-nios/internal/controller/network"
	"github.com/crossplane-contrib/provider-infoblox-nios/internal/controller/networkcontainer"
	"github.com/crossplane-contrib/provider-infoblox-nios/internal/controller/networkview"
	rangepkg "github.com/crossplane-contrib/provider-infoblox-nios/internal/controller/range"
	"github.com/crossplane-contrib/provider-infoblox-nios/internal/controller/rangetemplate"
	"github.com/crossplane-contrib/provider-infoblox-nios/internal/controller/recorda"
	"github.com/crossplane-contrib/provider-infoblox-nios/internal/controller/recordaaaa"
	"github.com/crossplane-contrib/provider-infoblox-nios/internal/controller/recordcname"
	"github.com/crossplane-contrib/provider-infoblox-nios/internal/controller/recordmx"
	"github.com/crossplane-contrib/provider-infoblox-nios/internal/controller/recordptr"
	"github.com/crossplane-contrib/provider-infoblox-nios/internal/controller/recordsrv"
	"github.com/crossplane-contrib/provider-infoblox-nios/internal/controller/recordtxt"
	"github.com/crossplane-contrib/provider-infoblox-nios/internal/controller/zoneauth"
	"github.com/crossplane-contrib/provider-infoblox-nios/internal/controller/zonedelegated"
	"github.com/crossplane-contrib/provider-infoblox-nios/internal/controller/zoneforward"
	"github.com/crossplane/crossplane-runtime/v2/pkg/controller"
	ctrl "sigs.k8s.io/controller-runtime"
)

// SetupGated creates all controllers with safe-start (gate) support.
// MR controllers defer startup until CRDs are installed.
func SetupGated(mgr ctrl.Manager, o controller.Options) error {
	for _, setup := range []func(ctrl.Manager, controller.Options) error{
		// ProviderConfig — never gated, must always be available.
		config.Setup,
		fixedaddress.SetupGated,
		hostrecord.SetupGated,
		ipv4sharednetwork.SetupGated,
		network.SetupGated,
		networkcontainer.SetupGated,
		networkview.SetupGated,
		rangepkg.SetupGated,
		rangetemplate.SetupGated,
		recorda.SetupGated,
		recordaaaa.SetupGated,
		recordcname.SetupGated,
		recordmx.SetupGated,
		recordptr.SetupGated,
		recordsrv.SetupGated,
		recordtxt.SetupGated,
		zoneauth.SetupGated,
		zonedelegated.SetupGated,
		zoneforward.SetupGated,
	} {
		if err := setup(mgr, o); err != nil {
			return err
		}
	}
	return nil
}

// Setup creates all controllers without gate support (RBAC fallback).
// MR controllers start immediately without waiting for CRD installation.
func Setup(mgr ctrl.Manager, o controller.Options) error {
	for _, setup := range []func(ctrl.Manager, controller.Options) error{
		// ProviderConfig — never gated, must always be available.
		config.Setup,
		fixedaddress.Setup,
		hostrecord.Setup,
		ipv4sharednetwork.Setup,
		network.Setup,
		networkcontainer.Setup,
		networkview.Setup,
		rangepkg.Setup,
		rangetemplate.Setup,
		recorda.Setup,
		recordaaaa.Setup,
		recordcname.Setup,
		recordmx.Setup,
		recordptr.Setup,
		recordsrv.Setup,
		recordtxt.Setup,
		zoneauth.Setup,
		zonedelegated.Setup,
		zoneforward.Setup,
	} {
		if err := setup(mgr, o); err != nil {
			return err
		}
	}
	return nil
}
