//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MXRecord) DeepCopyInto(out *MXRecord) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MXRecord.
func (in *MXRecord) DeepCopy() *MXRecord {
	if in == nil {
		return nil
	}
	out := new(MXRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MXRecord) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MXRecordAwsRte53RecordInfo) DeepCopyInto(out *MXRecordAwsRte53RecordInfo) {
	*out = *in
	if in.AliasTargetDnsName != nil {
		in, out := &in.AliasTargetDnsName, &out.AliasTargetDnsName
		*out = new(string)
		**out = **in
	}
	if in.AliasTargetHostedZoneId != nil {
		in, out := &in.AliasTargetHostedZoneId, &out.AliasTargetHostedZoneId
		*out = new(string)
		**out = **in
	}
	if in.AliasTargetEvaluateTargetHealth != nil {
		in, out := &in.AliasTargetEvaluateTargetHealth, &out.AliasTargetEvaluateTargetHealth
		*out = new(bool)
		**out = **in
	}
	if in.Failover != nil {
		in, out := &in.Failover, &out.Failover
		*out = new(string)
		**out = **in
	}
	if in.GeolocationContinentCode != nil {
		in, out := &in.GeolocationContinentCode, &out.GeolocationContinentCode
		*out = new(string)
		**out = **in
	}
	if in.GeolocationCountryCode != nil {
		in, out := &in.GeolocationCountryCode, &out.GeolocationCountryCode
		*out = new(string)
		**out = **in
	}
	if in.GeolocationSubdivisionCode != nil {
		in, out := &in.GeolocationSubdivisionCode, &out.GeolocationSubdivisionCode
		*out = new(string)
		**out = **in
	}
	if in.HealthCheckId != nil {
		in, out := &in.HealthCheckId, &out.HealthCheckId
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.SetIdentifier != nil {
		in, out := &in.SetIdentifier, &out.SetIdentifier
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.Weight != nil {
		in, out := &in.Weight, &out.Weight
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MXRecordAwsRte53RecordInfo.
func (in *MXRecordAwsRte53RecordInfo) DeepCopy() *MXRecordAwsRte53RecordInfo {
	if in == nil {
		return nil
	}
	out := new(MXRecordAwsRte53RecordInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MXRecordCloudInfo) DeepCopyInto(out *MXRecordCloudInfo) {
	*out = *in
	if in.DelegatedMember != nil {
		in, out := &in.DelegatedMember, &out.DelegatedMember
		*out = new(MXRecordCloudInfoDelegatedMember)
		(*in).DeepCopyInto(*out)
	}
	if in.DelegatedScope != nil {
		in, out := &in.DelegatedScope, &out.DelegatedScope
		*out = new(string)
		**out = **in
	}
	if in.DelegatedRoot != nil {
		in, out := &in.DelegatedRoot, &out.DelegatedRoot
		*out = new(string)
		**out = **in
	}
	if in.OwnedByAdaptor != nil {
		in, out := &in.OwnedByAdaptor, &out.OwnedByAdaptor
		*out = new(bool)
		**out = **in
	}
	if in.Usage != nil {
		in, out := &in.Usage, &out.Usage
		*out = new(string)
		**out = **in
	}
	if in.Tenant != nil {
		in, out := &in.Tenant, &out.Tenant
		*out = new(string)
		**out = **in
	}
	if in.MgmtPlatform != nil {
		in, out := &in.MgmtPlatform, &out.MgmtPlatform
		*out = new(string)
		**out = **in
	}
	if in.AuthorityType != nil {
		in, out := &in.AuthorityType, &out.AuthorityType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MXRecordCloudInfo.
func (in *MXRecordCloudInfo) DeepCopy() *MXRecordCloudInfo {
	if in == nil {
		return nil
	}
	out := new(MXRecordCloudInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MXRecordCloudInfoDelegatedMember) DeepCopyInto(out *MXRecordCloudInfoDelegatedMember) {
	*out = *in
	if in.Ipv4Addr != nil {
		in, out := &in.Ipv4Addr, &out.Ipv4Addr
		*out = new(string)
		**out = **in
	}
	if in.Ipv6Addr != nil {
		in, out := &in.Ipv6Addr, &out.Ipv6Addr
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MXRecordCloudInfoDelegatedMember.
func (in *MXRecordCloudInfoDelegatedMember) DeepCopy() *MXRecordCloudInfoDelegatedMember {
	if in == nil {
		return nil
	}
	out := new(MXRecordCloudInfoDelegatedMember)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MXRecordList) DeepCopyInto(out *MXRecordList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MXRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MXRecordList.
func (in *MXRecordList) DeepCopy() *MXRecordList {
	if in == nil {
		return nil
	}
	out := new(MXRecordList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MXRecordList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MXRecordMsAdUserData) DeepCopyInto(out *MXRecordMsAdUserData) {
	*out = *in
	if in.ActiveUsersCount != nil {
		in, out := &in.ActiveUsersCount, &out.ActiveUsersCount
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MXRecordMsAdUserData.
func (in *MXRecordMsAdUserData) DeepCopy() *MXRecordMsAdUserData {
	if in == nil {
		return nil
	}
	out := new(MXRecordMsAdUserData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MXRecordObservation) DeepCopyInto(out *MXRecordObservation) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.MailExchanger != nil {
		in, out := &in.MailExchanger, &out.MailExchanger
		*out = new(string)
		**out = **in
	}
	if in.Preference != nil {
		in, out := &in.Preference, &out.Preference
		*out = new(int64)
		**out = **in
	}
	if in.Comment != nil {
		in, out := &in.Comment, &out.Comment
		*out = new(string)
		**out = **in
	}
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(uint32)
		**out = **in
	}
	if in.UseTTL != nil {
		in, out := &in.UseTTL, &out.UseTTL
		*out = new(bool)
		**out = **in
	}
	if in.ExtAttrs != nil {
		in, out := &in.ExtAttrs, &out.ExtAttrs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.View != nil {
		in, out := &in.View, &out.View
		*out = new(string)
		**out = **in
	}
	if in.Ref != nil {
		in, out := &in.Ref, &out.Ref
		*out = new(string)
		**out = **in
	}
	if in.Zone != nil {
		in, out := &in.Zone, &out.Zone
		*out = new(string)
		**out = **in
	}
	if in.DNSName != nil {
		in, out := &in.DNSName, &out.DNSName
		*out = new(string)
		**out = **in
	}
	if in.DNSMailExchanger != nil {
		in, out := &in.DNSMailExchanger, &out.DNSMailExchanger
		*out = new(string)
		**out = **in
	}
	if in.Creator != nil {
		in, out := &in.Creator, &out.Creator
		*out = new(string)
		**out = **in
	}
	if in.CreationTime != nil {
		in, out := &in.CreationTime, &out.CreationTime
		*out = new(int64)
		**out = **in
	}
	if in.LastQueried != nil {
		in, out := &in.LastQueried, &out.LastQueried
		*out = new(int64)
		**out = **in
	}
	if in.DdnsPrincipal != nil {
		in, out := &in.DdnsPrincipal, &out.DdnsPrincipal
		*out = new(string)
		**out = **in
	}
	if in.DdnsProtected != nil {
		in, out := &in.DdnsProtected, &out.DdnsProtected
		*out = new(bool)
		**out = **in
	}
	if in.ForbidReclamation != nil {
		in, out := &in.ForbidReclamation, &out.ForbidReclamation
		*out = new(bool)
		**out = **in
	}
	if in.Reclaimable != nil {
		in, out := &in.Reclaimable, &out.Reclaimable
		*out = new(bool)
		**out = **in
	}
	if in.SharedRecordGroup != nil {
		in, out := &in.SharedRecordGroup, &out.SharedRecordGroup
		*out = new(string)
		**out = **in
	}
	if in.AwsRte53RecordInfo != nil {
		in, out := &in.AwsRte53RecordInfo, &out.AwsRte53RecordInfo
		*out = new(MXRecordAwsRte53RecordInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.CloudInfo != nil {
		in, out := &in.CloudInfo, &out.CloudInfo
		*out = new(MXRecordCloudInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.MsAdUserData != nil {
		in, out := &in.MsAdUserData, &out.MsAdUserData
		*out = new(MXRecordMsAdUserData)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MXRecordObservation.
func (in *MXRecordObservation) DeepCopy() *MXRecordObservation {
	if in == nil {
		return nil
	}
	out := new(MXRecordObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MXRecordParameters) DeepCopyInto(out *MXRecordParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.MailExchanger != nil {
		in, out := &in.MailExchanger, &out.MailExchanger
		*out = new(string)
		**out = **in
	}
	if in.Preference != nil {
		in, out := &in.Preference, &out.Preference
		*out = new(int64)
		**out = **in
	}
	if in.Comment != nil {
		in, out := &in.Comment, &out.Comment
		*out = new(string)
		**out = **in
	}
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(uint32)
		**out = **in
	}
	if in.UseTTL != nil {
		in, out := &in.UseTTL, &out.UseTTL
		*out = new(bool)
		**out = **in
	}
	if in.ExtAttrs != nil {
		in, out := &in.ExtAttrs, &out.ExtAttrs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.View != nil {
		in, out := &in.View, &out.View
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MXRecordParameters.
func (in *MXRecordParameters) DeepCopy() *MXRecordParameters {
	if in == nil {
		return nil
	}
	out := new(MXRecordParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MXRecordSpec) DeepCopyInto(out *MXRecordSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MXRecordSpec.
func (in *MXRecordSpec) DeepCopy() *MXRecordSpec {
	if in == nil {
		return nil
	}
	out := new(MXRecordSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MXRecordStatus) DeepCopyInto(out *MXRecordStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MXRecordStatus.
func (in *MXRecordStatus) DeepCopy() *MXRecordStatus {
	if in == nil {
		return nil
	}
	out := new(MXRecordStatus)
	in.DeepCopyInto(out)
	return out
}
