//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNAMERecord) DeepCopyInto(out *CNAMERecord) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNAMERecord.
func (in *CNAMERecord) DeepCopy() *CNAMERecord {
	if in == nil {
		return nil
	}
	out := new(CNAMERecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CNAMERecord) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNAMERecordList) DeepCopyInto(out *CNAMERecordList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CNAMERecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNAMERecordList.
func (in *CNAMERecordList) DeepCopy() *CNAMERecordList {
	if in == nil {
		return nil
	}
	out := new(CNAMERecordList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CNAMERecordList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNAMERecordObservation) DeepCopyInto(out *CNAMERecordObservation) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Canonical != nil {
		in, out := &in.Canonical, &out.Canonical
		*out = new(string)
		**out = **in
	}
	if in.Comment != nil {
		in, out := &in.Comment, &out.Comment
		*out = new(string)
		**out = **in
	}
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(int64)
		**out = **in
	}
	if in.UseTTL != nil {
		in, out := &in.UseTTL, &out.UseTTL
		*out = new(bool)
		**out = **in
	}
	if in.ExtAttrs != nil {
		in, out := &in.ExtAttrs, &out.ExtAttrs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.View != nil {
		in, out := &in.View, &out.View
		*out = new(string)
		**out = **in
	}
	if in.Ref != nil {
		in, out := &in.Ref, &out.Ref
		*out = new(string)
		**out = **in
	}
	if in.Zone != nil {
		in, out := &in.Zone, &out.Zone
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNAMERecordObservation.
func (in *CNAMERecordObservation) DeepCopy() *CNAMERecordObservation {
	if in == nil {
		return nil
	}
	out := new(CNAMERecordObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNAMERecordParameters) DeepCopyInto(out *CNAMERecordParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Canonical != nil {
		in, out := &in.Canonical, &out.Canonical
		*out = new(string)
		**out = **in
	}
	if in.CanonicalRef != nil {
		in, out := &in.CanonicalRef, &out.CanonicalRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.CanonicalSelector != nil {
		in, out := &in.CanonicalSelector, &out.CanonicalSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Comment != nil {
		in, out := &in.Comment, &out.Comment
		*out = new(string)
		**out = **in
	}
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(int64)
		**out = **in
	}
	if in.UseTTL != nil {
		in, out := &in.UseTTL, &out.UseTTL
		*out = new(bool)
		**out = **in
	}
	if in.ExtAttrs != nil {
		in, out := &in.ExtAttrs, &out.ExtAttrs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.View != nil {
		in, out := &in.View, &out.View
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNAMERecordParameters.
func (in *CNAMERecordParameters) DeepCopy() *CNAMERecordParameters {
	if in == nil {
		return nil
	}
	out := new(CNAMERecordParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNAMERecordSpec) DeepCopyInto(out *CNAMERecordSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNAMERecordSpec.
func (in *CNAMERecordSpec) DeepCopy() *CNAMERecordSpec {
	if in == nil {
		return nil
	}
	out := new(CNAMERecordSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNAMERecordStatus) DeepCopyInto(out *CNAMERecordStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNAMERecordStatus.
func (in *CNAMERecordStatus) DeepCopy() *CNAMERecordStatus {
	if in == nil {
		return nil
	}
	out := new(CNAMERecordStatus)
	in.DeepCopyInto(out)
	return out
}
