// Code generated by openapi2crd. DO NOT EDIT.

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Package referencehelpers provides generic cross-resource reference
// extractors shared across every resource's generated types. It is
// intentionally a leaf package (imports nothing under apis/) so any
// apis/{cluster,namespaced}/<slug>/v1alpha1 package can import it without
// risk of an import cycle with the root apis package (which imports every
// scope package for scheme registration).
package referencehelpers

import (
	"github.com/crossplane/crossplane-runtime/v2/pkg/fieldpath"
	"github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	"github.com/crossplane/crossplane-runtime/v2/pkg/resource"
)

// ExtractField returns a cross-resource reference extractor that reads an
// arbitrary field off a referenced managed resource by JSON field path
// (e.g. "spec.forProvider.network"), using fieldpath.PaveObject. It is the
// native-provider equivalent of upjet's ExtractParamPath: unlike the
// crossplane-runtime default reference.ExternalName() extractor, which
// always reads the crossplane.io/external-name annotation, ExtractField
// lets a +crossplane:generate:reference:extractor= marker resolve to any
// field on the target's spec or status. Because it works generically via
// reflection, it needs no import of any resource-specific package, so it
// cannot introduce an import cycle between resources that reference each
// other.
//
// An empty return means "not yet resolvable" (missing field, wrong type,
// or the target hasn't populated the field yet) — crossplane-runtime
// reference resolution treats this as "referenced field was empty" and
// requeues.
func ExtractField(path string) reference.ExtractValueFn {
	return func(mg resource.Managed) string {
		paved, err := fieldpath.PaveObject(mg)
		if err != nil {
			return ""
		}
		v, err := paved.GetString(path)
		if err != nil {
			return ""
		}
		return v
	}
}
