//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPv4SharedNetwork) DeepCopyInto(out *IPv4SharedNetwork) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPv4SharedNetwork.
func (in *IPv4SharedNetwork) DeepCopy() *IPv4SharedNetwork {
	if in == nil {
		return nil
	}
	out := new(IPv4SharedNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IPv4SharedNetwork) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPv4SharedNetworkDhcpOption) DeepCopyInto(out *IPv4SharedNetworkDhcpOption) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Num != nil {
		in, out := &in.Num, &out.Num
		*out = new(uint32)
		**out = **in
	}
	if in.VendorClass != nil {
		in, out := &in.VendorClass, &out.VendorClass
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
	if in.UseOption != nil {
		in, out := &in.UseOption, &out.UseOption
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPv4SharedNetworkDhcpOption.
func (in *IPv4SharedNetworkDhcpOption) DeepCopy() *IPv4SharedNetworkDhcpOption {
	if in == nil {
		return nil
	}
	out := new(IPv4SharedNetworkDhcpOption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPv4SharedNetworkList) DeepCopyInto(out *IPv4SharedNetworkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IPv4SharedNetwork, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPv4SharedNetworkList.
func (in *IPv4SharedNetworkList) DeepCopy() *IPv4SharedNetworkList {
	if in == nil {
		return nil
	}
	out := new(IPv4SharedNetworkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IPv4SharedNetworkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPv4SharedNetworkObservation) DeepCopyInto(out *IPv4SharedNetworkObservation) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Networks != nil {
		in, out := &in.Networks, &out.Networks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NetworkView != nil {
		in, out := &in.NetworkView, &out.NetworkView
		*out = new(string)
		**out = **in
	}
	if in.Comment != nil {
		in, out := &in.Comment, &out.Comment
		*out = new(string)
		**out = **in
	}
	if in.ExtAttrs != nil {
		in, out := &in.ExtAttrs, &out.ExtAttrs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Disable != nil {
		in, out := &in.Disable, &out.Disable
		*out = new(bool)
		**out = **in
	}
	if in.UseOptions != nil {
		in, out := &in.UseOptions, &out.UseOptions
		*out = new(bool)
		**out = **in
	}
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make([]*IPv4SharedNetworkDhcpOption, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(IPv4SharedNetworkDhcpOption)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Ref != nil {
		in, out := &in.Ref, &out.Ref
		*out = new(string)
		**out = **in
	}
	if in.Authority != nil {
		in, out := &in.Authority, &out.Authority
		*out = new(bool)
		**out = **in
	}
	if in.DdnsTTL != nil {
		in, out := &in.DdnsTTL, &out.DdnsTTL
		*out = new(uint32)
		**out = **in
	}
	if in.EnableDdns != nil {
		in, out := &in.EnableDdns, &out.EnableDdns
		*out = new(bool)
		**out = **in
	}
	if in.DhcpUtilization != nil {
		in, out := &in.DhcpUtilization, &out.DhcpUtilization
		*out = new(uint32)
		**out = **in
	}
	if in.DhcpUtilizationStatus != nil {
		in, out := &in.DhcpUtilizationStatus, &out.DhcpUtilizationStatus
		*out = new(string)
		**out = **in
	}
	if in.DynamicHosts != nil {
		in, out := &in.DynamicHosts, &out.DynamicHosts
		*out = new(uint32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPv4SharedNetworkObservation.
func (in *IPv4SharedNetworkObservation) DeepCopy() *IPv4SharedNetworkObservation {
	if in == nil {
		return nil
	}
	out := new(IPv4SharedNetworkObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPv4SharedNetworkParameters) DeepCopyInto(out *IPv4SharedNetworkParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Networks != nil {
		in, out := &in.Networks, &out.Networks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NetworksRefs != nil {
		in, out := &in.NetworksRefs, &out.NetworksRefs
		*out = make([]v1.NamespacedReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NetworksSelector != nil {
		in, out := &in.NetworksSelector, &out.NetworksSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.NetworkView != nil {
		in, out := &in.NetworkView, &out.NetworkView
		*out = new(string)
		**out = **in
	}
	if in.Comment != nil {
		in, out := &in.Comment, &out.Comment
		*out = new(string)
		**out = **in
	}
	if in.ExtAttrs != nil {
		in, out := &in.ExtAttrs, &out.ExtAttrs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Disable != nil {
		in, out := &in.Disable, &out.Disable
		*out = new(bool)
		**out = **in
	}
	if in.UseOptions != nil {
		in, out := &in.UseOptions, &out.UseOptions
		*out = new(bool)
		**out = **in
	}
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make([]*IPv4SharedNetworkDhcpOption, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(IPv4SharedNetworkDhcpOption)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPv4SharedNetworkParameters.
func (in *IPv4SharedNetworkParameters) DeepCopy() *IPv4SharedNetworkParameters {
	if in == nil {
		return nil
	}
	out := new(IPv4SharedNetworkParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPv4SharedNetworkSpec) DeepCopyInto(out *IPv4SharedNetworkSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPv4SharedNetworkSpec.
func (in *IPv4SharedNetworkSpec) DeepCopy() *IPv4SharedNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(IPv4SharedNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPv4SharedNetworkStatus) DeepCopyInto(out *IPv4SharedNetworkStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPv4SharedNetworkStatus.
func (in *IPv4SharedNetworkStatus) DeepCopy() *IPv4SharedNetworkStatus {
	if in == nil {
		return nil
	}
	out := new(IPv4SharedNetworkStatus)
	in.DeepCopyInto(out)
	return out
}
