// Code generated by openapi2crd. DO NOT EDIT.

// Package v1alpha1 contains the Cluster-scoped DTCPool managed resource.
// API group: dtcpool.infobloxnios.crossplane.io
package v1alpha1

import (
	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DTCPoolServerLink identifies one DTCServer member of a DTCPool along with its load-balancing weight (mirrors the SDK's DtcServerLink struct).
type DTCPoolServerLink struct {
	// DTCServer member of the pool, identified by its Crossplane external-name (the DTCServer's WAPI `_ref`).
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-infoblox-nios/apis/cluster/dtcserver/v1alpha1.DTCServer
	Server *string `json:"server,omitempty"`
	// +optional
	ServerRef *xpv2.Reference `json:"serverRef,omitempty"`
	// +optional
	ServerSelector *xpv2.Selector `json:"serverSelector,omitempty"`
	// The load-balancing weight of the server within the pool.
	Ratio *uint32 `json:"ratio,omitempty"`
}

// DTCPoolMonitor identifies a health monitor associated with a DTCPool by its WAPI `_ref` (mirrors the SDK's polymorphic Monitor interface, simplified to a reference — no monitor sub-type is independently cataloged today).
type DTCPoolMonitor struct {
	// Reference (`_ref`) of the monitor associated with the pool, e.g. "dtc:monitor:http/ZG5z...".
	Monitor *string `json:"monitor,omitempty"`
}

// DTCPoolDynamicRatio carries dynamic-ratio load balancing settings for a DTCPool (mirrors the SDK's SettingDynamicratio struct); reused for both lbDynamicRatioPreferred and lbDynamicRatioAlternate.
type DTCPoolDynamicRatio struct {
	// The method of the DTC dynamic ratio load balancing.
	Method *string `json:"method,omitempty"`
	// The DTC monitor whose output is used for dynamic ratio load balancing.
	Monitor *string `json:"monitor,omitempty"`
	// The metric of the DTC SNMP monitor used for dynamic weighing.
	MonitorMetric *string `json:"monitorMetric,omitempty"`
	// How the DTC monitor weight is applied: PRIORITY forwards clients to the least loaded server; RATIO calculates distribution from dynamic weights.
	MonitorWeighing *string `json:"monitorWeighing,omitempty"`
	// Whether the inverted values of the DTC SNMP monitor metric are used.
	InvertMonitorMetric *bool `json:"invertMonitorMetric,omitempty"`
}

// DTCPoolConsolidatedMonitorHealth carries consolidated monitor health status shared across pool members (mirrors the SDK's DtcPoolConsolidatedMonitorHealth struct).
type DTCPoolConsolidatedMonitorHealth struct {
	// Members whose monitor statuses are shared across other members in the pool.
	// +optional
	Members []string `json:"members"`
	// Monitor whose statuses are shared across other members in the pool.
	Monitor *string `json:"monitor,omitempty"`
	// Servers assigned to the pool with this monitor are healthy if ANY or ALL members report a healthy status.
	Availability *string `json:"availability,omitempty"`
	// Whether health checks are performed on each DTC Grid member serving related LBDN(s) and shared across all DTC Grid members, not just the selected list.
	FullHealthCommunication *bool `json:"fullHealthCommunication,omitempty"`
}

// DTCPoolHealth carries the aggregate health status of a DTCPool (mirrors the SDK's DtcHealth struct).
type DTCPoolHealth struct {
	// The availability color status.
	Availability *string `json:"availability,omitempty"`
	// The textual description of the object's status.
	Description *string `json:"description,omitempty"`
	// The enabled state of the object.
	EnabledState *string `json:"enabledState,omitempty"`
}

// DTCPoolParameters are the configurable fields of a DTCPool.
type DTCPoolParameters struct {
	// DTC Pool display name. Mutable, but changes are not reference-resolved on the fly by referencing DTCLBDN resources — see the DTCLBDN resource note when it is onboarded.
	// +kubebuilder:validation:Required
	Name *string `json:"name"`
	// Preferred load balancing method used to select a server from the pool.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Enum=ROUND_ROBIN;RATIO;TOPOLOGY;DYNAMIC_RATIO;GLOBAL_AVAILABILITY;ALL_AVAILABLE
	LBPreferredMethod *string `json:"lbPreferredMethod"`
	// Fallback load balancing method used if lbPreferredMethod returns no results. NONE is accepted here for backward compatibility with existing manifests, but the backend never accepts it as an explicit write value — it only appears on read-back as the server's default when the field is left unset, and the controller normalizes it to "unset" on both the read and write paths.
	// +kubebuilder:validation:Enum=NONE;ROUND_ROBIN;RATIO;TOPOLOGY;DYNAMIC_RATIO;GLOBAL_AVAILABILITY;ALL_AVAILABLE
	LBAlternateMethod *string `json:"lbAlternateMethod,omitempty"`
	// DTC Servers that are members of this pool, each with a per-server ratio/weight.
	// +optional
	Servers []DTCPoolServerLink `json:"servers"`
	// Determines when a pool member is considered available: ANY, at least QUORUM, or ALL of its monitors report it up.
	// +kubebuilder:validation:Enum=ANY;QUORUM;ALL
	Availability *string `json:"availability,omitempty"`
	// Minimum number of monitors that must report a resource as up for it to be available. Only meaningful when availability=QUORUM.
	Quorum *uint32 `json:"quorum,omitempty"`
	// Topology ruleset name used when lbPreferredMethod=TOPOLOGY.
	LBPreferredTopology *string `json:"lbPreferredTopology,omitempty"`
	// Dynamic-ratio settings used when lbPreferredMethod=DYNAMIC_RATIO.
	LBDynamicRatioPreferred *DTCPoolDynamicRatio `json:"lbDynamicRatioPreferred,omitempty"`
	// Topology ruleset name used when lbAlternateMethod=TOPOLOGY.
	LBAlternateTopology *string `json:"lbAlternateTopology,omitempty"`
	// Dynamic-ratio settings used when lbAlternateMethod=DYNAMIC_RATIO.
	LBDynamicRatioAlternate *DTCPoolDynamicRatio `json:"lbDynamicRatioAlternate,omitempty"`
	// Health monitors associated with the pool.
	// +optional
	Monitors []DTCPoolMonitor `json:"monitors"`
	// Comment for the DTC Pool; maximum 256 characters.
	Comment *string `json:"comment,omitempty"`
	// Whether the DTC Pool is disabled.
	Disable *bool `json:"disable,omitempty"`
	// Time-To-Live for the DTC Pool response, in seconds. Zero indicates the record should not be cached. Must be non-negative (0-2147483647); to inherit the zone/grid default, set useTtl to false rather than passing a negative sentinel value.
	// +kubebuilder:validation:Minimum=0
	// +kubebuilder:validation:Maximum=2147483647
	TTL *uint32 `json:"ttl,omitempty"`
	// Use flag for ttl.
	UseTTL *bool `json:"useTtl,omitempty"`
	// Extensible attributes (arbitrary key/value metadata defined in Grid Manager). The WAPI wire format wraps each value as {"value": ...}; this map is the simplified string-valued CRD representation (the controller translates to/from the SDK's EA map[string]interface{} type).
	// +optional
	// +kubebuilder:validation:XValidation:rule="self.all(k, k != 'Crossplane Internal ID')",message="the 'Crossplane Internal ID' extensible attribute is reserved for the provider's identity stamp and cannot be set in spec.forProvider.extAttrs"
	ExtAttrs map[string]string `json:"extAttrs"`
}

// DTCPoolObservation holds the observed state of a DTCPool.
// It mirrors every DTCPoolParameters field plus response-only fields
// (full-mirror AtProvider) so users can compare forProvider to
// atProvider before switching to full management
// (managementPolicies: ["Observe"]).
type DTCPoolObservation struct {
	// Server-assigned external identifier for this resource, set by Observe()
	// from the resource's external name. Used by import testing to confirm
	// the controller re-discovers the resource after a restart.
	// +optional
	ID string `json:"id,omitempty"` // atProvider
	// DTC Pool display name. Mutable, but changes are not reference-resolved on the fly by referencing DTCLBDN resources — see the DTCLBDN resource note when it is onboarded.
	Name *string `json:"name,omitempty"` // atProvider
	// Preferred load balancing method used to select a server from the pool.
	LBPreferredMethod *string `json:"lbPreferredMethod,omitempty"` // atProvider
	// Fallback load balancing method used if lbPreferredMethod returns no results. NONE is accepted here for backward compatibility with existing manifests, but the backend never accepts it as an explicit write value — it only appears on read-back as the server's default when the field is left unset, and the controller normalizes it to "unset" on both the read and write paths.
	LBAlternateMethod *string `json:"lbAlternateMethod,omitempty"` // atProvider
	// DTC Servers that are members of this pool, each with a per-server ratio/weight.
	// +optional
	Servers []DTCPoolServerLink `json:"servers"` // atProvider
	// Determines when a pool member is considered available: ANY, at least QUORUM, or ALL of its monitors report it up.
	Availability *string `json:"availability,omitempty"` // atProvider
	// Minimum number of monitors that must report a resource as up for it to be available. Only meaningful when availability=QUORUM.
	Quorum *uint32 `json:"quorum,omitempty"` // atProvider
	// Topology ruleset name used when lbPreferredMethod=TOPOLOGY.
	LBPreferredTopology *string `json:"lbPreferredTopology,omitempty"` // atProvider
	// Dynamic-ratio settings used when lbPreferredMethod=DYNAMIC_RATIO.
	LBDynamicRatioPreferred *DTCPoolDynamicRatio `json:"lbDynamicRatioPreferred,omitempty"` // atProvider
	// Topology ruleset name used when lbAlternateMethod=TOPOLOGY.
	LBAlternateTopology *string `json:"lbAlternateTopology,omitempty"` // atProvider
	// Dynamic-ratio settings used when lbAlternateMethod=DYNAMIC_RATIO.
	LBDynamicRatioAlternate *DTCPoolDynamicRatio `json:"lbDynamicRatioAlternate,omitempty"` // atProvider
	// Health monitors associated with the pool.
	// +optional
	Monitors []DTCPoolMonitor `json:"monitors"` // atProvider
	// Comment for the DTC Pool; maximum 256 characters.
	Comment *string `json:"comment,omitempty"` // atProvider
	// Whether the DTC Pool is disabled.
	Disable *bool `json:"disable,omitempty"` // atProvider
	// Time-To-Live for the DTC Pool response, in seconds. Zero indicates the record should not be cached. Must be non-negative (0-2147483647); to inherit the zone/grid default, set useTtl to false rather than passing a negative sentinel value.
	TTL *uint32 `json:"ttl,omitempty"` // atProvider
	// Use flag for ttl.
	UseTTL *bool `json:"useTtl,omitempty"` // atProvider
	// Extensible attributes (arbitrary key/value metadata defined in Grid Manager). The WAPI wire format wraps each value as {"value": ...}; this map is the simplified string-valued CRD representation (the controller translates to/from the SDK's EA map[string]interface{} type).
	// +optional
	ExtAttrs map[string]string `json:"extAttrs"` // atProvider
	// Server-assigned opaque object reference (WAPI `_ref`). Mirrors the crossplane.io/external-name annotation for observability and uptest import verification.
	Ref *string `json:"ref,omitempty"` // atProvider
	// Consolidated monitor health status shared across pool members. Read-only — Update accepts a differently-shaped payload for this field via the SDK's generic consolidatedMonitors parameter, not this typed representation.
	// +optional
	ConsolidatedMonitors []DTCPoolConsolidatedMonitorHealth `json:"consolidatedMonitors"` // atProvider
	// Aggregate health status of the pool.
	Health *DTCPoolHealth `json:"health,omitempty"` // atProvider
}

// DTCPoolSpec defines the desired state of DTCPool.
type DTCPoolSpec struct {
	xpv2.ClusterManagedResourceSpec `json:",inline"`

	// ForProvider holds the user-supplied parameters for this DTCPool.
	// +kubebuilder:validation:Required
	ForProvider DTCPoolParameters `json:"forProvider"`
}

// DTCPoolStatus defines the observed state of DTCPool.
type DTCPoolStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`

	// AtProvider holds the observed values from the Infoblox NIOS WAPI.
	// +optional
	AtProvider DTCPoolObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:storageversion
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,infobloxnios}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"

// DTCPool is the Cluster-scoped managed resource representing an Infoblox NIOS DTCPool.
type DTCPool struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   DTCPoolSpec   `json:"spec"`
	Status DTCPoolStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DTCPoolList contains a list of DTCPool.
type DTCPoolList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DTCPool `json:"items"`
}
