// Package report renders a model.Resource inventory into the Markdown
// document consumed by the reviewer and later phases
// (tools/openapi/inventory.md).
package report

import (
	"fmt"
	"io"
	"sort"
	"strings"
	"time"

	"github.com/crossplane-contrib/provider-infoblox-nios/tools/openapi/pkg/model"
)

const emDash = "—"

// Options controls report generation.
type Options struct {
	// GeneratedAt is stamped into the report header. Zero value uses
	// time.Now().
	GeneratedAt time.Time
	// SDKCommit is the pinned infoblox-go-client/v2 commit SHA the catalog
	// was derived from.
	SDKCommit string
	// PilotSlug is the recommended/confirmed pilot resource slug.
	PilotSlug string
	// ActionEndpoints lists imperative SDK methods that are not modeled as
	// managed resources.
	ActionEndpoints []model.ActionEndpoint
	// ProbeNote is a human-readable summary of the live API probing
	// outcome.
	ProbeNote string
}

// Write renders the full inventory report to w.
func Write(w io.Writer, resources []model.Resource, opts Options) error {
	generatedAt := opts.GeneratedAt
	if generatedAt.IsZero() {
		generatedAt = time.Now().UTC()
	}

	sorted := make([]model.Resource, len(resources))
	copy(sorted, resources)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Slug < sorted[j].Slug })

	b := &strings.Builder{}

	fmt.Fprintf(b, "# Infoblox NIOS Provider — Resource Inventory\n\n")
	fmt.Fprintf(b, "> Generated: %s\n", generatedAt.Format(time.RFC3339))
	fmt.Fprintf(b, "> **This file is generated by the `tools/openapi` inventory tool (`go run ./tools/openapi/cmd/openapi-inventory inventory`). Do not edit by hand.**\n\n")
	fmt.Fprintf(b, "Infoblox NIOS does not publish an OpenAPI/Swagger specification for its WAPI ")
	fmt.Fprintf(b, "(input format `rest-nospec-sdk`). This inventory was built from:\n\n")
	fmt.Fprintf(b, "- The official Go SDK, `github.com/infobloxopen/infoblox-go-client/v2`")
	if opts.SDKCommit != "" {
		fmt.Fprintf(b, " (pinned at commit `%s` — see `tools/openapi/specs/infobloxopen/infoblox-go-client/README.md`)", opts.SDKCommit)
	}
	fmt.Fprintf(b, "\n")
	fmt.Fprintf(b, "- Live API probing against a real NIOS Grid Manager appliance\n")
	fmt.Fprintf(b, "- The reference Terraform provider, `github.com/infobloxopen/terraform-provider-infoblox`, for naming conventions (note: this provider does NOT use `ForceNew` schema tags anywhere — immutability below is derived by diffing each SDK method's Create vs. Update parameter list instead)\n\n")

	if opts.ProbeNote != "" {
		fmt.Fprintf(b, "## Live API Probing\n\n%s\n\n", opts.ProbeNote)
	}

	writeMethodology(b)
	writePilotSection(b, sorted, opts.PilotSlug)
	writeSummaryTable(b, sorted)
	writeExternalNameTable(b, sorted)
	writeImmutableFieldsTable(b, sorted)
	writeConnectionDetailsTable(b, sorted)
	writeCrossReferenceTable(b, sorted)
	writeNonStandardCRUDSection(b, sorted)
	writeActionEndpoints(b, opts.ActionEndpoints)
	writeDetailedCatalog(b, sorted)

	_, err := io.WriteString(w, b.String())
	return err
}

func writeMethodology(b *strings.Builder) {
	fmt.Fprintf(b, "## Methodology\n\n")
	fmt.Fprintf(b, "Only WAPI object types reachable through the SDK's `IBObjectManager` interface ")
	fmt.Fprintf(b, "(typed `Create<Resource>`/`Get<Resource>`/`Update<Resource>`/`Delete<Resource>` methods) ")
	fmt.Fprintf(b, "are cataloged as managed resources. The full WAPI schema defines several hundred ")
	fmt.Fprintf(b, "additional object types (grid configuration, member management, RPZ feeds, etc.) that ")
	fmt.Fprintf(b, "the SDK does not wrap with typed convenience methods — those would require raw ")
	fmt.Fprintf(b, "`Connector.CreateObject`/`GetObject`/`UpdateObject`/`DeleteObject` calls with hand-built ")
	fmt.Fprintf(b, "field maps, a materially different implementation shape, and are out of scope.\n\n")
	fmt.Fprintf(b, "For each cataloged resource, the **Fields** table lists only the fields exposed through ")
	fmt.Fprintf(b, "the SDK's Create/Update wrapper methods plus the resource's key response-only fields. ")
	fmt.Fprintf(b, "Several resources' full WAPI object model (as generated in `objects_generated.go`) expose ")
	fmt.Fprintf(b, "dozens of additional fields not reachable through any ObjectManager method — these are ")
	fmt.Fprintf(b, "called out per-resource under **Full Schema Notes** and require the generic Connector to set.\n\n")
	fmt.Fprintf(b, "**Immutability** is derived by diffing each resource's `Create<Resource>` method parameter ")
	fmt.Fprintf(b, "list against its `Update<Resource>` method parameter list: a parameter present in Create but ")
	fmt.Fprintf(b, "absent from Update means the SDK provides no way to change that value after creation. This ")
	fmt.Fprintf(b, "replaces the usual Terraform `ForceNew` cross-reference, since the reference Terraform ")
	fmt.Fprintf(b, "provider does not use `ForceNew` tags anywhere in its schema.\n\n")
}

func writePilotSection(b *strings.Builder, resources []model.Resource, pilotSlug string) {
	fmt.Fprintf(b, "## Pilot Resource\n\n")
	if pilotSlug == "" {
		fmt.Fprintf(b, "No pilot slug was supplied to the report generator.\n\n")
		return
	}
	for _, r := range resources {
		if r.Slug != pilotSlug {
			continue
		}
		fmt.Fprintf(b, "**Confirmed pilot: %s** (`%s`) — WAPI object type `%s`, pattern `%s`, ", r.Kind, r.Slug, r.WAPIObjectType, r.Pattern)
		fmt.Fprintf(b, "external-name strategy `%s`, full CRUD via the SDK wrapper: %s, live-verified: %s.\n\n",
			r.ExternalNameStrategy, yesNo(r.HasFullCRUD()), yesNo(r.LiveVerified))
		if r.LiveNotes != "" {
			fmt.Fprintf(b, "%s\n\n", r.LiveNotes)
		}
		return
	}
	fmt.Fprintf(b, "**WARNING:** pilot slug %q was NOT found among the analyzed resources. The pilot choice needs re-evaluation against an alternative candidate.\n\n", pilotSlug)
}

func writeSummaryTable(b *strings.Builder, resources []model.Resource) {
	fmt.Fprintf(b, "## Resource Summary Table\n\n")
	fmt.Fprintf(b, "| Kind | Slug | WAPI Object Type | Pattern | Fields (req/resp/both) | Update Method | Delete Behavior | Live Verified |\n")
	fmt.Fprintf(b, "|------|------|-------------------|---------|------------------------|----------------|------------------|---------------|\n")
	for _, r := range resources {
		req, resp, both := r.FieldCounts()
		update := r.UpdateMethod()
		if update == "" {
			update = "none"
		}
		wapiType := r.WAPIObjectType
		if wapiType == "" {
			wapiType = "(runtime-selected)"
		}
		fmt.Fprintf(b, "| %s | `%s` | `%s` | %s | %d/%d/%d | %s | %s | %s |\n",
			r.Kind, r.Slug, wapiType, r.Pattern, req, resp, both, update, r.DeleteBehavior, yesNo(r.LiveVerified))
	}
	fmt.Fprintf(b, "\n")
}

func writeExternalNameTable(b *strings.Builder, resources []model.Resource) {
	fmt.Fprintf(b, "## External-Name Strategy Table (§7.13)\n\n")
	fmt.Fprintf(b, "Every NIOS object uses the same strategy — a server-assigned opaque `_ref` — because ")
	fmt.Fprintf(b, "WAPI never exposes a stable user-supplied identifier that survives a rename.\n\n")
	fmt.Fprintf(b, "| Resource | Strategy | External Name Source | Rationale |\n")
	fmt.Fprintf(b, "|----------|----------|----------------------|-----------|\n")
	for _, r := range resources {
		fmt.Fprintf(b, "| %s | %s | `%s` | %s |\n", r.Kind, r.ExternalNameStrategy, r.ExternalNameSourcePath, escapePipes(r.ExternalNameRationale))
	}
	fmt.Fprintf(b, "\n")
}

func writeImmutableFieldsTable(b *strings.Builder, resources []model.Resource) {
	fmt.Fprintf(b, "## Immutable Fields Table (§7.14)\n\n")
	fmt.Fprintf(b, "| Resource | Immutable Fields | Evidence |\n")
	fmt.Fprintf(b, "|----------|-------------------|----------|\n")
	for _, r := range resources {
		immutable := "none known"
		if len(r.ImmutableFields) > 0 {
			immutable = "`" + strings.Join(r.ImmutableFields, "`, `") + "`"
		}
		fmt.Fprintf(b, "| %s | %s | Create<->Update SDK parameter diff |\n", r.Kind, immutable)
	}
	fmt.Fprintf(b, "\n")
}

func writeConnectionDetailsTable(b *strings.Builder, resources []model.Resource) {
	fmt.Fprintf(b, "## Connection Details (§7.16)\n\n")
	hasAny := false
	fmt.Fprintf(b, "| Resource | Key | Source Field | Availability | Notes |\n")
	fmt.Fprintf(b, "|----------|-----|---------------|--------------|-------|\n")
	for _, r := range resources {
		for _, cd := range r.ConnectionDetails {
			hasAny = true
			fmt.Fprintf(b, "| %s | `%s` | `%s` | %s | %s |\n", r.Kind, cd.Key, cd.SourceField, cd.Availability, escapePipes(cd.Notes))
		}
	}
	if !hasAny {
		fmt.Fprintf(b, "| _(none identified)_ | | | | |\n\n")
		fmt.Fprintf(b, "No NIOS resource in this catalog returns secret/credential/token-shaped fields. ")
		fmt.Fprintf(b, "WAPI Basic Auth credentials are provider-config-level (host/username/password), not ")
		fmt.Fprintf(b, "per-resource outputs.\n")
	}
	fmt.Fprintf(b, "\n")
}

func writeCrossReferenceTable(b *strings.Builder, resources []model.Resource) {
	fmt.Fprintf(b, "## Cross-Resource References (§7.17)\n\n")
	fmt.Fprintf(b, "| Source Resource | Field Path | Target Resource | Target Scope | Extractor | Compound |\n")
	fmt.Fprintf(b, "|------------------|------------|------------------|---------------|-----------|----------|\n")
	hasAny := false
	for _, r := range resources {
		for _, cr := range r.CrossReferences {
			hasAny = true
			fmt.Fprintf(b, "| %s | `%s` | %s | %s | %s | %s |\n", r.Kind, cr.FieldPath, cr.TargetKind, cr.TargetScope, cr.Extractor, yesNo(cr.Compound))
		}
	}
	if !hasAny {
		fmt.Fprintf(b, "| _(none identified)_ | | | | | |\n")
	}
	fmt.Fprintf(b, "\n")
}

func writeNonStandardCRUDSection(b *strings.Builder, resources []model.Resource) {
	fmt.Fprintf(b, "## Non-Standard CRUD Patterns\n\n")
	fmt.Fprintf(b, "Resources whose SDK wrapper deviates from the uniform Create/Get/Update/Delete naming ")
	fmt.Fprintf(b, "and coverage pattern:\n\n")
	any := false
	for _, r := range resources {
		if r.HasFullCRUD() && crudNamesStandard(r) {
			continue
		}
		any = true
		fmt.Fprintf(b, "- **%s**: %s\n", r.Kind, escapePipes(r.Notes))
	}
	if !any {
		fmt.Fprintf(b, "_(none — every resource above has full Create/Read/Update/Delete via the SDK wrapper with conventionally-named methods)_\n")
	}
	fmt.Fprintf(b, "\n")
}

// crudNamesStandard reports whether every CRUD method name for r follows the
// Create<Resource>/Get<Resource>/Update<Resource>/Delete<Resource> naming
// convention (heuristic: starts with the expected verb).
func crudNamesStandard(r model.Resource) bool {
	for _, m := range r.CRUD {
		switch m.Operation {
		case "Create":
			if !strings.HasPrefix(m.Method, "Create") {
				return false
			}
		case "Update":
			if !strings.HasPrefix(m.Method, "Update") {
				return false
			}
		case "Delete":
			if !strings.HasPrefix(m.Method, "Delete") {
				return false
			}
		}
	}
	return true
}

func writeActionEndpoints(b *strings.Builder, actions []model.ActionEndpoint) {
	fmt.Fprintf(b, "## Sub-Resource / Action Endpoints\n\n")
	fmt.Fprintf(b, "SDK methods that perform an imperative operation rather than CRUD on a single object ")
	fmt.Fprintf(b, "type. These are NOT modeled as managed resources — recorded here for completeness and ")
	fmt.Fprintf(b, "later controller-design reference.\n\n")
	if len(actions) == 0 {
		fmt.Fprintf(b, "_(none discovered)_\n\n")
		return
	}
	fmt.Fprintf(b, "| Method | Notes |\n")
	fmt.Fprintf(b, "|--------|-------|\n")
	for _, a := range actions {
		fmt.Fprintf(b, "| `%s` | %s |\n", a.Method, escapePipes(a.Notes))
	}
	fmt.Fprintf(b, "\n")
}

func writeDetailedCatalog(b *strings.Builder, resources []model.Resource) {
	fmt.Fprintf(b, "---\n\n## Detailed Resource Catalog\n\n")
	for _, r := range resources {
		writeResourceDetail(b, r)
	}
}

func writeResourceDetail(b *strings.Builder, r model.Resource) {
	writeResourceHeader(b, r)
	writeResourceCRUDMethods(b, r)
	writeResourceFields(b, r)
	writeResourceOptionalSections(b, r)
	fmt.Fprintf(b, "---\n\n")
}

func writeResourceHeader(b *strings.Builder, r model.Resource) {
	fmt.Fprintf(b, "### %s\n\n", r.Kind)
	fmt.Fprintf(b, "**Slug:** `%s`  \n", r.Slug)
	wapiType := r.WAPIObjectType
	if wapiType == "" {
		wapiType = "(runtime-selected — see notes)"
	}
	fmt.Fprintf(b, "**WAPI object type:** `%s`  \n", wapiType)
	if r.WAPIObjectTypeNotes != "" {
		fmt.Fprintf(b, "**WAPI object type notes:** %s  \n", r.WAPIObjectTypeNotes)
	}
	fmt.Fprintf(b, "**SDK struct:** `%s`  \n", r.GoStructName)
	fmt.Fprintf(b, "**Pattern:** %s  \n", r.Pattern)
	fmt.Fprintf(b, "**External-name strategy:** %s (`%s`)  \n", r.ExternalNameStrategy, r.ExternalNameSourcePath)
	fmt.Fprintf(b, "**Rationale:** %s  \n", r.ExternalNameRationale)
	fmt.Fprintf(b, "**Delete behavior:** %s  \n", r.DeleteBehavior)
	fmt.Fprintf(b, "**Update method:** %s  \n", orNone(r.UpdateMethod()))
	fmt.Fprintf(b, "**Live-verified:** %s  \n", yesNo(r.LiveVerified))
	if r.Notes != "" {
		fmt.Fprintf(b, "**Notes:** %s  \n", r.Notes)
	}
	fmt.Fprintf(b, "\n")
}

func writeResourceCRUDMethods(b *strings.Builder, r model.Resource) {
	fmt.Fprintf(b, "#### CRUD Methods\n\n")
	fmt.Fprintf(b, "| Operation | Go Method | Receiver | Notes |\n")
	fmt.Fprintf(b, "|-----------|-----------|----------|-------|\n")
	for _, m := range r.CRUD {
		fmt.Fprintf(b, "| %s | `%s` | %s | %s |\n", m.Operation, m.Method, m.Receiver, escapePipes(m.Notes))
	}
	fmt.Fprintf(b, "\n")
}

func writeResourceFields(b *strings.Builder, r model.Resource) {
	req, resp, both := r.FieldCounts()
	fmt.Fprintf(b, "#### Fields (request=%d, response=%d, both=%d)\n\n", req, resp, both)
	fmt.Fprintf(b, "| Name | Go Type | Scope | Required | Immutable | Enum | Description |\n")
	fmt.Fprintf(b, "|------|---------|-------|----------|-----------|------|-------------|\n")
	for _, field := range r.Fields {
		enum := emDash
		if len(field.Enum) > 0 {
			enum = strings.Join(field.Enum, ", ")
		}
		fmt.Fprintf(b, "| `%s` | `%s` | %s | %s | %s | %s | %s |\n",
			field.JSONName, field.GoType, field.Scope, yesNo(field.Required), yesNo(field.Immutable), enum, escapePipes(field.Description))
	}
	fmt.Fprintf(b, "\n")

	if r.FullSchemaNotes != "" {
		fmt.Fprintf(b, "#### Full Schema Notes\n\n%s\n\n", r.FullSchemaNotes)
	}
}

// writeResourceOptionalSections renders the sections that only appear when
// the corresponding data is present (connection details, cross-references,
// undocumented fields, live-verification notes).
func writeResourceOptionalSections(b *strings.Builder, r model.Resource) {
	if len(r.ConnectionDetails) > 0 {
		fmt.Fprintf(b, "#### Connection Details\n\n")
		fmt.Fprintf(b, "| Key | Source Field | Availability | Notes |\n")
		fmt.Fprintf(b, "|-----|---------------|--------------|-------|\n")
		for _, cd := range r.ConnectionDetails {
			fmt.Fprintf(b, "| `%s` | `%s` | %s | %s |\n", cd.Key, cd.SourceField, cd.Availability, escapePipes(cd.Notes))
		}
		fmt.Fprintf(b, "\n")
	}

	if len(r.CrossReferences) > 0 {
		fmt.Fprintf(b, "#### Cross-Resource References\n\n")
		fmt.Fprintf(b, "| Field Path | Target Resource | Target Scope | Extractor | Compound | Notes |\n")
		fmt.Fprintf(b, "|------------|------------------|---------------|-----------|----------|-------|\n")
		for _, cr := range r.CrossReferences {
			fmt.Fprintf(b, "| `%s` | %s | %s | %s | %s | %s |\n", cr.FieldPath, cr.TargetKind, cr.TargetScope, cr.Extractor, yesNo(cr.Compound), escapePipes(cr.Notes))
		}
		fmt.Fprintf(b, "\n")
	}

	if len(r.UndocumentedFields) > 0 {
		fmt.Fprintf(b, "#### Undocumented Fields (live-verified)\n\n")
		for _, uf := range r.UndocumentedFields {
			fmt.Fprintf(b, "- `%s`\n", uf)
		}
		fmt.Fprintf(b, "\n")
	}

	if r.LiveVerified || r.LiveNotes != "" {
		fmt.Fprintf(b, "#### API Behavior (live-verified)\n\n")
		fmt.Fprintf(b, "- **Delete behavior:** %s\n", r.DeleteBehavior)
		if r.LiveNotes != "" {
			fmt.Fprintf(b, "- **Notes:** %s\n", r.LiveNotes)
		}
		fmt.Fprintf(b, "\n")
	}
}

func orNone(s string) string {
	if s == "" {
		return "none"
	}
	return s
}

func yesNo(v bool) string {
	if v {
		return "yes"
	}
	return "no"
}

func escapePipes(s string) string {
	if s == "" {
		return emDash
	}
	return strings.ReplaceAll(strings.ReplaceAll(s, "\n", " "), "|", "\\|")
}
