//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FixedAddress) DeepCopyInto(out *FixedAddress) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FixedAddress.
func (in *FixedAddress) DeepCopy() *FixedAddress {
	if in == nil {
		return nil
	}
	out := new(FixedAddress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FixedAddress) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FixedAddressCloudInfo) DeepCopyInto(out *FixedAddressCloudInfo) {
	*out = *in
	if in.DelegatedMember != nil {
		in, out := &in.DelegatedMember, &out.DelegatedMember
		*out = new(FixedAddressCloudInfoDelegatedMember)
		(*in).DeepCopyInto(*out)
	}
	if in.DelegatedScope != nil {
		in, out := &in.DelegatedScope, &out.DelegatedScope
		*out = new(string)
		**out = **in
	}
	if in.DelegatedRoot != nil {
		in, out := &in.DelegatedRoot, &out.DelegatedRoot
		*out = new(string)
		**out = **in
	}
	if in.OwnedByAdaptor != nil {
		in, out := &in.OwnedByAdaptor, &out.OwnedByAdaptor
		*out = new(bool)
		**out = **in
	}
	if in.Usage != nil {
		in, out := &in.Usage, &out.Usage
		*out = new(string)
		**out = **in
	}
	if in.Tenant != nil {
		in, out := &in.Tenant, &out.Tenant
		*out = new(string)
		**out = **in
	}
	if in.MgmtPlatform != nil {
		in, out := &in.MgmtPlatform, &out.MgmtPlatform
		*out = new(string)
		**out = **in
	}
	if in.AuthorityType != nil {
		in, out := &in.AuthorityType, &out.AuthorityType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FixedAddressCloudInfo.
func (in *FixedAddressCloudInfo) DeepCopy() *FixedAddressCloudInfo {
	if in == nil {
		return nil
	}
	out := new(FixedAddressCloudInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FixedAddressCloudInfoDelegatedMember) DeepCopyInto(out *FixedAddressCloudInfoDelegatedMember) {
	*out = *in
	if in.Ipv4Addr != nil {
		in, out := &in.Ipv4Addr, &out.Ipv4Addr
		*out = new(string)
		**out = **in
	}
	if in.Ipv6Addr != nil {
		in, out := &in.Ipv6Addr, &out.Ipv6Addr
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FixedAddressCloudInfoDelegatedMember.
func (in *FixedAddressCloudInfoDelegatedMember) DeepCopy() *FixedAddressCloudInfoDelegatedMember {
	if in == nil {
		return nil
	}
	out := new(FixedAddressCloudInfoDelegatedMember)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FixedAddressDhcpOption) DeepCopyInto(out *FixedAddressDhcpOption) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Num != nil {
		in, out := &in.Num, &out.Num
		*out = new(int64)
		**out = **in
	}
	if in.VendorClass != nil {
		in, out := &in.VendorClass, &out.VendorClass
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
	if in.UseOption != nil {
		in, out := &in.UseOption, &out.UseOption
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FixedAddressDhcpOption.
func (in *FixedAddressDhcpOption) DeepCopy() *FixedAddressDhcpOption {
	if in == nil {
		return nil
	}
	out := new(FixedAddressDhcpOption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FixedAddressList) DeepCopyInto(out *FixedAddressList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FixedAddress, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FixedAddressList.
func (in *FixedAddressList) DeepCopy() *FixedAddressList {
	if in == nil {
		return nil
	}
	out := new(FixedAddressList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FixedAddressList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FixedAddressObservation) DeepCopyInto(out *FixedAddressObservation) {
	*out = *in
	if in.IPv4Addr != nil {
		in, out := &in.IPv4Addr, &out.IPv4Addr
		*out = new(string)
		**out = **in
	}
	if in.IPv6Addr != nil {
		in, out := &in.IPv6Addr, &out.IPv6Addr
		*out = new(string)
		**out = **in
	}
	if in.MAC != nil {
		in, out := &in.MAC, &out.MAC
		*out = new(string)
		**out = **in
	}
	if in.NetworkView != nil {
		in, out := &in.NetworkView, &out.NetworkView
		*out = new(string)
		**out = **in
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.MatchClient != nil {
		in, out := &in.MatchClient, &out.MatchClient
		*out = new(string)
		**out = **in
	}
	if in.Comment != nil {
		in, out := &in.Comment, &out.Comment
		*out = new(string)
		**out = **in
	}
	if in.ExtAttrs != nil {
		in, out := &in.ExtAttrs, &out.ExtAttrs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Disable != nil {
		in, out := &in.Disable, &out.Disable
		*out = new(bool)
		**out = **in
	}
	if in.AgentCircuitID != nil {
		in, out := &in.AgentCircuitID, &out.AgentCircuitID
		*out = new(string)
		**out = **in
	}
	if in.AgentRemoteID != nil {
		in, out := &in.AgentRemoteID, &out.AgentRemoteID
		*out = new(string)
		**out = **in
	}
	if in.ClientIdentifierPrependZero != nil {
		in, out := &in.ClientIdentifierPrependZero, &out.ClientIdentifierPrependZero
		*out = new(bool)
		**out = **in
	}
	if in.DHCPClientIdentifier != nil {
		in, out := &in.DHCPClientIdentifier, &out.DHCPClientIdentifier
		*out = new(string)
		**out = **in
	}
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make([]*FixedAddressDhcpOption, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(FixedAddressDhcpOption)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.UseOptions != nil {
		in, out := &in.UseOptions, &out.UseOptions
		*out = new(bool)
		**out = **in
	}
	if in.Ref != nil {
		in, out := &in.Ref, &out.Ref
		*out = new(string)
		**out = **in
	}
	if in.DUID != nil {
		in, out := &in.DUID, &out.DUID
		*out = new(string)
		**out = **in
	}
	if in.CloudInfo != nil {
		in, out := &in.CloudInfo, &out.CloudInfo
		*out = new(FixedAddressCloudInfo)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FixedAddressObservation.
func (in *FixedAddressObservation) DeepCopy() *FixedAddressObservation {
	if in == nil {
		return nil
	}
	out := new(FixedAddressObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FixedAddressParameters) DeepCopyInto(out *FixedAddressParameters) {
	*out = *in
	if in.IPv4Addr != nil {
		in, out := &in.IPv4Addr, &out.IPv4Addr
		*out = new(string)
		**out = **in
	}
	if in.IPv6Addr != nil {
		in, out := &in.IPv6Addr, &out.IPv6Addr
		*out = new(string)
		**out = **in
	}
	if in.MAC != nil {
		in, out := &in.MAC, &out.MAC
		*out = new(string)
		**out = **in
	}
	if in.NetworkView != nil {
		in, out := &in.NetworkView, &out.NetworkView
		*out = new(string)
		**out = **in
	}
	if in.NetworkViewRef != nil {
		in, out := &in.NetworkViewRef, &out.NetworkViewRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.NetworkViewSelector != nil {
		in, out := &in.NetworkViewSelector, &out.NetworkViewSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.MatchClient != nil {
		in, out := &in.MatchClient, &out.MatchClient
		*out = new(string)
		**out = **in
	}
	if in.Comment != nil {
		in, out := &in.Comment, &out.Comment
		*out = new(string)
		**out = **in
	}
	if in.ExtAttrs != nil {
		in, out := &in.ExtAttrs, &out.ExtAttrs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Disable != nil {
		in, out := &in.Disable, &out.Disable
		*out = new(bool)
		**out = **in
	}
	if in.AgentCircuitID != nil {
		in, out := &in.AgentCircuitID, &out.AgentCircuitID
		*out = new(string)
		**out = **in
	}
	if in.AgentRemoteID != nil {
		in, out := &in.AgentRemoteID, &out.AgentRemoteID
		*out = new(string)
		**out = **in
	}
	if in.ClientIdentifierPrependZero != nil {
		in, out := &in.ClientIdentifierPrependZero, &out.ClientIdentifierPrependZero
		*out = new(bool)
		**out = **in
	}
	if in.DHCPClientIdentifier != nil {
		in, out := &in.DHCPClientIdentifier, &out.DHCPClientIdentifier
		*out = new(string)
		**out = **in
	}
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make([]*FixedAddressDhcpOption, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(FixedAddressDhcpOption)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.UseOptions != nil {
		in, out := &in.UseOptions, &out.UseOptions
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FixedAddressParameters.
func (in *FixedAddressParameters) DeepCopy() *FixedAddressParameters {
	if in == nil {
		return nil
	}
	out := new(FixedAddressParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FixedAddressSpec) DeepCopyInto(out *FixedAddressSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FixedAddressSpec.
func (in *FixedAddressSpec) DeepCopy() *FixedAddressSpec {
	if in == nil {
		return nil
	}
	out := new(FixedAddressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FixedAddressStatus) DeepCopyInto(out *FixedAddressStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FixedAddressStatus.
func (in *FixedAddressStatus) DeepCopy() *FixedAddressStatus {
	if in == nil {
		return nil
	}
	out := new(FixedAddressStatus)
	in.DeepCopyInto(out)
	return out
}
