// Code generated by openapi2crd. DO NOT EDIT.

// Package zonedelegated contains a standalone reference copy of the Parameters
// and Observation types for the ZoneDelegated managed resource. The
// cluster-scoped and namespaced variants (apis/cluster/zonedelegated/,
// apis/namespaced/zonedelegated/) generate self-contained copies of these same
// types rather than importing this package — see the openapi2crd/pkg/
// generator package doc comment for the rationale.
package zonedelegated

// ZoneDelegatedNameServer identifies one remote name server a delegated zone forwards queries to (mirrors the SDK's NameServer struct).
type ZoneDelegatedNameServer struct {
	// A resolvable domain name for the external DNS server.
	Name *string `json:"name,omitempty"`
	// The IPv4 Address or IPv6 Address of the server.
	Address *string `json:"address,omitempty"`
}

// ZoneDelegatedParameters are the configurable fields of a ZoneDelegated.
type ZoneDelegatedParameters struct {
	// FQDN of the delegated zone. Fixed at creation — confirmed absent from the UpdateZoneDelegated SDK method signature.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="fqdn is immutable after creation"
	Fqdn *string `json:"fqdn"`
	// List of remote name servers the zone is delegated to. The Infoblox appliance redirects queries for the delegated zone to these servers.
	// +kubebuilder:validation:Required
	DelegateTo []ZoneDelegatedNameServer `json:"delegateTo"`
	// DNS view in which the zone resides, e.g. "external". Fixed at creation — confirmed absent from the UpdateZoneDelegated SDK method signature. The WAPI additionally rejects moving an existing zone between views at the data level.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="view is immutable after creation"
	View *string `json:"view,omitempty"`
	// Format of the zone (e.g. FORWARD, IPV4, IPV6). Fixed at creation — confirmed absent from the UpdateZoneDelegated SDK method signature.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="zoneFormat is immutable after creation"
	ZoneFormat *string `json:"zoneFormat,omitempty"`
	// Comment for the zone; maximum 256 characters.
	Comment *string `json:"comment,omitempty"`
	// Determines whether the zone is disabled. When false, the zone is enabled.
	Disable *bool `json:"disable,omitempty"`
	// If set, other administrators cannot make conflicting changes to this zone. The zone continues to serve DNS data while locked.
	Locked *bool `json:"locked,omitempty"`
	// Delegation name server group bound to this delegated zone.
	NsGroup *string `json:"nsGroup,omitempty"`
	// Time-to-live, in seconds, of the auto-generated NS and glue records for this delegation. Must be non-negative (0-2147483647); to inherit the zone/grid default, set useDelegatedTtl to false rather than passing a negative sentinel value.
	// +kubebuilder:validation:Minimum=0
	// +kubebuilder:validation:Maximum=2147483647
	DelegatedTTL *uint32 `json:"delegatedTtl,omitempty"`
	// Use flag for delegatedTtl — when false the zone/grid default TTL applies.
	UseDelegatedTTL *bool `json:"useDelegatedTtl,omitempty"`
	// Extensible attributes (arbitrary key/value metadata defined in Grid Manager). The WAPI wire format wraps each value as {"value": ...}; this map is the simplified string-valued CRD representation (the controller translates to/from the SDK's EA map[string]interface{} type).
	// +optional
	ExtAttrs map[string]string `json:"extAttrs"`
}

// ZoneDelegatedObservation holds the observed state of a ZoneDelegated.
// It mirrors every ZoneDelegatedParameters field plus response-only fields
// (full-mirror AtProvider) so users can compare forProvider to
// atProvider before switching to full management
// (managementPolicies: ["Observe"]).
type ZoneDelegatedObservation struct {
	// Server-assigned external identifier for this resource, set by Observe()
	// from the resource's external name. Used by import testing to confirm
	// the controller re-discovers the resource after a restart.
	// +optional
	ID string `json:"id,omitempty"` // atProvider
	// FQDN of the delegated zone. Fixed at creation — confirmed absent from the UpdateZoneDelegated SDK method signature.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="fqdn is immutable after creation"
	Fqdn *string `json:"fqdn,omitempty"` // atProvider
	// List of remote name servers the zone is delegated to. The Infoblox appliance redirects queries for the delegated zone to these servers.
	// +optional
	DelegateTo []ZoneDelegatedNameServer `json:"delegateTo"` // atProvider
	// DNS view in which the zone resides, e.g. "external". Fixed at creation — confirmed absent from the UpdateZoneDelegated SDK method signature. The WAPI additionally rejects moving an existing zone between views at the data level.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="view is immutable after creation"
	View *string `json:"view,omitempty"` // atProvider
	// Format of the zone (e.g. FORWARD, IPV4, IPV6). Fixed at creation — confirmed absent from the UpdateZoneDelegated SDK method signature.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="zoneFormat is immutable after creation"
	ZoneFormat *string `json:"zoneFormat,omitempty"` // atProvider
	// Comment for the zone; maximum 256 characters.
	Comment *string `json:"comment,omitempty"` // atProvider
	// Determines whether the zone is disabled. When false, the zone is enabled.
	Disable *bool `json:"disable,omitempty"` // atProvider
	// If set, other administrators cannot make conflicting changes to this zone. The zone continues to serve DNS data while locked.
	Locked *bool `json:"locked,omitempty"` // atProvider
	// Delegation name server group bound to this delegated zone.
	NsGroup *string `json:"nsGroup,omitempty"` // atProvider
	// Time-to-live, in seconds, of the auto-generated NS and glue records for this delegation. Must be non-negative (0-2147483647); to inherit the zone/grid default, set useDelegatedTtl to false rather than passing a negative sentinel value.
	DelegatedTTL *uint32 `json:"delegatedTtl,omitempty"` // atProvider
	// Use flag for delegatedTtl — when false the zone/grid default TTL applies.
	UseDelegatedTTL *bool `json:"useDelegatedTtl,omitempty"` // atProvider
	// Extensible attributes (arbitrary key/value metadata defined in Grid Manager). The WAPI wire format wraps each value as {"value": ...}; this map is the simplified string-valued CRD representation (the controller translates to/from the SDK's EA map[string]interface{} type).
	// +optional
	ExtAttrs map[string]string `json:"extAttrs"` // atProvider
	// Server-assigned opaque object reference (WAPI `_ref`). Mirrors the crossplane.io/external-name annotation for observability and uptest import verification.
	Ref *string `json:"ref,omitempty"` // atProvider
}
