// Code generated by openapi2crd. DO NOT EDIT.

// Package v1alpha1 contains the Cluster-scoped NSRecord managed resource.
// API group: recordns.infobloxnios.crossplane.io
package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// NSRecordAddress identifies one glue name server address for an NSRecord (mirrors the SDK's ZoneNameServer struct).
type NSRecordAddress struct {
	// The address of the Zone Name Server.
	Address *string `json:"address,omitempty"`
	// Flag to indicate if PTR records need to be auto created.
	AutoCreatePtr *bool `json:"autoCreatePtr,omitempty"`
}

// NSRecordCloudInfo carries Cloud API delegation/ownership information for a cloud-managed NSRecord (mirrors the SDK's GridCloudapiInfo struct).
type NSRecordCloudInfo struct {
	// The Cloud Platform Appliance to which authority of the object is delegated.
	DelegatedMember *NSRecordCloudInfoDelegatedMember `json:"delegatedMember,omitempty"`
	// Indicates the scope of delegation for the object. This can be one of the following: NONE (outside any delegation), ROOT (the delegation point), SUBTREE (within the scope of a delegation), RECLAIMING (within the scope of a delegation being reclaimed, either as the delegation point or in the subtree).
	DelegatedScope *string `json:"delegatedScope,omitempty"`
	// Indicates the root of the delegation if delegated_scope is SUBTREE or RECLAIMING. This is not set otherwise.
	DelegatedRoot *string `json:"delegatedRoot,omitempty"`
	// Determines whether the object was created by the cloud adapter or not.
	OwnedByAdaptor *bool `json:"ownedByAdaptor,omitempty"`
	// Indicates the cloud origin of the object.
	Usage *string `json:"usage,omitempty"`
	// Reference to the tenant object associated with the object, if any.
	Tenant *string `json:"tenant,omitempty"`
	// Indicates the specified cloud management platform.
	MgmtPlatform *string `json:"mgmtPlatform,omitempty"`
	// Type of authority over the object.
	AuthorityType *string `json:"authorityType,omitempty"`
}

// NSRecordCloudInfoDelegatedMember identifies the Grid member an NSRecord's authority is delegated to (mirrors the SDK's Dhcpmember struct).
type NSRecordCloudInfoDelegatedMember struct {
	// The IPv4 Address of the Grid Member.
	Ipv4Addr *string `json:"ipv4addr,omitempty"`
	// The IPv6 Address of the Grid Member.
	Ipv6Addr *string `json:"ipv6addr,omitempty"`
	// The Grid member name
	Name *string `json:"name,omitempty"`
}

// NSRecordParameters are the configurable fields of a NSRecord.
type NSRecordParameters struct {
	// Name of the NS record in FQDN format (the delegated zone/subdomain). Live-verified immutable (`supports=rws`, no `u`) — WAPI rejects a PUT that changes this field even though the Go SDK's UpdateNSRecord signature still accepts a name parameter.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="name is immutable after creation"
	Name *string `json:"name"`
	// FQDN of the authoritative server for the redirected zone. WAPI allows this field to be updated in place, but the provider marks it immutable anyway: this object's server-assigned handle is derived from (view, name, nameserver), and it is the only one of those three components WAPI does not already reject an update for. Changing it in place would rotate the handle out from under the provider with no way to re-establish which live object the resource still refers to, so an apply that changes it is rejected by the API server and the existing record is left unchanged. An operator who needs a different name server replaces the resource deliberately.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="nameserver is immutable after creation"
	Nameserver *string `json:"nameserver"`
	// DNS view in which the record resides, e.g. "external". Fixed at creation — WAPI ties the record's _ref to (view, zone, name). Live-verified hard immutable (`supports=rws`, no `u`); the Go SDK already drops view from UpdateNSRecord's request body.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="view is immutable after creation"
	View *string `json:"view"`
	// Glue address records for the name server. Live-verified REQUIRED on create (`field for create missing: addresses`) — corrects inventory.md's "optional" classification.
	// +kubebuilder:validation:Required
	Addresses []NSRecordAddress `json:"addresses"`
	// MS delegation point name.
	MsDelegationName *string `json:"msDelegationName,omitempty"`
}

// NSRecordObservation holds the observed state of a NSRecord.
// It mirrors every NSRecordParameters field plus response-only fields
// (full-mirror AtProvider) so users can compare forProvider to
// atProvider before switching to full management
// (managementPolicies: ["Observe"]).
type NSRecordObservation struct {
	// Server-assigned external identifier for this resource, set by Observe()
	// from the resource's external name. Used by import testing to confirm
	// the controller re-discovers the resource after a restart.
	// +optional
	ID string `json:"id,omitempty"` // atProvider
	// Name of the NS record in FQDN format (the delegated zone/subdomain). Live-verified immutable (`supports=rws`, no `u`) — WAPI rejects a PUT that changes this field even though the Go SDK's UpdateNSRecord signature still accepts a name parameter.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="name is immutable after creation"
	Name *string `json:"name,omitempty"` // atProvider
	// FQDN of the authoritative server for the redirected zone. WAPI allows this field to be updated in place, but the provider marks it immutable anyway: this object's server-assigned handle is derived from (view, name, nameserver), and it is the only one of those three components WAPI does not already reject an update for. Changing it in place would rotate the handle out from under the provider with no way to re-establish which live object the resource still refers to, so an apply that changes it is rejected by the API server and the existing record is left unchanged. An operator who needs a different name server replaces the resource deliberately.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="nameserver is immutable after creation"
	Nameserver *string `json:"nameserver,omitempty"` // atProvider
	// DNS view in which the record resides, e.g. "external". Fixed at creation — WAPI ties the record's _ref to (view, zone, name). Live-verified hard immutable (`supports=rws`, no `u`); the Go SDK already drops view from UpdateNSRecord's request body.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="view is immutable after creation"
	View *string `json:"view,omitempty"` // atProvider
	// Glue address records for the name server. Live-verified REQUIRED on create (`field for create missing: addresses`) — corrects inventory.md's "optional" classification.
	// +optional
	Addresses []NSRecordAddress `json:"addresses"` // atProvider
	// MS delegation point name.
	MsDelegationName *string `json:"msDelegationName,omitempty"` // atProvider
	// Server-assigned opaque object reference (WAPI `_ref`). Mirrors the crossplane.io/external-name annotation for observability and uptest import verification.
	Ref *string `json:"ref,omitempty"` // atProvider
	// Zone in which the record resides, e.g. "zone.com". Derived from name/view by WAPI — not a CreateNSRecord parameter, so it has no ForProvider counterpart.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="zone is immutable after creation"
	Zone *string `json:"zone,omitempty"` // atProvider
	// Record creator. Live-verified read-only (`supports=rs`) — present on the RecordNS struct but omitted from inventory.md's static field table.
	Creator *string `json:"creator,omitempty"` // atProvider
	// Record name in punycode format (derived from name).
	DNSName *string `json:"dnsName,omitempty"` // atProvider
	// Time of the last DNS query for this record (Unix epoch seconds).
	LastQueried *int64 `json:"lastQueried,omitempty"` // atProvider
	// Cloud API related information for this object (cloud-managed records only).
	CloudInfo *NSRecordCloudInfo `json:"cloudInfo,omitempty"` // atProvider
	// Host name policy for the record.
	Policy *string `json:"policy,omitempty"` // atProvider
}

// NSRecordSpec defines the desired state of NSRecord.
type NSRecordSpec struct {
	xpv1.ResourceSpec `json:",inline"`

	// ForProvider holds the user-supplied parameters for this NSRecord.
	// +kubebuilder:validation:Required
	ForProvider NSRecordParameters `json:"forProvider"`
}

// NSRecordStatus defines the observed state of NSRecord.
type NSRecordStatus struct {
	xpv1.ResourceStatus `json:",inline"`

	// AtProvider holds the observed values from the Infoblox NIOS WAPI.
	// +optional
	AtProvider NSRecordObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:storageversion
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,infobloxnios}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"

// NSRecord is the Cluster-scoped managed resource representing an Infoblox NIOS NSRecord.
type NSRecord struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   NSRecordSpec   `json:"spec"`
	Status NSRecordStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NSRecordList contains a list of NSRecord.
type NSRecordList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NSRecord `json:"items"`
}
