// Code generated by openapi2crd. DO NOT EDIT.

// Package v1alpha1 contains the Namespaced-scoped ZoneAuth managed resource.
// API group: zoneauth.infobloxnios.m.crossplane.io
package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	xpv2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// MemberServer identifies a Grid member acting as a primary or secondary server for a zone (mirrors the SDK's Memberserver struct).
type MemberServer struct {
	// Grid member name.
	Name *string `json:"name,omitempty"`
	// Whether this Grid member is in stealth mode (its NS record is hidden from DNS queries).
	Stealth *bool `json:"stealth,omitempty"`
	// Whether zone data reaches this member via DNS zone transfer (true) or Grid replication (false).
	GridReplicate *bool `json:"gridReplicate,omitempty"`
	// Whether the Grid lead secondary performs zone transfers to non-lead secondaries.
	Lead *bool `json:"lead,omitempty"`
	// Primary preference list of Grid members and/or external servers for this member.
	// +optional
	PreferredPrimaries []ExternalServer `json:"preferredPrimaries"`
	// Whether preferredPrimaries is used for this member.
	EnablePreferredPrimaries *bool `json:"enablePreferredPrimaries,omitempty"`
}

// ExternalServer identifies an external (non-Grid) DNS server acting as a primary or secondary for a zone, or a preferred-primaries entry (mirrors the SDK's NameServer struct).
type ExternalServer struct {
	// IPv4 or IPv6 address of the server.
	Address *string `json:"address,omitempty"`
	// Resolvable domain name of the external DNS server.
	Name *string `json:"name,omitempty"`
	// Whether the NS record for this server is hidden from DNS queries.
	Stealth *bool `json:"stealth,omitempty"`
	// Whether this name server is shared with the parent Microsoft primary zone's delegation server.
	SharedWithMsParentDelegation *bool `json:"sharedWithMsParentDelegation,omitempty"`
	// Generated TSIG key.
	TsigKey *string `json:"tsigKey,omitempty"`
	// TSIG key algorithm.
	TsigKeyAlg *string `json:"tsigKeyAlg,omitempty"`
	// TSIG key name.
	TsigKeyName *string `json:"tsigKeyName,omitempty"`
	// Use flag for tsigKeyName.
	UseTsigKeyName *bool `json:"useTsigKeyName,omitempty"`
}

// ZoneAuthParameters are the configurable fields of a ZoneAuth.
type ZoneAuthParameters struct {
	// Fully-qualified domain name of the zone, e.g. "example.com". Immutable — WAPI rejects a PUT that changes it with "Field is not allowed for update".
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="fqdn is immutable after creation"
	FQDN *string `json:"fqdn"`
	// DNS view in which the zone resides, e.g. "external". Defaults to the Grid's default view if unset at creation. Immutable — WAPI rejects a PUT that changes it with "Cannot move zones between views".
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="view is immutable after creation"
	View *string `json:"view,omitempty"`
	// Format of the zone. Immutable — WAPI rejects a PUT that changes it with "Field is not allowed for update".
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="zoneFormat is immutable after creation"
	// +kubebuilder:validation:Enum=FORWARD;IPV4;IPV6
	ZoneFormat *string `json:"zoneFormat,omitempty"`
	// Comment for the zone; maximum 256 characters.
	Comment *string `json:"comment,omitempty"`
	// Determines whether the zone is disabled. When false, the zone is enabled.
	Disable *bool `json:"disable,omitempty"`
	// TTL (in seconds) of the SOA record of this zone — the length of time data from the zone is cached.
	SoaDefaultTTL *uint32 `json:"soaDefaultTtl,omitempty"`
	// Number of seconds after which a secondary server stops answering for the zone because its data is considered too old to be useful.
	SoaExpire *uint32 `json:"soaExpire,omitempty"`
	// Negative-caching TTL (in seconds) of the zone's SOA record — how long a secondary server caches "Does Not Respond" answers.
	SoaNegativeTTL *uint32 `json:"soaNegativeTtl,omitempty"`
	// Interval (in seconds) at which a secondary server checks the primary server for fresh zone data.
	SoaRefresh *uint32 `json:"soaRefresh,omitempty"`
	// Number of seconds a secondary server waits before retrying the primary server after a failed connection.
	SoaRetry *uint32 `json:"soaRetry,omitempty"`
	// Name server group that serves DNS for this zone.
	NsGroup *string `json:"nsGroup,omitempty"`
	// Extensible attributes (arbitrary key/value metadata defined in Grid Manager). The WAPI wire format wraps each value as {"value": ...}; this map is the simplified string-valued CRD representation (the controller translates to/from the SDK's EA map[string]interface{} type).
	// +optional
	ExtAttrs map[string]string `json:"extAttrs"`
	// Grid members that act as primary servers for this zone.
	// +optional
	GridPrimary []MemberServer `json:"gridPrimary"`
	// Grid members that act as secondary servers for this zone.
	// +optional
	GridSecondaries []MemberServer `json:"gridSecondaries"`
	// External (non-Grid) primary servers for this zone.
	// +optional
	ExternalPrimaries []ExternalServer `json:"externalPrimaries"`
	// External (non-Grid) secondary servers for this zone.
	// +optional
	ExternalSecondaries []ExternalServer `json:"externalSecondaries"`
}

// ZoneAuthObservation holds the observed state of a ZoneAuth.
// It mirrors every ZoneAuthParameters field plus response-only fields
// (full-mirror AtProvider) so users can compare forProvider to
// atProvider before switching to full management
// (managementPolicies: ["Observe"]).
type ZoneAuthObservation struct {
	// Server-assigned external identifier for this resource, set by Observe()
	// from the resource's external name. Used by import testing to confirm
	// the controller re-discovers the resource after a restart.
	// +optional
	ID string `json:"id,omitempty"` // atProvider
	// Fully-qualified domain name of the zone, e.g. "example.com". Immutable — WAPI rejects a PUT that changes it with "Field is not allowed for update".
	FQDN *string `json:"fqdn,omitempty"` // atProvider
	// DNS view in which the zone resides, e.g. "external". Defaults to the Grid's default view if unset at creation. Immutable — WAPI rejects a PUT that changes it with "Cannot move zones between views".
	View *string `json:"view,omitempty"` // atProvider
	// Format of the zone. Immutable — WAPI rejects a PUT that changes it with "Field is not allowed for update".
	ZoneFormat *string `json:"zoneFormat,omitempty"` // atProvider
	// Comment for the zone; maximum 256 characters.
	Comment *string `json:"comment,omitempty"` // atProvider
	// Determines whether the zone is disabled. When false, the zone is enabled.
	Disable *bool `json:"disable,omitempty"` // atProvider
	// TTL (in seconds) of the SOA record of this zone — the length of time data from the zone is cached.
	SoaDefaultTTL *uint32 `json:"soaDefaultTtl,omitempty"` // atProvider
	// Number of seconds after which a secondary server stops answering for the zone because its data is considered too old to be useful.
	SoaExpire *uint32 `json:"soaExpire,omitempty"` // atProvider
	// Negative-caching TTL (in seconds) of the zone's SOA record — how long a secondary server caches "Does Not Respond" answers.
	SoaNegativeTTL *uint32 `json:"soaNegativeTtl,omitempty"` // atProvider
	// Interval (in seconds) at which a secondary server checks the primary server for fresh zone data.
	SoaRefresh *uint32 `json:"soaRefresh,omitempty"` // atProvider
	// Number of seconds a secondary server waits before retrying the primary server after a failed connection.
	SoaRetry *uint32 `json:"soaRetry,omitempty"` // atProvider
	// Name server group that serves DNS for this zone.
	NsGroup *string `json:"nsGroup,omitempty"` // atProvider
	// Extensible attributes (arbitrary key/value metadata defined in Grid Manager). The WAPI wire format wraps each value as {"value": ...}; this map is the simplified string-valued CRD representation (the controller translates to/from the SDK's EA map[string]interface{} type).
	// +optional
	ExtAttrs map[string]string `json:"extAttrs"` // atProvider
	// Grid members that act as primary servers for this zone.
	// +optional
	GridPrimary []MemberServer `json:"gridPrimary"` // atProvider
	// Grid members that act as secondary servers for this zone.
	// +optional
	GridSecondaries []MemberServer `json:"gridSecondaries"` // atProvider
	// External (non-Grid) primary servers for this zone.
	// +optional
	ExternalPrimaries []ExternalServer `json:"externalPrimaries"` // atProvider
	// External (non-Grid) secondary servers for this zone.
	// +optional
	ExternalSecondaries []ExternalServer `json:"externalSecondaries"` // atProvider
	// Server-assigned opaque object reference (WAPI `_ref`). Mirrors the crossplane.io/external-name annotation for observability and uptest import verification. Stable across the resource's lifetime — every field it embeds (fqdn, view, zoneFormat) is immutable.
	Ref *string `json:"ref,omitempty"` // atProvider
}

// ZoneAuthSpec defines the desired state of ZoneAuth.
type ZoneAuthSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`

	// ForProvider holds the user-supplied parameters for this ZoneAuth.
	// +kubebuilder:validation:Required
	ForProvider ZoneAuthParameters `json:"forProvider"`
}

// ZoneAuthStatus defines the observed state of ZoneAuth.
type ZoneAuthStatus struct {
	xpv1.ResourceStatus `json:",inline"`

	// AtProvider holds the observed values from the Infoblox NIOS WAPI.
	// +optional
	AtProvider ZoneAuthObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:storageversion
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,infobloxnios}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"

// ZoneAuth is the Namespaced-scoped managed resource representing an Infoblox NIOS ZoneAuth.
type ZoneAuth struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ZoneAuthSpec   `json:"spec"`
	Status ZoneAuthStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ZoneAuthList contains a list of ZoneAuth.
type ZoneAuthList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ZoneAuth `json:"items"`
}
