// Code generated by openapi2crd. DO NOT EDIT.

// Package networkview contains a standalone reference copy of the Parameters
// and Observation types for the NetworkView managed resource. The
// cluster-scoped and namespaced variants (apis/cluster/networkview/,
// apis/namespaced/networkview/) generate self-contained copies of these same
// types rather than importing this package — see the openapi2crd/pkg/
// generator package doc comment for the rationale.
package networkview

// NetworkViewParameters are the configurable fields of a NetworkView.
type NetworkViewParameters struct {
	// Name of the network view. Mutable — UpdateNetworkView accepts a new name, but renaming changes the record's _ref.
	// +kubebuilder:validation:Required
	Name *string `json:"name"`
	// Comment for the network view; maximum 256 characters.
	Comment *string `json:"comment,omitempty"`
	// Extensible attributes (arbitrary key/value metadata defined in Grid Manager). The WAPI wire format wraps each value as {"value": ...}; this map is the simplified string-valued CRD representation (the controller translates to/from the SDK's EA map[string]interface{} type).
	// +optional
	// +kubebuilder:validation:XValidation:rule="self.all(k, k != 'Crossplane Internal ID')",message="the 'Crossplane Internal ID' extensible attribute is reserved for the provider's identity stamp and cannot be set in spec.forProvider.extAttrs"
	ExtAttrs map[string]string `json:"extAttrs"`
}

// NetworkViewObservation holds the observed state of a NetworkView.
// It mirrors every NetworkViewParameters field plus response-only fields
// (full-mirror AtProvider) so users can compare forProvider to
// atProvider before switching to full management
// (managementPolicies: ["Observe"]).
type NetworkViewObservation struct {
	// Server-assigned external identifier for this resource, set by Observe()
	// from the resource's external name. Used by import testing to confirm
	// the controller re-discovers the resource after a restart.
	// +optional
	ID string `json:"id,omitempty"` // atProvider
	// Name of the network view. Mutable — UpdateNetworkView accepts a new name, but renaming changes the record's _ref.
	Name *string `json:"name,omitempty"` // atProvider
	// Comment for the network view; maximum 256 characters.
	Comment *string `json:"comment,omitempty"` // atProvider
	// Extensible attributes (arbitrary key/value metadata defined in Grid Manager). The WAPI wire format wraps each value as {"value": ...}; this map is the simplified string-valued CRD representation (the controller translates to/from the SDK's EA map[string]interface{} type).
	// +optional
	ExtAttrs map[string]string `json:"extAttrs"` // atProvider
	// Server-assigned opaque object reference (WAPI `_ref`, e.g. `networkview/ZG5z...:default/true`). Mirrors the crossplane.io/external-name annotation for observability and uptest import verification.
	Ref *string `json:"ref,omitempty"` // atProvider
	// Whether this is the Grid's default network view. Exactly one exists per Grid and it cannot be deleted (live-verified: GET networkview always returns a `default` entry with is_default=true). Server-controlled — never a create/update parameter.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="isDefault is immutable after creation"
	IsDefault *bool `json:"isDefault,omitempty"` // atProvider
}
