// Code generated by openapi2crd. DO NOT EDIT.

// Package v1alpha1 contains the Cluster-scoped Network managed resource.
// API group: network.infobloxnios.crossplane.io
package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// NetworkMember is a Grid member DHCP-service assignment for a network. The underlying WAPI object is a union of a dhcpmember or msdhcpserver entry; at most one field group below is populated for a given entry.
type NetworkMember struct {
	// Grid member name serving DHCP for this network (dhcpmember entry).
	DhcpMemberName *string `json:"dhcpMemberName,omitempty"`
	// IPv4 address of the Grid member serving DHCP (dhcpmember entry).
	DhcpMemberIPv4Addr *string `json:"dhcpMemberIpv4Addr,omitempty"`
	// IPv6 address of the Grid member serving DHCP (dhcpmember entry).
	DhcpMemberIPv6Addr *string `json:"dhcpMemberIpv6Addr,omitempty"`
	// IPv4 address or FQDN of the Microsoft DHCP server (msdhcpserver entry).
	MsDhcpServerIPv4Addr *string `json:"msDhcpServerIpv4Addr,omitempty"`
}

// NetworkParameters are the configurable fields of a Network.
type NetworkParameters struct {
	// Network view the network belongs to, identified by NetworkView name. Fixed at creation — confirmed absent from the UpdateNetwork SDK method signature.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="networkView is immutable after creation"
	NetworkView *string `json:"networkView"`
	// CIDR of the network, e.g. "10.0.0.0/24" (IPv4) or an IPv6 CIDR. Fixed at creation — confirmed absent from the UpdateNetwork SDK method signature. The WAPI object type (network vs ipv6network) is selected at runtime from this value's format.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="network is immutable after creation"
	Network *string `json:"network"`
	// Comment for the network; maximum 256 characters.
	Comment *string `json:"comment,omitempty"`
	// Extensible attributes (arbitrary key/value metadata defined in Grid Manager). The WAPI wire format wraps each value as {"value": ...}; this map is the simplified string-valued CRD representation (the controller translates to/from the SDK's EA map[string]interface{} type).
	// +optional
	ExtAttrs map[string]string `json:"extAttrs"`
}

// NetworkObservation holds the observed state of a Network.
// It mirrors every NetworkParameters field plus response-only fields
// (full-mirror AtProvider) so users can compare forProvider to
// atProvider before switching to full management
// (managementPolicies: ["Observe"]).
type NetworkObservation struct {
	// Server-assigned external identifier for this resource, set by Observe()
	// from the resource's external name. Used by import testing to confirm
	// the controller re-discovers the resource after a restart.
	// +optional
	ID string `json:"id,omitempty"` // atProvider
	// Network view the network belongs to, identified by NetworkView name. Fixed at creation — confirmed absent from the UpdateNetwork SDK method signature.
	NetworkView *string `json:"networkView,omitempty"` // atProvider
	// CIDR of the network, e.g. "10.0.0.0/24" (IPv4) or an IPv6 CIDR. Fixed at creation — confirmed absent from the UpdateNetwork SDK method signature. The WAPI object type (network vs ipv6network) is selected at runtime from this value's format.
	Network *string `json:"network,omitempty"` // atProvider
	// Comment for the network; maximum 256 characters.
	Comment *string `json:"comment,omitempty"` // atProvider
	// Extensible attributes (arbitrary key/value metadata defined in Grid Manager). The WAPI wire format wraps each value as {"value": ...}; this map is the simplified string-valued CRD representation (the controller translates to/from the SDK's EA map[string]interface{} type).
	// +optional
	ExtAttrs map[string]string `json:"extAttrs"` // atProvider
	// Server-assigned opaque object reference (WAPI `_ref`). Mirrors the crossplane.io/external-name annotation for observability and uptest import verification.
	Ref *string `json:"ref,omitempty"` // atProvider
	// Grid members serving DHCP for this network. Populated on read; not settable via CreateNetwork/UpdateNetwork through the ObjectManager wrapper.
	// +optional
	Members []NetworkMember `json:"members"` // atProvider
}

// NetworkSpec defines the desired state of Network.
type NetworkSpec struct {
	xpv1.ResourceSpec `json:",inline"`

	// ForProvider holds the user-supplied parameters for this Network.
	// +kubebuilder:validation:Required
	ForProvider NetworkParameters `json:"forProvider"`
}

// NetworkStatus defines the observed state of Network.
type NetworkStatus struct {
	xpv1.ResourceStatus `json:",inline"`

	// AtProvider holds the observed values from the Infoblox NIOS WAPI.
	// +optional
	AtProvider NetworkObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:storageversion
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,infobloxnios}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"

// Network is the Cluster-scoped managed resource representing an Infoblox NIOS Network.
type Network struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   NetworkSpec   `json:"spec"`
	Status NetworkStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NetworkList contains a list of Network.
type NetworkList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Network `json:"items"`
}
