// Code generated by hack/generate-registration.go. DO NOT EDIT.

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

package apis

import (
	"k8s.io/apimachinery/pkg/runtime"

	infobloxniosv1alpha1 "github.com/crossplane-contrib/provider-infoblox-nios/apis/v1alpha1"
)

// AddToSchemes may be used to add all resources defined in the project to a Scheme.
var AddToSchemes runtime.SchemeBuilder

func init() {
	// Register ProviderConfig types.
	AddToSchemes = append(AddToSchemes, infobloxniosv1alpha1.SchemeBuilder.AddToScheme)
}

// AddToScheme adds all Resources to the Scheme.
func AddToScheme(s *runtime.Scheme) error {
	return AddToSchemes.AddToScheme(s)
}
