// Code generated by openapi2crd. DO NOT EDIT.

// Package v1alpha1 contains the Cluster-scoped FixedAddress managed resource.
// API group: fixedaddress.infobloxnios.crossplane.io
package v1alpha1

import (
	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// FixedAddressDhcpOption is one DHCP option entry for a FixedAddress (mirrors the SDK's Dhcpoption struct).
type FixedAddressDhcpOption struct {
	// Name of the DHCP option.
	Name *string `json:"name,omitempty"`
	// The code of the DHCP option.
	Num *int64 `json:"num,omitempty"`
	// The name of the space this DHCP option is associated to.
	VendorClass *string `json:"vendorClass,omitempty"`
	// Value of the DHCP option.
	Value *string `json:"value,omitempty"`
	// Only applies to special options that are displayed separately from other options and have a use flag.
	UseOption *bool `json:"useOption,omitempty"`
}

// FixedAddressCloudInfo carries Cloud API delegation/ownership information for a cloud-managed FixedAddress (mirrors the SDK's GridCloudapiInfo struct).
type FixedAddressCloudInfo struct {
	// The Cloud Platform Appliance to which authority of the object is delegated.
	DelegatedMember *FixedAddressCloudInfoDelegatedMember `json:"delegatedMember,omitempty"`
	// Indicates the scope of delegation for the object. This can be one of the following: NONE (outside any delegation), ROOT (the delegation point), SUBTREE (within the scope of a delegation), RECLAIMING (within the scope of a delegation being reclaimed, either as the delegation point or in the subtree).
	DelegatedScope *string `json:"delegatedScope,omitempty"`
	// Indicates the root of the delegation if delegated_scope is SUBTREE or RECLAIMING. This is not set otherwise.
	DelegatedRoot *string `json:"delegatedRoot,omitempty"`
	// Determines whether the object was created by the cloud adapter or not.
	OwnedByAdaptor *bool `json:"ownedByAdaptor,omitempty"`
	// Indicates the cloud origin of the object.
	Usage *string `json:"usage,omitempty"`
	// Reference to the tenant object associated with the object, if any.
	Tenant *string `json:"tenant,omitempty"`
	// Indicates the specified cloud management platform.
	MgmtPlatform *string `json:"mgmtPlatform,omitempty"`
	// Type of authority over the object.
	AuthorityType *string `json:"authorityType,omitempty"`
}

// FixedAddressCloudInfoDelegatedMember identifies the Grid member a cloud-managed FixedAddress's authority is delegated to (mirrors the SDK's Dhcpmember struct).
type FixedAddressCloudInfoDelegatedMember struct {
	// The IPv4 Address of the Grid Member.
	Ipv4Addr *string `json:"ipv4addr,omitempty"`
	// The IPv6 Address of the Grid Member.
	Ipv6Addr *string `json:"ipv6addr,omitempty"`
	// The Grid member name
	Name *string `json:"name,omitempty"`
}

// FixedAddressParameters are the configurable fields of a FixedAddress.
// +kubebuilder:validation:XValidation:rule="(has(self.ipv4addr) && !has(self.ipv6addr)) || (!has(self.ipv4addr) && has(self.ipv6addr))",message="exactly one of ipv4addr or ipv6addr must be set (mutually exclusive address families)"
type FixedAddressParameters struct {
	// IPv4 address of the fixed address. Mutually exclusive with ipv6addr — exactly one of the two must be set. May be set statically or allocated dynamically from a CIDR (network) at create time. Changing this value changes the record's _ref (UNSTABLE external name, live-verified).
	IPv4Addr *string `json:"ipv4addr,omitempty"`
	// IPv6 address of the fixed address. Mutually exclusive with ipv4addr — exactly one of the two must be set. Selects the ipv6fixedaddress WAPI object type.
	IPv6Addr *string `json:"ipv6addr,omitempty"`
	// MAC address for MAC_ADDRESS/CIRCUIT_ID/REMOTE_ID match_client modes (IPv4 only — for IPv6 this field carries the DHCP unique identifier and AllocateIP rejects an empty value). For IPv4, the SDK defaults this to the zero MAC address (00:00:00:00:00:00) when omitted and no match_client is set, so it is not catalog-Required.
	MAC *string `json:"mac,omitempty"`
	// Network view the fixed address belongs to. Defaults to "default" when unset. Identifies a NetworkView by name.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-infoblox-nios/apis/cluster/networkview/v1alpha1.NetworkView
	NetworkView *string `json:"networkView,omitempty"`
	// +optional
	NetworkViewRef *xpv2.Reference `json:"networkViewRef,omitempty"`
	// +optional
	NetworkViewSelector *xpv2.Selector `json:"networkViewSelector,omitempty"`
	// CIDR used to resolve a dynamically-allocated address at create time, e.g. "10.0.0.0/24". Only meaningful when ipv4addr/ipv6addr is not a literal address.
	Network *string `json:"network,omitempty"`
	// Display name of the fixed address.
	Name *string `json:"name,omitempty"`
	// How the fixed IP is matched to a requesting client. CIRCUIT_ID requires agentCircuitId; REMOTE_ID requires agentRemoteId; CLIENT_ID requires dhcpClientIdentifier (business-rule constraints enforced by WAPI at apply time, not by CRD schema validation).
	// +kubebuilder:validation:Enum=MAC_ADDRESS;CLIENT_ID;RESERVED;CIRCUIT_ID;REMOTE_ID
	MatchClient *string `json:"matchClient,omitempty"`
	// Comment for the fixed address.
	Comment *string `json:"comment,omitempty"`
	// Extensible attributes (arbitrary key/value metadata defined in Grid Manager). The WAPI wire format wraps each value as {"value": ...}; this map is the simplified string-valued CRD representation (the controller translates to/from the SDK's EA map[string]interface{} type).
	// +optional
	// +kubebuilder:validation:XValidation:rule="self.all(k, k != 'Crossplane Internal ID')",message="the 'Crossplane Internal ID' extensible attribute is reserved for the provider's identity stamp and cannot be set in spec.forProvider.extAttrs"
	ExtAttrs map[string]string `json:"extAttrs"`
	// Whether the fixed address is disabled.
	Disable *bool `json:"disable,omitempty"`
	// Agent circuit ID. Required by WAPI when matchClient is CIRCUIT_ID (business rule, not CRD-enforced).
	AgentCircuitID *string `json:"agentCircuitId,omitempty"`
	// Agent remote ID. Required by WAPI when matchClient is REMOTE_ID (business rule, not CRD-enforced).
	AgentRemoteID *string `json:"agentRemoteId,omitempty"`
	// Whether a leading zero is prepended to the client identifier.
	ClientIdentifierPrependZero *bool `json:"clientIdentifierPrependZero,omitempty"`
	// DHCP client identifier. Required by WAPI when matchClient is CLIENT_ID (business rule, not CRD-enforced).
	DHCPClientIdentifier *string `json:"dhcpClientIdentifier,omitempty"`
	// DHCP options for the fixed address.
	// +optional
	Options []*FixedAddressDhcpOption `json:"options"`
	// Use flag for options.
	UseOptions *bool `json:"useOptions,omitempty"`
}

// FixedAddressObservation holds the observed state of a FixedAddress.
// It mirrors every FixedAddressParameters field plus response-only fields
// (full-mirror AtProvider) so users can compare forProvider to
// atProvider before switching to full management
// (managementPolicies: ["Observe"]).
type FixedAddressObservation struct {
	// Server-assigned external identifier for this resource, set by Observe()
	// from the resource's external name. Used by import testing to confirm
	// the controller re-discovers the resource after a restart.
	// +optional
	ID string `json:"id,omitempty"` // atProvider
	// IPv4 address of the fixed address. Mutually exclusive with ipv6addr — exactly one of the two must be set. May be set statically or allocated dynamically from a CIDR (network) at create time. Changing this value changes the record's _ref (UNSTABLE external name, live-verified).
	IPv4Addr *string `json:"ipv4addr,omitempty"` // atProvider
	// IPv6 address of the fixed address. Mutually exclusive with ipv4addr — exactly one of the two must be set. Selects the ipv6fixedaddress WAPI object type.
	IPv6Addr *string `json:"ipv6addr,omitempty"` // atProvider
	// MAC address for MAC_ADDRESS/CIRCUIT_ID/REMOTE_ID match_client modes (IPv4 only — for IPv6 this field carries the DHCP unique identifier and AllocateIP rejects an empty value). For IPv4, the SDK defaults this to the zero MAC address (00:00:00:00:00:00) when omitted and no match_client is set, so it is not catalog-Required.
	MAC *string `json:"mac,omitempty"` // atProvider
	// Network view the fixed address belongs to. Defaults to "default" when unset. Identifies a NetworkView by name.
	NetworkView *string `json:"networkView,omitempty"` // atProvider
	// CIDR used to resolve a dynamically-allocated address at create time, e.g. "10.0.0.0/24". Only meaningful when ipv4addr/ipv6addr is not a literal address.
	Network *string `json:"network,omitempty"` // atProvider
	// Display name of the fixed address.
	Name *string `json:"name,omitempty"` // atProvider
	// How the fixed IP is matched to a requesting client. CIRCUIT_ID requires agentCircuitId; REMOTE_ID requires agentRemoteId; CLIENT_ID requires dhcpClientIdentifier (business-rule constraints enforced by WAPI at apply time, not by CRD schema validation).
	MatchClient *string `json:"matchClient,omitempty"` // atProvider
	// Comment for the fixed address.
	Comment *string `json:"comment,omitempty"` // atProvider
	// Extensible attributes (arbitrary key/value metadata defined in Grid Manager). The WAPI wire format wraps each value as {"value": ...}; this map is the simplified string-valued CRD representation (the controller translates to/from the SDK's EA map[string]interface{} type).
	// +optional
	ExtAttrs map[string]string `json:"extAttrs"` // atProvider
	// Whether the fixed address is disabled.
	Disable *bool `json:"disable,omitempty"` // atProvider
	// Agent circuit ID. Required by WAPI when matchClient is CIRCUIT_ID (business rule, not CRD-enforced).
	AgentCircuitID *string `json:"agentCircuitId,omitempty"` // atProvider
	// Agent remote ID. Required by WAPI when matchClient is REMOTE_ID (business rule, not CRD-enforced).
	AgentRemoteID *string `json:"agentRemoteId,omitempty"` // atProvider
	// Whether a leading zero is prepended to the client identifier.
	ClientIdentifierPrependZero *bool `json:"clientIdentifierPrependZero,omitempty"` // atProvider
	// DHCP client identifier. Required by WAPI when matchClient is CLIENT_ID (business rule, not CRD-enforced).
	DHCPClientIdentifier *string `json:"dhcpClientIdentifier,omitempty"` // atProvider
	// DHCP options for the fixed address.
	// +optional
	Options []*FixedAddressDhcpOption `json:"options"` // atProvider
	// Use flag for options.
	UseOptions *bool `json:"useOptions,omitempty"` // atProvider
	// Server-assigned opaque object reference (WAPI `_ref`). Mirrors the crossplane.io/external-name annotation for observability and uptest import verification. UNSTABLE — changes when ipv4addr changes (live-verified).
	Ref *string `json:"ref,omitempty"` // atProvider
	// DHCP unique identifier. IPv6 only — this field exists on the shared Go SDK struct but is only ever populated by WAPI for the ipv6fixedaddress object type, not the IPv4 fixedaddress object type (live-verified).
	DUID *string `json:"duid,omitempty"` // atProvider
	// Cloud API related information for this object (cloud-managed fixed addresses only).
	CloudInfo *FixedAddressCloudInfo `json:"cloudInfo,omitempty"` // atProvider
}

// FixedAddressSpec defines the desired state of FixedAddress.
type FixedAddressSpec struct {
	xpv2.ClusterManagedResourceSpec `json:",inline"`

	// ForProvider holds the user-supplied parameters for this FixedAddress.
	// +kubebuilder:validation:Required
	ForProvider FixedAddressParameters `json:"forProvider"`
}

// FixedAddressStatus defines the observed state of FixedAddress.
type FixedAddressStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`

	// AtProvider holds the observed values from the Infoblox NIOS WAPI.
	// +optional
	AtProvider FixedAddressObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:storageversion
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,infobloxnios}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"

// FixedAddress is the Cluster-scoped managed resource representing an Infoblox NIOS FixedAddress.
type FixedAddress struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   FixedAddressSpec   `json:"spec"`
	Status FixedAddressStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FixedAddressList contains a list of FixedAddress.
type FixedAddressList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []FixedAddress `json:"items"`
}
