// Code generated by openapi2crd. DO NOT EDIT.

// Package v1alpha1 contains the Namespaced-scoped AliasRecord managed resource
// for the infobloxnios provider.
// +kubebuilder:object:generate=true
// +groupName=recordalias.infobloxnios.m.crossplane.io
// +versionName=v1alpha1
package v1alpha1
