// Code generated by openapi2crd. DO NOT EDIT.

// Package v1alpha1 contains the Namespaced-scoped AliasRecord managed resource.
// API group: recordalias.infobloxnios.m.crossplane.io
package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	xpv2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// AliasRecordParameters are the configurable fields of a AliasRecord.
type AliasRecordParameters struct {
	// Alias name in FQDN format. Renaming changes the record's _ref.
	// +kubebuilder:validation:Required
	Name *string `json:"name"`
	// Target name in FQDN format that this alias resolves to. Live-verified: updating this field does not change the record's _ref.
	// +kubebuilder:validation:Required
	TargetName *string `json:"targetName"`
	// Record type the alias resolves to.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Enum=A;AAAA;MX;NAPTR;PTR;SPF;SRV;TXT
	TargetType *string `json:"targetType"`
	// DNS view in which the record resides, e.g. "external". Soft-immutable: the WAPI schema advertises this field as updatable, but a live update attempt is rejected at the data level, so it is treated as fixed at creation.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="view is immutable after creation"
	View *string `json:"view"`
	// Comment for the record; maximum 256 characters.
	Comment *string `json:"comment,omitempty"`
	// Whether the record is disabled. Unlike most other DNS record types in this catalog, Alias exposes this field via the SDK's ObjectManager wrapper.
	Disable *bool `json:"disable,omitempty"`
	// Time-to-live in seconds. Zero means the record is not cached. Must be non-negative (0-2147483647); to inherit the zone/grid default, set useTtl to false rather than passing a negative sentinel value.
	// +kubebuilder:validation:Minimum=0
	// +kubebuilder:validation:Maximum=2147483647
	TTL *uint32 `json:"ttl,omitempty"`
	// Use flag for ttl — when false the zone/grid default TTL applies.
	UseTTL *bool `json:"useTtl,omitempty"`
	// Extensible attributes (arbitrary key/value metadata defined in Grid Manager). The WAPI wire format wraps each value as {"value": ...}; this map is the simplified string-valued CRD representation (the controller translates to/from the SDK's EA map[string]interface{} type).
	// +optional
	ExtAttrs map[string]string `json:"extAttrs"`
}

// AliasRecordObservation holds the observed state of a AliasRecord.
// It mirrors every AliasRecordParameters field plus response-only fields
// (full-mirror AtProvider) so users can compare forProvider to
// atProvider before switching to full management
// (managementPolicies: ["Observe"]).
type AliasRecordObservation struct {
	// Server-assigned external identifier for this resource, set by Observe()
	// from the resource's external name. Used by import testing to confirm
	// the controller re-discovers the resource after a restart.
	// +optional
	ID string `json:"id,omitempty"` // atProvider
	// Alias name in FQDN format. Renaming changes the record's _ref.
	Name *string `json:"name,omitempty"` // atProvider
	// Target name in FQDN format that this alias resolves to. Live-verified: updating this field does not change the record's _ref.
	TargetName *string `json:"targetName,omitempty"` // atProvider
	// Record type the alias resolves to.
	TargetType *string `json:"targetType,omitempty"` // atProvider
	// DNS view in which the record resides, e.g. "external". Soft-immutable: the WAPI schema advertises this field as updatable, but a live update attempt is rejected at the data level, so it is treated as fixed at creation.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="view is immutable after creation"
	View *string `json:"view,omitempty"` // atProvider
	// Comment for the record; maximum 256 characters.
	Comment *string `json:"comment,omitempty"` // atProvider
	// Whether the record is disabled. Unlike most other DNS record types in this catalog, Alias exposes this field via the SDK's ObjectManager wrapper.
	Disable *bool `json:"disable,omitempty"` // atProvider
	// Time-to-live in seconds. Zero means the record is not cached. Must be non-negative (0-2147483647); to inherit the zone/grid default, set useTtl to false rather than passing a negative sentinel value.
	TTL *uint32 `json:"ttl,omitempty"` // atProvider
	// Use flag for ttl — when false the zone/grid default TTL applies.
	UseTTL *bool `json:"useTtl,omitempty"` // atProvider
	// Extensible attributes (arbitrary key/value metadata defined in Grid Manager). The WAPI wire format wraps each value as {"value": ...}; this map is the simplified string-valued CRD representation (the controller translates to/from the SDK's EA map[string]interface{} type).
	// +optional
	ExtAttrs map[string]string `json:"extAttrs"` // atProvider
	// Server-assigned opaque object reference (WAPI `_ref`). Mirrors the crossplane.io/external-name annotation for observability and uptest import verification.
	Ref *string `json:"ref,omitempty"` // atProvider
	// Zone in which the record resides, e.g. "zone.com". Derived from name/view by WAPI — not a CreateAliasRecord parameter, so it has no ForProvider counterpart.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="zone is immutable after creation"
	Zone *string `json:"zone,omitempty"` // atProvider
}

// AliasRecordSpec defines the desired state of AliasRecord.
type AliasRecordSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`

	// ForProvider holds the user-supplied parameters for this AliasRecord.
	// +kubebuilder:validation:Required
	ForProvider AliasRecordParameters `json:"forProvider"`
}

// AliasRecordStatus defines the observed state of AliasRecord.
type AliasRecordStatus struct {
	xpv1.ResourceStatus `json:",inline"`

	// AtProvider holds the observed values from the Infoblox NIOS WAPI.
	// +optional
	AtProvider AliasRecordObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:storageversion
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,infobloxnios}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"

// AliasRecord is the Namespaced-scoped managed resource representing an Infoblox NIOS AliasRecord.
type AliasRecord struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   AliasRecordSpec   `json:"spec"`
	Status AliasRecordStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AliasRecordList contains a list of AliasRecord.
type AliasRecordList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AliasRecord `json:"items"`
}
