package catalog

import "github.com/crossplane-contrib/provider-infoblox-nios/tools/openapi/pkg/model"

func dtcPool() model.Resource {
	return model.Resource{
		Slug:           "dtc_pool",
		Kind:           "DTCPool",
		WAPIObjectType: "dtc:pool",
		Pattern:        model.PatternCRUD,
		GoStructName:   "DtcPool",
		CRUD: []model.CRUDMethod{
			{Operation: "Create", Method: "CreateDtcPool", Receiver: "ObjectManager"},
			{Operation: "Read", Method: "GetDtcPool", Receiver: "ObjectManager"},
			{Operation: "ReadByRef", Method: "GetDtcPoolByRef", Receiver: "ObjectManager"},
			{Operation: "Read", Method: "GetAllDtcPool", Receiver: "ObjectManager", Notes: "List/query variant."},
			{Operation: "Update", Method: "UpdateDtcPool", Receiver: "ObjectManager"},
			{Operation: "Delete", Method: "DeleteDtcPool", Receiver: "ObjectManager"},
		},
		ExternalNameStrategy:   model.StrategyServerAssigned,
		ExternalNameRationale:  "WAPI assigns an opaque `_ref` on POST; name is mutable so it cannot serve as the external-name.",
		ExternalNameSourcePath: "_ref",
		Fields: []model.Field{
			f("_ref", "string", model.FieldScopeResponse, false, false, "Server-assigned opaque object reference. This is the Crossplane external-name."),
			f("name", "*string", model.FieldScopeBoth, true, false, "DTC Pool display name."),
			f("comment", "*string", model.FieldScopeBoth, false, false, "Comment for the DTC Pool; maximum 256 characters."),
			f("disable", "*bool", model.FieldScopeBoth, false, false, "Whether the DTC Pool is disabled."),
			f("extattrs", "EA", model.FieldScopeBoth, false, false, "Extensible attributes."),
			fEnum("availability", "string", model.FieldScopeBoth, false, false, "Determines when a pool member is considered available.", "ANY", "QUORUM", "ALL"),
			f("quorum", "*uint32", model.FieldScopeBoth, false, false, "Minimum number of monitors that must report a resource as up (availability=QUORUM)."),
			fEnum("lb_preferred_method", "string", model.FieldScopeBoth, false, false, "Preferred load balancing method.", "ROUND_ROBIN", "RATIO", "TOPOLOGY", "DYNAMIC_RATIO", "GLOBAL_AVAILABILITY", "SOURCE_IP_HASH"),
			f("lb_preferred_topology", "*string", model.FieldScopeBoth, false, false, "Topology ruleset name (lb_preferred_method=TOPOLOGY)."),
			f("lb_dynamic_ratio_preferred", "*SettingDynamicratio", model.FieldScopeBoth, false, false, "Dynamic-ratio settings (lb_preferred_method=DYNAMIC_RATIO)."),
			fEnum("lb_alternate_method", "string", model.FieldScopeBoth, false, false, "Fallback load balancing method if the preferred method returns no results. NONE is accepted for backward compatibility with existing manifests, but the backend never accepts it as an explicit write value \u2014 it only appears on read-back as the server's default when the field is left unset; the controller normalizes it to \"unset\" on both the read and write paths.", "NONE", "ROUND_ROBIN", "RATIO", "TOPOLOGY", "DYNAMIC_RATIO", "GLOBAL_AVAILABILITY", "ALL_AVAILABLE"),
			f("lb_alternate_topology", "*string", model.FieldScopeBoth, false, false, "Topology ruleset name (lb_alternate_method=TOPOLOGY)."),
			f("lb_dynamic_ratio_alternate", "*SettingDynamicratio", model.FieldScopeBoth, false, false, "Dynamic-ratio settings (lb_alternate_method=DYNAMIC_RATIO)."),
			f("servers", "[]*DtcServerLink", model.FieldScopeBoth, false, false, "DTC Servers that are members of this pool, with per-server ratio/weight."),
			f("monitors", "[]*DtcMonitorHttp", model.FieldScopeBoth, false, false, "Health monitors associated with the pool (Create accepts []Monitor; Get returns []*DtcMonitorHttp \u2014 the SDK's Monitor interface covers several concrete monitor types)."),
			f("auto_consolidated_monitors", "*bool", model.FieldScopeBoth, false, false, "Whether DTC Consolidated Monitors are auto-managed."),
			f("consolidated_monitors", "[]*DtcPoolConsolidatedMonitorHealth", model.FieldScopeResponse, false, false, "Consolidated monitor health status. Read-only on Get; Update accepts a differently-shaped []map[string]interface{} for this (\"consolidatedMonitors\" param), not the typed response struct."),
			f("ttl", "*uint32", model.FieldScopeBoth, false, false, "TTL for the DTC Pool response."),
			f("use_ttl", "*bool", model.FieldScopeBoth, false, false, "Use flag for ttl."),
			f("health", "*DtcHealth", model.FieldScopeResponse, false, false, "Aggregate health status of the pool."),
		},
		ImmutableFields: []string{},
		MutableFields:   []string{"name", "comment", "disable", "extattrs", "availability", "quorum", "lb_preferred_method", "lb_preferred_topology", "lb_dynamic_ratio_preferred", "lb_alternate_method", "lb_alternate_topology", "lb_dynamic_ratio_alternate", "servers", "monitors", "auto_consolidated_monitors", "ttl", "use_ttl"},
		DeleteBehavior:  "hard-delete (404 on subsequent GET) — inferred; not independently live-verified.",
		Notes:           "DNS Traffic Control (load balancing) pool. Fully mutable via the wrapper \u2014 no immutable fields identified from the Create/Update signature diff.",
	}
}

func dtcServer() model.Resource {
	return model.Resource{
		Slug:           "dtc_server",
		Kind:           "DTCServer",
		WAPIObjectType: "dtc:server",
		Pattern:        model.PatternCRUD,
		GoStructName:   "DtcServer",
		CRUD: []model.CRUDMethod{
			{Operation: "Create", Method: "CreateDtcServer", Receiver: "ObjectManager"},
			{Operation: "Read", Method: "GetDtcServer", Receiver: "ObjectManager"},
			{Operation: "ReadByRef", Method: "GetDtcServerByRef", Receiver: "ObjectManager"},
			{Operation: "Read", Method: "GetAllDtcServer", Receiver: "ObjectManager", Notes: "List/query variant."},
			{Operation: "Update", Method: "UpdateDtcServer", Receiver: "ObjectManager"},
			{Operation: "Delete", Method: "DeleteDtcServer", Receiver: "ObjectManager"},
		},
		ExternalNameStrategy:   model.StrategyServerAssigned,
		ExternalNameRationale:  "WAPI assigns an opaque `_ref` on POST; name is mutable so it cannot serve as the external-name.",
		ExternalNameSourcePath: "_ref",
		Fields: []model.Field{
			f("_ref", "string", model.FieldScopeResponse, false, false, "Server-assigned opaque object reference. This is the Crossplane external-name."),
			f("name", "*string", model.FieldScopeBoth, true, false, "DTC Server display name."),
			f("host", "*string", model.FieldScopeBoth, true, false, "Address or FQDN of the backend server."),
			f("comment", "*string", model.FieldScopeBoth, false, false, "Comment for the DTC Server; maximum 256 characters."),
			f("disable", "*bool", model.FieldScopeBoth, false, false, "Whether the DTC Server is disabled."),
			f("extattrs", "EA", model.FieldScopeBoth, false, false, "Extensible attributes."),
			f("auto_create_host_record", "*bool", model.FieldScopeBoth, false, false, "Whether a read-only A/AAAA/CNAME host record is auto-created and kept in sync with `host`."),
			f("monitors", "[]*DtcServerMonitor", model.FieldScopeBoth, false, false, "IP/FQDN and monitor pairs used for additional health monitoring."),
			f("sni_hostname", "*string", model.FieldScopeBoth, false, false, "Hostname for Server Name Indication (SNI)."),
			f("use_sni_hostname", "*bool", model.FieldScopeBoth, false, false, "Use flag for sni_hostname."),
			f("health", "*DtcHealth", model.FieldScopeResponse, false, false, "Health status of the server."),
		},
		ImmutableFields: []string{},
		MutableFields:   []string{"name", "host", "comment", "disable", "extattrs", "auto_create_host_record", "monitors", "sni_hostname", "use_sni_hostname"},
		DeleteBehavior:  "hard-delete (404 on subsequent GET) — inferred; not independently live-verified.",
		Notes:           "DTC backend server referenced by DTCPool.servers. Fully mutable via the wrapper.",
		CrossReferences: []model.CrossReference{},
	}
}

func dtcLbdn() model.Resource {
	return model.Resource{
		Slug:           "dtc_lbdn",
		Kind:           "DTCLBDN",
		WAPIObjectType: "dtc:lbdn",
		Pattern:        model.PatternCRUD,
		GoStructName:   "DtcLbdn",
		CRUD: []model.CRUDMethod{
			{Operation: "Create", Method: "CreateDtcLbdn", Receiver: "ObjectManager"},
			{Operation: "ReadByRef", Method: "GetDtcLbdnByRef", Receiver: "ObjectManager"},
			{Operation: "Read", Method: "GetDtcLbdn", Receiver: "ObjectManager"},
			{Operation: "Read", Method: "GetAllDtcLbdn", Receiver: "ObjectManager", Notes: "List/query variant."},
			{Operation: "Update", Method: "UpdateDtcLbdn", Receiver: "ObjectManager"},
			{Operation: "Delete", Method: "DeleteDtcLbdn", Receiver: "ObjectManager"},
		},
		ExternalNameStrategy:   model.StrategyServerAssigned,
		ExternalNameRationale:  "WAPI assigns an opaque `_ref` on POST; name is mutable so it cannot serve as the external-name.",
		ExternalNameSourcePath: "_ref",
		Fields: []model.Field{
			f("_ref", "string", model.FieldScopeResponse, false, false, "Server-assigned opaque object reference. This is the Crossplane external-name."),
			f("name", "*string", model.FieldScopeBoth, true, false, "DTC LBDN display name (not DNS-related)."),
			f("auth_zones", "[]*ZoneAuth", model.FieldScopeBoth, false, false, "Authoritative zones the LBDN's patterns are matched against."),
			f("patterns", "[]string", model.FieldScopeBoth, false, false, "FQDN wildcard patterns matched against incoming queries."),
			fEnum("types", "[]string", model.FieldScopeBoth, false, false, "Resource record types the LBDN answers with.", "A", "AAAA", "CNAME", "NAPTR", "SRV"),
			fEnum("lb_method", "string", model.FieldScopeBoth, false, false, "Load balancing method used to select a pool.", "ROUND_ROBIN", "RATIO", "TOPOLOGY", "GLOBAL_AVAILABILITY"),
			f("pools", "[]*DtcPoolLink", model.FieldScopeBoth, false, false, "Pools associated with this LBDN, with per-pool ratio."),
			f("priority", "*uint32", model.FieldScopeBoth, false, false, "Match priority among overlapping LBDNs (lower ordinal wins)."),
			f("persistence", "*uint32", model.FieldScopeBoth, false, false, "Seconds to cache a client-specific LBDN response. Zero disables caching."),
			f("topology", "*string", model.FieldScopeBoth, false, false, "Topology ruleset name (lb_method=TOPOLOGY)."),
			f("ttl", "*uint32", model.FieldScopeBoth, false, false, "TTL for the DTC LBDN response."),
			f("use_ttl", "*bool", model.FieldScopeBoth, false, false, "Use flag for ttl."),
			f("comment", "*string", model.FieldScopeBoth, false, false, "Comment for the DTC LBDN; maximum 256 characters."),
			f("disable", "*bool", model.FieldScopeBoth, false, false, "Whether the DTC LBDN is disabled."),
			f("extattrs", "EA", model.FieldScopeBoth, false, false, "Extensible attributes."),
			f("auto_consolidated_monitors", "*bool", model.FieldScopeBoth, false, false, "Whether DTC Consolidated Monitors are auto-managed on related pools."),
			f("health", "*DtcHealth", model.FieldScopeResponse, false, false, "Aggregate health status of the LBDN."),
		},
		ImmutableFields: []string{},
		MutableFields:   []string{"name", "auth_zones", "patterns", "types", "lb_method", "pools", "priority", "persistence", "topology", "ttl", "use_ttl", "comment", "disable", "extattrs", "auto_consolidated_monitors"},
		DeleteBehavior:  "hard-delete (404 on subsequent GET) — inferred; not independently live-verified.",
		Notes:           "DNS Traffic Control load-balanced DNS name (LBDN = Load Balanced Domain Name). Fully mutable via the wrapper. Depends on DTCPool (pools) and ZoneAuth (auth_zones).",
		CrossReferences: []model.CrossReference{
			{FieldPath: "pools", TargetKind: "DTCPool", TargetScope: "cluster", Extractor: "external-name", Compound: false},
			{FieldPath: "authZones", TargetKind: "ZoneAuth", TargetScope: "cluster", Extractor: "external-name", Compound: false},
		},
	}
}
