// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1alpha1 "github.com/crossplane-contrib/provider-infoblox-nios/apis/namespaced/recorda/v1alpha1"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this PTRRecord.
func (mg *PTRRecord) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Ptrdname),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.PtrdnameRef,
		Selector:     mg.Spec.ForProvider.PtrdnameSelector,
		To: reference.To{
			List:    &v1alpha1.ARecordList{},
			Managed: &v1alpha1.ARecord{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Ptrdname")
	}
	mg.Spec.ForProvider.Ptrdname = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.PtrdnameRef = rsp.ResolvedReference

	return nil
}
