// Code generated by openapi2crd. DO NOT EDIT.

// Package dtcserver contains a standalone reference copy of the Parameters
// and Observation types for the DTCServer managed resource. The
// cluster-scoped and namespaced variants (apis/cluster/dtcserver/,
// apis/namespaced/dtcserver/) generate self-contained copies of these same
// types rather than importing this package — see the openapi2crd/pkg/
// generator package doc comment for the rationale.
package dtcserver

// DTCServerMonitor identifies one IP/FQDN and monitor pair used for additional health monitoring of a DTCServer (mirrors the SDK's DtcServerMonitor struct).
type DTCServerMonitor struct {
	// Reference of the monitor associated with the server.
	Monitor *string `json:"monitor,omitempty"`
	// IP address or FQDN of the server used for monitoring.
	Host *string `json:"host,omitempty"`
}

// DTCServerHealth carries the aggregate health status of a DTCServer (mirrors the SDK's DtcHealth struct).
type DTCServerHealth struct {
	// The availability color status.
	Availability *string `json:"availability,omitempty"`
	// The textual description of the object's status.
	Description *string `json:"description,omitempty"`
	// The enabled state of the object.
	EnabledState *string `json:"enabledState,omitempty"`
}

// DTCServerParameters are the configurable fields of a DTCServer.
type DTCServerParameters struct {
	// DTC Server display name.
	// +kubebuilder:validation:Required
	Name *string `json:"name"`
	// Address or FQDN of the backend server.
	// +kubebuilder:validation:Required
	Host *string `json:"host"`
	// Comment for the DTC Server; maximum 256 characters.
	Comment *string `json:"comment,omitempty"`
	// Whether the DTC Server is disabled.
	Disable *bool `json:"disable,omitempty"`
	// Whether a read-only A/AAAA/CNAME host record is auto-created for host and kept in sync with it.
	AutoCreateHostRecord *bool `json:"autoCreateHostRecord,omitempty"`
	// Hostname for Server Name Indication (SNI), in FQDN format.
	SniHostname *string `json:"sniHostname,omitempty"`
	// Use flag for sniHostname.
	UseSniHostname *bool `json:"useSniHostname,omitempty"`
	// IP/FQDN and monitor pairs used for additional health monitoring.
	// +optional
	Monitors []DTCServerMonitor `json:"monitors"`
	// Extensible attributes (arbitrary key/value metadata defined in Grid Manager). The WAPI wire format wraps each value as {"value": ...}; this map is the simplified string-valued CRD representation (the controller translates to/from the SDK's EA map[string]interface{} type).
	// +optional
	// +kubebuilder:validation:XValidation:rule="self.all(k, k != 'Crossplane Internal ID')",message="the 'Crossplane Internal ID' extensible attribute is reserved for the provider's identity stamp and cannot be set in spec.forProvider.extAttrs"
	ExtAttrs map[string]string `json:"extAttrs"`
}

// DTCServerObservation holds the observed state of a DTCServer.
// It mirrors every DTCServerParameters field plus response-only fields
// (full-mirror AtProvider) so users can compare forProvider to
// atProvider before switching to full management
// (managementPolicies: ["Observe"]).
type DTCServerObservation struct {
	// Server-assigned external identifier for this resource, set by Observe()
	// from the resource's external name. Used by import testing to confirm
	// the controller re-discovers the resource after a restart.
	// +optional
	ID string `json:"id,omitempty"` // atProvider
	// DTC Server display name.
	Name *string `json:"name,omitempty"` // atProvider
	// Address or FQDN of the backend server.
	Host *string `json:"host,omitempty"` // atProvider
	// Comment for the DTC Server; maximum 256 characters.
	Comment *string `json:"comment,omitempty"` // atProvider
	// Whether the DTC Server is disabled.
	Disable *bool `json:"disable,omitempty"` // atProvider
	// Whether a read-only A/AAAA/CNAME host record is auto-created for host and kept in sync with it.
	AutoCreateHostRecord *bool `json:"autoCreateHostRecord,omitempty"` // atProvider
	// Hostname for Server Name Indication (SNI), in FQDN format.
	SniHostname *string `json:"sniHostname,omitempty"` // atProvider
	// Use flag for sniHostname.
	UseSniHostname *bool `json:"useSniHostname,omitempty"` // atProvider
	// IP/FQDN and monitor pairs used for additional health monitoring.
	// +optional
	Monitors []DTCServerMonitor `json:"monitors"` // atProvider
	// Extensible attributes (arbitrary key/value metadata defined in Grid Manager). The WAPI wire format wraps each value as {"value": ...}; this map is the simplified string-valued CRD representation (the controller translates to/from the SDK's EA map[string]interface{} type).
	// +optional
	ExtAttrs map[string]string `json:"extAttrs"` // atProvider
	// Server-assigned opaque object reference (WAPI `_ref`). Mirrors the crossplane.io/external-name annotation for observability and uptest import verification.
	Ref *string `json:"ref,omitempty"` // atProvider
	// Health status of the server.
	Health *DTCServerHealth `json:"health,omitempty"` // atProvider
}
