// Code generated by openapi2crd. DO NOT EDIT.

// Package recordcname contains a standalone reference copy of the Parameters
// and Observation types for the CNAMERecord managed resource. The
// cluster-scoped and namespaced variants (apis/cluster/recordcname/,
// apis/namespaced/recordcname/) generate self-contained copies of these same
// types rather than importing this package — see the openapi2crd/pkg/
// generator package doc comment for the rationale.
package recordcname

import (
	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// CNAMERecordParameters are the configurable fields of a CNAMERecord.
type CNAMERecordParameters struct {
	// Alias name in FQDN format for the CNAME record. Renaming changes the record's _ref.
	// +kubebuilder:validation:Required
	Name *string `json:"name"`
	// Canonical (target) name in FQDN format. WAPI does not require the target to exist, so canonicalRef/canonicalSelector are optional convenience for resolving an ARecord's FQDN — this field may also be set directly as a plain FQDN string.
	// +kubebuilder:validation:Required
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-infoblox-nios/apis/cluster/recorda/v1alpha1.ARecord
	Canonical *string `json:"canonical"`
	// +optional
	CanonicalRef *xpv2.Reference `json:"canonicalRef,omitempty"`
	// +optional
	CanonicalSelector *xpv2.Selector `json:"canonicalSelector,omitempty"`
	// Comment for the record; maximum 256 characters.
	Comment *string `json:"comment,omitempty"`
	// Time-to-live in seconds. Zero means the record is not cached. Must be non-negative (0-2147483647); to inherit the zone/grid default, set useTtl to false rather than passing a negative sentinel value.
	// +kubebuilder:validation:Minimum=0
	// +kubebuilder:validation:Maximum=2147483647
	TTL *uint32 `json:"ttl,omitempty"`
	// Use flag for ttl — when false the zone/grid default TTL applies.
	UseTTL *bool `json:"useTtl,omitempty"`
	// Extensible attributes (arbitrary key/value metadata defined in Grid Manager). The WAPI wire format wraps each value as {"value": ...}; this map is the simplified string-valued CRD representation (the controller translates to/from the SDK's EA map[string]interface{} type).
	// +optional
	// +kubebuilder:validation:XValidation:rule="self.all(k, k != 'Crossplane Internal ID')",message="the 'Crossplane Internal ID' extensible attribute is reserved for the provider's identity stamp and cannot be set in spec.forProvider.extAttrs"
	ExtAttrs map[string]string `json:"extAttrs"`
	// DNS view in which the record resides, e.g. "external". Fixed at creation — WAPI ties the record's _ref to (view, zone, name). Schema-level supports=rwus (soft-mutable) but WAPI rejects the update at the data level ("A parent was not found"), so it is treated as immutable.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="view is immutable after creation"
	View *string `json:"view"`
}

// CNAMERecordObservation holds the observed state of a CNAMERecord.
// It mirrors every CNAMERecordParameters field plus response-only fields
// (full-mirror AtProvider) so users can compare forProvider to
// atProvider before switching to full management
// (managementPolicies: ["Observe"]).
type CNAMERecordObservation struct {
	// Server-assigned external identifier for this resource, set by Observe()
	// from the resource's external name. Used by import testing to confirm
	// the controller re-discovers the resource after a restart.
	// +optional
	ID string `json:"id,omitempty"` // atProvider
	// Alias name in FQDN format for the CNAME record. Renaming changes the record's _ref.
	Name *string `json:"name,omitempty"` // atProvider
	// Canonical (target) name in FQDN format. WAPI does not require the target to exist, so canonicalRef/canonicalSelector are optional convenience for resolving an ARecord's FQDN — this field may also be set directly as a plain FQDN string.
	Canonical *string `json:"canonical,omitempty"` // atProvider
	// Comment for the record; maximum 256 characters.
	Comment *string `json:"comment,omitempty"` // atProvider
	// Time-to-live in seconds. Zero means the record is not cached. Must be non-negative (0-2147483647); to inherit the zone/grid default, set useTtl to false rather than passing a negative sentinel value.
	TTL *uint32 `json:"ttl,omitempty"` // atProvider
	// Use flag for ttl — when false the zone/grid default TTL applies.
	UseTTL *bool `json:"useTtl,omitempty"` // atProvider
	// Extensible attributes (arbitrary key/value metadata defined in Grid Manager). The WAPI wire format wraps each value as {"value": ...}; this map is the simplified string-valued CRD representation (the controller translates to/from the SDK's EA map[string]interface{} type).
	// +optional
	ExtAttrs map[string]string `json:"extAttrs"` // atProvider
	// DNS view in which the record resides, e.g. "external". Fixed at creation — WAPI ties the record's _ref to (view, zone, name). Schema-level supports=rwus (soft-mutable) but WAPI rejects the update at the data level ("A parent was not found"), so it is treated as immutable.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="view is immutable after creation"
	View *string `json:"view,omitempty"` // atProvider
	// Server-assigned opaque object reference (WAPI `_ref`). Mirrors the crossplane.io/external-name annotation for observability and uptest import verification.
	Ref *string `json:"ref,omitempty"` // atProvider
	// Zone in which the record resides, e.g. "zone.com". Derived from name/view by WAPI — not a CreateCNAMERecord parameter, so it has no ForProvider counterpart.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="zone is immutable after creation"
	Zone *string `json:"zone,omitempty"` // atProvider
}
